### PR TITLE
Stop IAR warning about goto skipping variable definition

### PR DESCRIPTION
**Pull request by daverodgman**
## Description

Re-visit #8352

## PR checklist

- [x] **changelog** not required
- [x] **backport** #8403 
- [x] **tests** not required

### CODE REVIEW

**Comment by daverodgman** [comment]
Draft for now (IAR license has expired, waiting for this to be renewed to test).

**Comment by daverodgman** [comment]
@tom-cosgrove-arm @gilles-peskine-arm does one of you want to review this one? thanks

**Comment by gilles-peskine-arm** [comment]
I've added this pull request to the non-roadmap board, where anyone on the team can pick it up.

**Comment by daverodgman** [comment]
Now tested. This gives a clean build with IAR 9.4 (with default config).

**Comment by gilles-peskine-arm** [comment]
> This gives a clean build with IAR 9.4 (with default config).

This will remain an uphill path until we get IAR back in the CI.

**Comment by tom-cosgrove-arm** [comment]
Just to confirm: no backport because (1) not applicable (this code isn't in the LTS branch) or (2) we're not backporting compiler warning fixes?

**Comment by daverodgman** [comment]
> Just to confirm: no backport because (1) not applicable (this code isn't in the LTS branch) or (2) we're not backporting compiler warning fixes?

I wasn't going to because of (2), but, it is an easy backport and results in a clean build for 2.28, so no objection to a backport?

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Pull request merged**
