### PR TITLE
Fix typo in psa_key_production_parameters_t doc: 65535 should be 65537

### PR DESCRIPTION
**Pull request by tom-cosgrove-arm**
## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [ ] **changelog** ~provided, or~ not required
- [ ] **backport** ~done, or~ not required - `psa_generate_key_ext()` was added to `development` only
- [ ] **tests** ~provided, or~ not required

### CODE REVIEW

**Comment by tom-cosgrove-arm** [comment]
Marked `do-not-merge` as this PR will hopefully come in via the release mergeback

**Review by tom-daubney-arm — APPROVED** [review]
LGTM.

**Review by Ryan-Everett-arm — APPROVED** [review]
LGTM

**Comment by tom-cosgrove-arm** [comment]
Merged in via release - thanks for reviews

**Pull request closed without merging**
