### PR TITLE
Backport 3.6: Fix uint32_t printed as unsigned int

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/9225

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required
- [x] **3.6 backport** of https://github.com/Mbed-TLS/mbedtls/pull/9225
- [x] **2.28 backport** not required
- [x] **tests** locally

### CODE REVIEW

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM - faithful backport

**Comment by tom-cosgrove-arm** [comment]
I've kicked the CI to re-run the pr-head jobs, as these seem to be transient errors

**Review by paul-elliott-arm — APPROVED** [review]
LGTM - Faithful backport.

**Comment by tom-cosgrove-arm** [comment]
Just needs the CI to finish, then can be merged together with #9225

**Pull request merged**
