### PR TITLE
Create Cipher light

### LINKED ISSUE #8058: [G2] Create Cipher light
See tentative definition in #8057 - this is similar to the existing MD light (introduced in #7120) and ECP light. (Don't worry about the definition being tentative: it will be refined if needed when we add more users in future tasks.)

This means that the outer guard of `cipher.c` will be changed from `CIPHER_C` to `CIPHER_LIGHT`, and then the parts of the file that are not part of Cipher light will be guarded by `CIPHER_C`. The macro `MBEDTLS_CIPHER_LIGHT` is private and does not appear in `mbedtls_config.h`.

Dependencies in `test_suite_cipher*` will need adjusting.

Rename the existing `all.sh` component `test_full_no_cipher` to `test_full_no_cipher_at_all` and create a new component `test_full_cipher_light_only` that will be initially very similar. For now, enable Cipher light by adding `-DMBEDTLS_CIPHER_LIGHT`.

Add a test `not grep mbedtls_cipher library/cipher.o` to the `no_cipher_at_all` component and a test `not grep mbedtls_cipher_auth library/cipher.o` to the `cipher_light_only` component.

### PR DESCRIPTION
**Pull request by valeriosetti**
This PR tries to introduce `CIPHER_LIGHT`, a "reduced" version of `CIPHER_C`, following the requirements of #8058 (i.e. the associated task) and #8057.

Resolves #8058

**Depends on:**
- #8057
- #8119 

## PR checklist

- [ ] **changelog** since we add the possibility for the end user to have a reduced version of `CIPHER_C` I think this is required, right?
- [ ] **backport** not required because it's an enhancement
- [ ] **tests** provided: a new test component was added

### CODE REVIEW

**Comment by valeriosetti** [comment]
Just rebased on `development` in order to benefit from a recent change to `config_test_driver.h` in which some legacy includes were removed

**Review by gabor-mezei-arm — CHANGES_REQUESTED** [review]

**Review by gabor-mezei-arm — CHANGES_REQUESTED** [review]
Please remove the check for `MBEDTLS_CIPHER_C` in every newly added occurrence where used along with a define which has already a check in `check_config.h`. Including `MBEDTLS_NIST_KW_C` and `MBEDTLS_CIPHER_AUTH_CRYPT`.

**Comment by valeriosetti** [comment]
> Please remove the check for `MBEDTLS_CIPHER_C` in every newly added occurrence where used along with a define which has already a check in `check_config.h`. Including `MBEDTLS_NIST_KW_C` and `MBEDTLS_CIPHER_AUTH_CRYPT`.

Sorry, I thought I already did that in my previous last commit, but apparently I missed a lot of occurrences there. It should be fixed now by https://github.com/Mbed-TLS/mbedtls/pull/8142/commits/1fb548725b61748d4b99fd38d13e9eeb38d6db85

**Comment by mpg** [comment]
Please put this on hold until #8057 is finalized. The definition is still likely to change.

**Comment by mpg** [comment]
@valeriosetti I think #8057 is converging (not a 100% sure yet, but changes if any should be minor at this point), so if you have bandwidth, feel free to update this to the new definition. (Or, if there are other tasks you can pick up in the meantime, prioritizing them until 8057 is fully approved also makes sense. Your choice.)

**Comment by valeriosetti** [comment]
> @valeriosetti I think #8057 is converging (not a 100% sure yet, but changes if any should be minor at this point), so if you have bandwidth, feel free to update this to the new definition. (Or, if there are other tasks you can pick up in the meantime, prioritizing them until 8057 is fully approved also makes sense. Your choice.)

Since I already have a PR for most of the available issues on the ciphers/AEAD EPIC and the remaining one depends on this PR, I think I will try to adapt this PR to the new requirements. For sure it will take me a while to read #8057 and #8337 and correctly implement it.

**Comment by valeriosetti** [comment]
Since requirements in #8058 were refined a lot after this PR was created, I agreed with @mpg to close this PR and open a new one

**Pull request closed without merging**
