### PR TITLE
[3.6 backport] Improve test key generation in test_suite_pk

### PR DESCRIPTION
**Pull request by valeriosetti**
## Description

This is the backport of #8986 for `mbedtls-3.6` LTS branch.

## PR checklist

- [x] **changelog** not required as in #8986
- [x] **3.6 backport** not required, this is the backport to 3.6
- [x] **2.28 backport** not required in general
- [x] **tests** provided as in #8986

### CODE REVIEW

**Comment by valeriosetti** [comment]
Since #8986 already got some feedback and the CI is almost happy, I started this backport by cherry-picking all the commits from #8986 to the `mbedtls-3.6` branch.

**Review by gilles-peskine-arm — COMMENTED** [review]
LGTM except that it's missing the latest update to #8986.

**Review by gilles-peskine-arm — APPROVED** [review]
LGTM

**Review by mpg — APPROVED** [review]
Straightforward backport.

**Pull request merged**
