### PR TITLE
[Backport 2.28] Add tests for mbedtls_ecp_set_zero

### PR DESCRIPTION
**Pull request by wernerlewis**
## Description
Trivial backport of #6181.
Tests function with various ECP point conditions, covering freshly
initialized, zeroed, non-zero, and freed points.

## Status
**READY**

### CODE REVIEW

**Comment by tom-cosgrove-arm** [comment]
Should the CI have failed on `all_u16-test_ref_configs`?

**Comment by gilles-peskine-arm** [comment]
@tom-cosgrove-arm Why? What configuration looks problematic?

**Comment by wernerlewis** [comment]
> Should the CI have failed on `all_u16-test_ref_configs`?

I'm not sure why it failed, the logs didn't indicate anything related to this change. I've restarted CI to see if it is a persistent error.

**Review by daverodgman — APPROVED** [review]

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM. Faithful backport

**Pull request merged**
