### PR TITLE
Rename modulus input argument from m to N

### PR DESCRIPTION
**Pull request by Mihir-Raj-Singh**
#### Files : 

bignum_mod.c
 bignum_mod.h
 bignum_mod_raw.c
 bignum_mod_raw.h
 test_suite_bignum_mod.function

## Description

Rename modulus input argument from m to N in above mentioned files.

## Gatekeeper checklist

- [x] **changelog**  not required
- [x] **backport** not required
- [x]  Run Ctest ( All test passed successfully)
- [x]  Run check_files.py (File system are correct)
- [x]  Signed the commit

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

### CODE REVIEW

**Comment by minosgalanakis** [comment]
Hi and thank you for your contribution.

Having a look at the CI, There are occurences that the `m` was missed, so the tests are failing. Would you try to refactor the PR as follows:
* Split one big commit into a series of small commits, each modifying one function, and its header/documentation.
* Remove the modifications in the tests included in the ` test_suite_bignum_mod.function` for now. This can be implemented on a separate PR but it not required for this task to be complete.
* White a more sensical title and or description for each commit. 

With bignum commits can be styled as:

~~~~~~~
bignum_mod: Renamed `m` -> N in mbedtls_mpi_mod_residue_setup()

Signed of: ..
~~~~~~~

or

~~~~~~~
bignum_mod: Renamed `m` -> N in mbedtls_mpi_mod_residue_setup()

This patch changes .....
..and does ....
... (Add a more verbose description)

Signed of: ..
~~~~~~~

**Comment by Mihir-Raj-Singh** [comment]
Sure , do I need to close this pull request to do that ? 
Or I can just start working  and update my  branch ?

**Comment by tom-cosgrove-arm** [comment]
In this case, the easiest thing will be to rebase this branch, because the DCO signoff check has failed because the value in `Signed-off-by:` does not exactly match that in `Author:`.  The easiest way to do the signoff is with `-s` on the `git commit` line.

**Comment by Mihir-Raj-Singh** [comment]
I have one more doubt that :
In `bignum_mod.h` there's a function called `mbedtls_mpi_mod_modulus_init()`  and just below it the code are 

```
/** Setup a modulus structure.
 *
 * \param[out] m    The address of the modulus structure to populate.
 * \param[in] p     The address of the limb array storing the value of \p m.
 *                  The memory pointed to by \p p will be used by \p m and must
 *                  not be modified in any way until after
 *                  mbedtls_mpi_mod_modulus_free() is called.
 * \param p_limbs   The number of limbs of \p p.
 * \param int_rep   The internal representation to be used for residues
 *                  associated with \p m (see #mbedtls_mpi_mod_rep_selector).
 *
 * \return      \c 0 if successful.
 * \return      #MBEDTLS_ERR_MPI_BAD_INPUT_DATA if \p int_rep is invalid.
 */
```

- My question is is this all comment ?


-  Do I also need to rename `m` to `N` in this too ? 
> \param[out] m 
> \p m.

**Comment by minosgalanakis** [comment]
Yes that is the documentation for the said method using [doxygen ](https://www.doxygen.nl/) syntax. Since it refers to the parameter's of the method and you have changed the method it describes

~~~~~~
void mbedtls_mpi_mod_modulus_init( mbedtls_mpi_mod_modulus *N );
~~~~~~~

Then the parameter `/p m` should be changed to `/p N`

**Comment by Mihir-Raj-Singh** [comment]
Hey there !
I have updated the files as suggested , please review it and let me know If something needs my attention.

**Comment by minosgalanakis** [comment]
The cross sign means that this commit failed the CI, but it appears that there may have bene a CI maintainance issue at the time so it may not be an actual positive.

Overall the commit is in good shape and passes the CI. Unfortunately it needs to be rebased onto development, since yesterday we had the code style change merged, as communicated in the mailing list. 

You may have to do a force push after the rebase for your branch to accept the changes. Let me know if you need help with this.

**Comment by Mihir-Raj-Singh** [comment]
Sure , I do understand.
 Will you please elaborate on what I have to do now ?

Do i have to rebase all these commits into one commit and force push this branch ?

**Comment by Mihir-Raj-Singh** [comment]
Hey @minosgalanakis , @tom-cosgrove-arm  are you people available?

I need some clarification on this.

**Comment by minosgalanakis** [comment]
There is no need to squash the commits on top of each other. What has changed is the base of your changes, because development branches organically move as more commits get merged. So you naturally need to rebase your commit on top of the latest changes.

The simplest way to do so, assuming that your remote is origin is

~~~~~~
git fetch origin
git pull --rebase
~~~~~~

Please be mindfull that since the new code style was merged your commits will also need to comply to the new style. You can check that with 

~~~~~~~
python3 scripts/code_style.py
~~~~~~~~

If there are incompatibility issues, you can fix them using the same script and add them to the last commit in the pr

~~~~~~~
python3 scripts/code_style.py -f
~~~~~~~

**Comment by Mihir-Raj-Singh** [comment]
> The simplest way to do so, assuming that your remote is origin is
> 
> ```
> git fetch origin
> git pull --rebase
> ```

I did follow the steps , but  as I ran `python3 scripts/code_style.py` I am getting an error :

> `python3 scripts/code_style.py`
```
Traceback (most recent call last):
  File "/home/scorpion/Desktop/MBEDTLS/mbedtls/scripts/code_style.py", line 197, in <module>
    sys.exit(main())
  File "/home/scorpion/Desktop/MBEDTLS/mbedtls/scripts/code_style.py", line 172, in main
    uncrustify_version = get_uncrustify_version().strip()
  File "/home/scorpion/Desktop/MBEDTLS/mbedtls/scripts/code_style.py", line 93, in get_uncrustify_version
    result = subprocess.run([UNCRUSTIFY_EXE, "--version"], \
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'uncrustify'
```
Any help regarding this will be appreciated.

**Comment by tom-cosgrove-arm** [comment]
You need to [install version 0.75.1 of `uncrustify`](https://github.com/Mbed-TLS/mbedtls-docs/blob/main/kb/how-to/uncrustify.md)

**Comment by Mihir-Raj-Singh** [comment]
> You need to [install version 0.75.1 of `uncrustify`](https://github.com/Mbed-TLS/mbedtls-docs/blob/main/kb/how-to/uncrustify.md)

- How may I know that which is the correct executable files in build directory ?
- And where do I have to copy it ? 
> where do `Path` refers to ?

**Comment by minosgalanakis** [comment]
I had a look and it may be a false positive. For something to be merged it needs to pass the CI, so I will try to relaunch that job.

**Comment by Mihir-Raj-Singh** [comment]
> I had a look and it may be a false positive. For something to be merged it needs to pass the CI, so I will try to relaunch that job. 

Can I be helpful in any way for now ? Or should I just wait ?

**Review by minosgalanakis — APPROVED** [review]
LGTM

**Comment by minosgalanakis** [comment]
> > I had a look and it may be a false positive. For something to be merged it needs to pass the CI, so I will try to relaunch that job.
> 
> Can I be helpful in any way for now ? Or should I just wait ?

Thanks, but there is nothing to do at the current state. 

I have approved the changes, but it needs a second reviewer. If they also have no comments for rework, and the PR gathers two approvals, it can be merged. 

If there are comments, that need to be addressed you will have to do so.

**Comment by Mihir-Raj-Singh** [comment]
> If there are comments, that need to be addressed you will have to do so.

- Thankyou , Let me know If anything needs my attention.

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Comment by minosgalanakis** [comment]
The CI is incorrectly reporting the status. It has successfully completed all jobs. --> [link](https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbed-tls-pr-merge/detail/PR-6903-merge/5/pipeline)

Please merge when possible.

**Pull request merged**
