### PR TITLE
Replace references to Mbed Crypto (rebase)

### PR DESCRIPTION
**Pull request by daverodgman**
## Description

Rebased version of #4990.

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** no (doc only)
- [x] **backport** #7597 
- [x] **tests** no (doc only)

### CODE REVIEW

**Comment by daverodgman** [comment]
@AndrzejKurek since you reviewed previously, please could you TAL? @tom-daubney-arm - please could you also review, thanks

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Comment by tom-cosgrove-arm** [comment]
@daverodgman If you think one review is enough, you can add `single-reviewer` and `approved`, and remove `needs-review`. If you think it needs two reviews, then please add `needs-reviewer`

**Review by gilles-peskine-arm — APPROVED** [review]
LGTM (mostly, I checked that we do preserve the historical names in the storage specification)

**Comment by gilles-peskine-arm** [comment]
This needs a 2.28 backport: Mbed TLS 2.28 is not a version of Mbed Crypto.

**Comment by gilles-peskine-arm** [comment]
@tom-cosgrove-arm single-reviewer is up to the reviewer. The author should stay out of this decision due to an obvious conflict of interest. (I admit I have single-reviewered a PR of mine before, because the reviewers just weren't coming out and oking it even if they did approve. But it shouldn't be that way.)

**Comment by daverodgman** [comment]
> @tom-cosgrove-arm single-reviewer is up to the reviewer. The author should stay out of this decision due to an obvious conflict of interest. (I admit I have single-reviewered a PR of mine before, because the reviewers just weren't coming out and oking it even if they did approve. But it shouldn't be that way.)

It's fine for the author to mark a PR single-reviewer - it's more of a hint coming from the author. The reviewer can always remove that label if they feel a second reviewer is warranted, and the gatekeeper can do the same.

**Pull request merged**
