### PR TITLE
Follow up to 8075

### PR DESCRIPTION
**Pull request by mpg**
## Description

This is the much expected follow-up to #8075

## PR checklist

- [x] **changelog** not required
- [x] **backport** not required
- [x] **tests** not required - we usually don't have automated tests ensuring the `check_config.h` gives an `#error` when expected.

### CODE REVIEW

**Comment by mpg** [comment]
The first CI failures are coming in: `component_build_psa_accel_key_type_ecc_key_pair` and `component_build_psa_accel_key_type_ecc_public_key` are quite obviously failing due to the new test.

I've been meaning to look into all these old `component_build_psa_accel` things for a while, but never got around to it so now it's coming back at me.

I'm inclined to say that acceleration for just `KEY_TYPE_ECC_PUBLIC_KEY` or just `KEY_TYPE_ECC_KEY_PAIR` was never really supported, as these are build-only components, so we could just remove them and that wouldn't be a regression.

Wdyt?

**Comment by mpg** [comment]
FWIW, I've tried locally a modified version of `test_psa_crypto_config_accel_ecc_some_key_types` that accelerates only `KEY_TYPE_ECC_PUBLIC_KEY` or only `KEY_TYPE_ECC_KEY_PAIR_BASIC` and `test_suite_psa` passed (I didn't try the whole `make test` as it's just too slow on my machine in this build). So, there's a chance that we actually support more than we currently advertise. However:
- this was not a complete run so perhaps other tests would fail;
- I think in most reasonable use cases a driver is going to support either (at least) those 4 key type components, or none;
- anyway it's acceptable to have an initial restriction and lift it later if people tell us about concrete use cases that require more flexibility;
- I stand by my statement that this was never really supported so this is not a regression;
- anyway the whole driver thing is not marked as stable yet;
- that close to release we should be very conservative.

So, my opinion is still we keep the restriction as it it and just remove the two components `component_build_psa_accel_key_type_ecc_key_pair` and `component_build_psa_accel_key_type_ecc_public_key`.

**Comment by mpg** [comment]
Aw, `test_psa_crypto_drivers` is failing as well due to the new check about partial key type accel. I'm looking into it.

**Comment by mpg** [comment]
Ok, that one looks easy, it should be a simple matter of updating `tests/configs/user-config-for-test.h`.

**Comment by mpg** [comment]
Both CIs have completed their run, and the only failing components are those mentioned above:
- `test_psa_crypto_drivers` for which I have a fix that works locally;
- `build_psa_accel_key_type_ecc_key_pair` and `build_psa_accel_key_type_ecc_public_key` which I'm suggesting we remove.

**Comment by mpg** [comment]
Note: I don't think we really need the limitation on key types: if acceleration is partial, then `ECP_C` is going to be enabled, which includes support for all key type operations. This is very different to the case of curves, where each curve has its own parameters, and ECP functions will fail on curves whose parameters are not included in the build.

I'm still reluctant to lift the restriction without further testing. We could try adding variants of `test_psa_crypto_config_accel_ecc_some_key_types` and see if they work (once the check in `check_config.h` has been removed of course). I'm running out of time to do this, but if someone wants to raise a PR doing that and see what the CI thinks, that would be interesting to know.

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]
I've reviewed up to 59b2854e1ac2e6c71a3726b030ebcefc707715ba. Looks good so far.

After that I don't understand what's going on. I started looking at c0c9b23b23e1ee4052631c7e85ce80c4ae99fec5 which looked right. Then the next force-push removed "Add check for unsupported partial curves acceleration" and "Add check for unsupported partial key type acceleration", which looked fine, and made changes to `all.sh` that I don't understand and that are failing.

**Comment by mpg** [comment]
Aw, sorry, I messed up and what I pushed wasn't at all what I intended. It looks like part of local experiments I thought I was doing in another worktree - but apparently I was not in the directory I thought I was - mixed with changes intended for this PR.

**Review by gilles-peskine-arm — COMMENTED** [review]
LGTM for correctness — will now check for completeness

**Review by gilles-peskine-arm — APPROVED** [review]
I am satisfied that this addresses my reservations in https://github.com/Mbed-TLS/mbedtls/pull/8075#pullrequestreview-1646234741

**Pull request merged**
