### PR TITLE
Adapt to new PSA Crypto repo name

### PR DESCRIPTION
**Pull request by ronald-cron-arm**
## Description

Patterns I looked for:
grep -i "psa-crypto"
grep -i "psa.*crypto.*repo"
grep -i "psa.*crypto.*root"

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required, no change for users
- [x] **backport** not required, 3.x only code
- [x] **tests** not required, just some renaming

### CODE REVIEW

**Review by paul-elliott-arm — COMMENTED** [review]
Do we care about docs?

docs/use-psa-crypto.md and others still contain references to psa-crypto
(Can provide full list if required).

Otherwise everything looks good. Restarted CI, due to some intermittent issues.

**Comment by ronald-cron-arm** [comment]
> Do we care about docs?
yes

> docs/use-psa-crypto.md and others still contain references to psa-crypto (Can provide full list if required).
In this file, it seems "psa crypto" reference the PSA cryptography APIs, not the PSA crypto repository thus it seems to be fine to keep that as is.

**Review by paul-elliott-arm — APPROVED** [review]
In which case, LGTM

**Review by davidhorstmann-arm — APPROVED** [review]
LGTM, thanks!

**Comment by ronald-cron-arm** [comment]
The ABI-API-checking failure is a CI glitch. This is ready to go.

**Pull request merged**
