### PR TITLE
Record size limit support is released, so remove warning about only for testing

### PR DESCRIPTION
**Pull request by tom-cosgrove-arm**
## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [ ] **changelog** ~provided, or~ not required
- [ ] **backport** ~done, or~ not required - RSL only in `development`
- [ ] **tests** ~provided, or~ not required

### CODE REVIEW

**Comment by tom-cosgrove-arm** [comment]
Marked `do-not-merge` as this PR will hopefully come in via the release mergeback

**Review by tom-daubney-arm — APPROVED** [review]
LGTM.

**Review by ronald-cron-arm — APPROVED** [review]
LGTM

**Comment by tom-cosgrove-arm** [comment]
Merged into `development` via release - thanks for reviews

**Pull request closed without merging**
