### PR TITLE
Move test helpers to the framework

### PR DESCRIPTION
**Pull request by davidhorstmann-arm**
Move the contents of `tests/src` and `tests/include` (excluding `tests/include/alt-dummy`) to the framework and adjust references to these paths accordingly.

## PR checklist

Please remove the segment/s on either side of the | symbol as appropriate, and add any relevant link/s to the end of the line.
If the provided content is part of the present PR remove the # symbol.

- [x] **changelog** not required because: no user-facing change (internal file motion only)
- [x] **development PR** provided
- [x] **framework PR** provided Mbed-TLS/mbedtls-framework#37
- [ ] **3.6 PR** provided # | not required because: 
- [x] **2.28 PR** not required because: no framework in 2.28
- **tests**  not required because: no functional change or features, moving of files only

### CODE REVIEW

**Comment by ronald-cron-arm** [comment]
First quick look, this looks overall as expected. I will wait for the CI to be happier to review further though.

**Comment by davidhorstmann-arm** [comment]
I will also need to rebase and rework after #9394 I think

**Comment by mpg** [comment]
Is this PR still relevant or should it be closed, and then a new one opened once #9430 and #9547 are in?

**Comment by davidhorstmann-arm** [comment]
Superseded by #9756

**Pull request closed without merging**
