### PR TITLE
cmake: Define compile and link options target by target

### PR DESCRIPTION
**Pull request by ronald-cron-arm**
## Description
Progresses #9615.

To avoid having the compile and link options being defined twice in tf-psa-crypto when included in Mbed TLS, define the compile and link options not through the global CMAKE_C_FLAGS but target by target.
For reviewers, in the CMake build tree, the compilation flags for a target are located in a `flags.make` file. Linker flags are in `link.txt` files. More generally from web browsing this seems the preferred way to define compile and link options in CMake nowadays.

## PR checklist
- [x] **changelog** not required because: cmake build system 
- [x] **development PR** provided here
- [x] **framework PR** not required
- [x] **3.6 PR** not required because: 4.0 only work
- [x] **2.28 PR** not required because: 4.0 only work
- **tests**  not required because: only changing the way compile/link options are set

### CODE REVIEW

**Review by minosgalanakis — COMMENTED** [review]
Looks good. Using `PRIVATE` is an elegant way of implementing the requirements.

There is a minor coflict that needs to be resolved though.

**Comment by ronald-cron-arm** [comment]
I've rebased to resolve the conflicts due to the merge of #9706. I had to resolve the conflicts manually only for one commit: "Remove now unnecessary shared lib specific compile option". The diff of the commit before and now are the same thus this should be all good.

**Review by minosgalanakis — APPROVED** [review]
LGTM

**Comment by valeriosetti** [comment]
Sorry, I think that a PR of mine that was recently merged (#9703) caused the conflict on the main `CMakeLists.txt` file

**Review by valeriosetti — DISMISSED** [review]
The PR is OK for me. Please just fix the conflict and then I will do another quick check

**Comment by ronald-cron-arm** [comment]
> Sorry, I think that a PR of mine that was recently merged (#9703) caused the conflict on the main `CMakeLists.txt` file

Indeed, but no worries that's just the way it is.

**Comment by ronald-cron-arm** [comment]
> The PR is OK for me. Please just fix the conflict and then I will do another quick check

I've rebased. I manually fixed the conflict in commit "cmake: GNU GCC: Set base compile options target by target" due to the merge of 9703. I've removed the "message(STATUS ..." lines as due to the new way setting the compilation flags they were producing lots of noise during the CMake configuration.

**Review by minosgalanakis — APPROVED** [review]
LGTM

**Pull request merged**
