### PR TITLE
[Backport 2.28] Add default config tests for the A64, A32, Thumb 1 and Thumb 2 instruction sets

### PR DESCRIPTION
**Pull request by bensze01**
This PR is the 2.28 backport of #9389

### CODE REVIEW

**Comment by bensze01** [comment]
The extra load on the CI should be negligable, and this PR doesn't affect any pre-existing tests either, so the risk of regressions should also be negligable.

Since officially we will be supporting 2.28 for a few more months, I'd be more comfortable with having these matching tests in place, in case we need to make an emergency release for whatever reason.

**Comment by mpg** [comment]
Considering that large differences between 2.28 and the other branches in `all.sh` structure, I wouldn't have insisted on a backport, but I agree it's better to have it, so let's review it an get this all merged.

**Review by mpg — APPROVED** [review]
LGTM, thanks!

**Review by tom-cosgrove-arm — APPROVED** [review]
Happy with this as a backport

**Pull request merged**
