### PR TITLE
Conversion function between raw and DER ECDSA signatures (ASN1 functions in `psa_util`)

### LINKED ISSUE #7765: Conversion function between raw and DER ECDSA signatures
There are two widespread formats for ECDSA signatures: fixed-size, or DER. The X.509 and TLS ecosystem and the legacy mbedtls API use the DER format. Most cryptoprocessors including Cryptoki (PKCS#11) and PSA Crypto use the fixed size format.

Converting between the two formats is awkward. We should offer an API for it, at least to facilitate the life of code (including our own X.509/TLS code) that needs the X.509/TLS format and wants to use the PSA API.

Goals of this issue (which may be broken down into sub-issues):

* Design the ECDSA signature format conversion API.
* Implement and test it.
* Make sure that we're using the new functions inside the library rather than an ad hoc implementation. (Some of our code uses the ECDSA functions that expose (r,s) as bignums rather than formatting them as a byte string; this may be the right choice sometimes.)
* List it in the upcoming PSA transition guide.

### PR DESCRIPTION
**Pull request by valeriosetti**
## Description

This PR is an alternative implementation of #8681 in which ASN.1 required functions are re-implemented in `psa_util` in order to remove that dependency.

Commits up to https://github.com/Mbed-TLS/mbedtls/pull/8696/commits/4e53147b4ebcaf781a7bc25542741831d2ed8e38 belong to #8681 

Resolves #7765

## PR checklist

- [ ] **changelog** maybe required, but for now this is only a study
- [ ] **backport** not required
- [ ] **tests** provided - the same as in #8681

### CODE REVIEW

**Comment by valeriosetti** [comment]
Here's some footprint comparison analysis between this PR and its ancestor #8681. 

### baremetal_size configuration

For this test I just run `component_build_arm_none_eabi_gcc_m0plus` from `all.sh` in the 2 branches:

- #8681 = 222702 bytes
- This PR = 222862

In this scenario this PR is  +160 bytes compared to #8681. This is reasonable since `baremetal_size` configuration keeps `MBEDTLS_ASN1_[PARSE|WRITE]_C` so there is code duplication for the ASN1 parse/write functions that this PR re-implements.

### TF-M configuration

- #8681 = 36298 bytes
    - I build this with `./mtest -S MBEDTLS_ASN1_WRITE_C MBEDTLS_ASN1_PARSE_C`, adding ASN1 symbols to the command line, otherwise #8681 was skipping ECDSA conversion functions in `psa_util` so the comparison would have been not correct.
- this PR = 33972 bytes
    - This was built with `./mtest -S` and no additional parameter

In this case we get -2326 bytes compared to #8681 because in the latter we enable more code from `asn1write`/`asn1parse` than what it is strictly needed.

**Comment by mpg** [comment]
Beyond the code size impact, I'm not super happy about having source-level duplication. (The usual reasons: every time we change something in one place we need to think about the other place etc.)

I'm wondering if we should also define a subset of `ASN1_PARSE` and `ASN1_WRITE` (could be `ASN1_LIGHT` or `ASN1_LIGHT_{PARSE,WRITE}`) containing just the two functions we need here? Then this would be auto-enabled when needed.

Btw, I think those two functions only make sense when some form of ECDSA is available, so perhaps they should be guarded with `ECDSA_C || (PSA_CRYPTO_C && (ALG_ECDSA || ALG_DETERMINISTIC_ECDSA))`? (Perhaps define a helper macro to avoid having to repeat this condition.) (Not specific to this PR actually, worth considering for 8681 too.)

**Comment by valeriosetti** [comment]
> I'm wondering if we should also define a subset of `ASN1_PARSE` and `ASN1_WRITE` (could be `ASN1_LIGHT` or `ASN1_LIGHT_{PARSE,WRITE}`) containing just the two functions we need here? Then this would be auto-enabled when needed.

I can have a look at this, but I think it would be better to keep that in a new PR so we can compare 3 options:
1. #8681 
2. based on (1) plus re-implementation of ASN1 functions in `psa_util.c`
3. based on (1) plus adding guards in ASN1 code for `ASN1_LIGHT` (or similar name)

**Comment by valeriosetti** [comment]
Closing this one as agreed on https://github.com/Mbed-TLS/mbedtls/pull/8696#issuecomment-1888906194. This feature will be completed in #8703

**Pull request closed without merging**
