### PR TITLE
Fix IAR warning

### LINKED ISSUE #3835: IAR compiler warnings in bignum.c
### Description
- Type: Compiler warning
- Priority: Minor

Hey folks!

The IAR Compiler (IAR ANSI C/C++ Compiler V8.50.1.245/W32 for ARM) has some remarks in bignum.c.

1. Remark: the unary minus operator is applied to an unsigned expression

https://github.com/ARMmbed/mbedtls/blob/935b4f96f9fb9d47158c988a1acaf9e1fa042e67/library/bignum.c#L269
https://github.com/ARMmbed/mbedtls/blob/935b4f96f9fb9d47158c988a1acaf9e1fa042e67/library/bignum.c#L302

2. Remark: integer conversion resulted in a change of sign

https://github.com/ARMmbed/mbedtls/blob/935b4f96f9fb9d47158c988a1acaf9e1fa042e67/library/bignum.c#L1683-L1685
https://github.com/ARMmbed/mbedtls/blob/935b4f96f9fb9d47158c988a1acaf9e1fa042e67/library/bignum.c#L1824

One possibility would be to add additional type casts to the lines.

### PR DESCRIPTION
**Pull request by daverodgman**
Thanks to @gstrauss for providing the fix. This fixes #3835

- [x] **changelog** present
- [x] **backport** in #6889
- [x] **tests** not required

### CODE REVIEW

**Review by tom-daubney-arm — APPROVED** [review]
LGTM

**Review by tom-cosgrove-arm — DISMISSED** [review]
I don't like the redundant postfix `u`, but okay, this is harmless

**Comment by tom-cosgrove-arm** [comment]
@daverodgman Can you explain why a ChangeLog entry isn't required? `ChangeLog` already contains entries such as `Fix compilation warnings with IAR toolchain`

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Pull request merged**
