### PR TITLE
[G3] Disable cipher.c in the accel component

### LINKED ISSUE #8417: [G3] Disable cipher.c in the accel component
When all ciphers and AEAD (and CMAC) are accelerated, PSA should not need `CIPHER_C`. We made changes in that direction in #8119 but haven't really tested with drivers; this task is to do so.

Suggestion: using the pair of components created by #8303:
- disable `CIPHER_C` in the accel component (but not the reference component);
- add a check that `cipher.o` is indeed empty;
- fix any issue or disparity that may arise.

**Depends on:** #8119 and #8303

### PR DESCRIPTION
**Pull request by valeriosetti**
## Description

Resolves #8417

## PR checklist

- [x] **changelog** not required, since nothing changes from user point of view
- [x] **backport** not required
- [x] **tests** provided: the PR itself involves a change of a test

### CODE REVIEW

**Review by mpg — APPROVED** [review]
LGTM

**Review by lpy4105 — COMMENTED** [review]
LGTM, but there is a conflict with #8495.
After rebasing, I will give my approval.

**Review by lpy4105 — APPROVED** [review]
LGTM

**Review by mpg — APPROVED** [review]
LGTM

**Pull request merged**
