### PR TITLE
Replace MBEDTLS_MD_CAN_SHA256 with PSA_WANT_ALG_SHA_256

### PR DESCRIPTION
**Pull request by eleuzi01**
## Description

Issue #9112

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required, internal changes
- [x] **3.6 backport** not required, needed for 4.0
- [x] **2.28 backport** not required, needed for 4.0
- [x] **tests** not required

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

### CODE REVIEW

**Review by gabor-mezei-arm — DISMISSED** [review]
LGTM

**Review by gabor-mezei-arm — APPROVED** [review]
LGTM

**Review by tom-daubney-arm — CHANGES_REQUESTED** [review]
Looks almost good to me; couple of points:

We have a hit for `MBEDTLS_MD_CAN_SHA256` in:
```
framework/scripts/generate_pkcs7_tests.py
40:    mandatory_dep = "MBEDTLS_MD_CAN_SHA256"
```
I think it is probably worth changing it here. WDYT @gabor-mezei-arm?

Also in `docs/architecture/psa-migration/md-cipher-dispatch.md` we have the following example:
```
#if defined(MBEDTLS_MD_LIGHT)
#if defined(MBEDTLS_SHA256_C) || \
    (defined(MBEDTLS_PSA_CRYPTO_C) && PSA_WANT_ALG_SHA_256)
#define MBEDTLS_MD_CAN_SHA256
#endif
#endif
```
Is it worth rewriting this example for a different config option that hasn't been replaced?

**Comment by eleuzi01** [comment]
> Looks almost good to me; couple of points:
> 
> We have a hit for `MBEDTLS_MD_CAN_SHA256` in:
> 
> ```
> framework/scripts/generate_pkcs7_tests.py
> 40:    mandatory_dep = "MBEDTLS_MD_CAN_SHA256"
> ```
> 
> I think it is probably worth changing it here. WDYT @gabor-mezei-arm?
> 

Thanks for review, I pushed that to framework [#31
](https://github.com/Mbed-TLS/mbedtls-framework/pull/31)

**Comment by gilles-peskine-arm** [comment]
> Also in docs/architecture/psa-migration/md-cipher-dispatch.md we have the following example:

I think it'll be a lot easier to update this document as a whole once all the changes are done. Or possibly remove it altogether: 4.0 will no longer have subtleties around dispatch of md and cipher.

**Comment by tom-daubney-arm** [comment]
> > Also in docs/architecture/psa-migration/md-cipher-dispatch.md we have the following example:
> 
> I think it'll be a lot easier to update this document as a whole once all the changes are done. Or possibly remove it altogether: 4.0 will no longer have subtleties around dispatch of md and cipher.

Great - I agree, just wanted to check. Happy to approve as is.

**Comment by tom-daubney-arm** [comment]
> > Looks almost good to me; couple of points:
> > We have a hit for `MBEDTLS_MD_CAN_SHA256` in:
> > ```
> > framework/scripts/generate_pkcs7_tests.py
> > 40:    mandatory_dep = "MBEDTLS_MD_CAN_SHA256"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think it is probably worth changing it here. WDYT @gabor-mezei-arm?
> 
> Thanks for review, I pushed that to framework [#31 ](https://github.com/Mbed-TLS/mbedtls-framework/pull/31)

Ah cool, thanks, I didn't realise that was there. For the future, it helps to link to the other PRs in the PR description so that the reviewers can easily find them all.

**Comment by eleuzi01** [comment]
> > > Looks almost good to me; couple of points:
> > > We have a hit for `MBEDTLS_MD_CAN_SHA256` in:
> > > ```
> > > framework/scripts/generate_pkcs7_tests.py
> > > 40:    mandatory_dep = "MBEDTLS_MD_CAN_SHA256"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I think it is probably worth changing it here. WDYT @gabor-mezei-arm?
> > 
> > 
> > Thanks for review, I pushed that to framework [#31 ](https://github.com/Mbed-TLS/mbedtls-framework/pull/31)
> 
> Ah cool, thanks, I didn't realise that was there. For the future, it helps to link to the other PRs in the PR description so that the reviewers can easily find them all.

Sorry about that, it completely slipped my mind. Thanks!

**Comment by tom-daubney-arm** [comment]
> > > > Looks almost good to me; couple of points:
> > > > We have a hit for `MBEDTLS_MD_CAN_SHA256` in:
> > > > ```
> > > > framework/scripts/generate_pkcs7_tests.py
> > > > 40:    mandatory_dep = "MBEDTLS_MD_CAN_SHA256"
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > I think it is probably worth changing it here. WDYT @gabor-mezei-arm?
> > > 
> > > 
> > > Thanks for review, I pushed that to framework [#31 ](https://github.com/Mbed-TLS/mbedtls-framework/pull/31)
> > 
> > 
> > Ah cool, thanks, I didn't realise that was there. For the future, it helps to link to the other PRs in the PR description so that the reviewers can easily find them all.
> 
> Sorry about that, it completely slipped my mind. Thanks!

All good!

**Review by tom-daubney-arm — DISMISSED** [review]
LGTM - thanks!

**Comment by gabor-mezei-arm** [comment]
The legacy macro removal PRs most probably cause a merge conflict to each other so wait for the others to be merged.

**Review by gabor-mezei-arm — APPROVED** [review]
LGTM

**Review by tom-daubney-arm — APPROVED** [review]
LGTM - thanks!

**Review by gabor-mezei-arm — DISMISSED** [review]
LGTM

**Review by tom-daubney-arm — DISMISSED** [review]
The current rebase LGTM but this PR is already in need of another rebase what with all the other PRs that have gone in today.

@eleuzi01 if you could ping me as soon as you have rebased again and the CI passes that would be great, I will then re-re-review ASAP and hopefully we can get this in without further bitrotting.

**Review by tom-daubney-arm — APPROVED** [review]
LGTM - thanks!

**Review by gabor-mezei-arm — APPROVED** [review]
LGTM

**Comment by irwir** [comment]
Still using MBEDTLS_MD_CAN_SHA256 macro: `check_config.h` and `config_adjust_legacy_crypto.h`.
Should  these files to be updated too?

**Comment by tom-daubney-arm** [comment]
> Still using MBEDTLS_MD_CAN_SHA256 macro: `check_config.h` and `config_adjust_legacy_crypto.h`. Should these files be updated too?

Not for now, my understanding is these will be updated later however @gabor-mezei-arm knows more so could weigh in here.

**Comment by gabor-mezei-arm** [comment]
It will be removed in #9396.

**Pull request merged**
