### PR TITLE
Add threading implementation for Windows platform with SRW Locks

### PR DESCRIPTION
**Pull request by SergeySeroshtan**
## Description
Native Windows mutexes are not supported yet, so this PR is an attempt to fulfill this gap.
Implementation is based on the Windows [Slim Reader/Writer (SRW) Locks](https://docs.microsoft.com/en-us/windows/desktop/sync/slim-reader-writer--srw--locks).

## Status
**READY**

## Requires Backporting
- This PR is a new feature

NO  

## Migrations

NO

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated

## Steps to test or reproduce
 - Build the library on Windows with enabled config options `MBEDTLS_THREADING_C` and `MBEDTLS_THREADING_SRWLOCK`
- Run `programs\random\gen_random_ctr_drbg.exe`

### CODE REVIEW

**Comment by awakecoding** [comment]
Just as a reference, I have my own implementation for Windows using critical sections: https://github.com/Devolutions/mbedtls/commit/f0568d1aa559aff01e6f668632e3d21cbffacbbd

**Comment by SergeySeroshtan** [comment]
Hi, @RonEld 
> Do you think this PR can be handled without the new configuration option?

Yes, it's can be done by using predefined compiler macros that points to the Windows platform, like `__WIN32__, _MSC_VER `, etc.

**Comment by tom-daubney-arm** [comment]
Hi @SergeySeroshtan, we are currently reviewing our PR backlog and was wondering if this PR is something that you still want? Please let us know your thoughts, thanks

**Comment by fwh-dc** [comment]
Hi @tom-daubney-arm 

We are interested in a contribution that adds a MBedTLS default mutex implementation for windows.
What is required to merge this PR?

Regards,
Frederik

**Comment by gilles-peskine-arm** [comment]
@fwh-dc Windows is not a top priority target for us, and few of us have Windows knowledge, so this PR is not likely to go forward unless someone external takes over. Would you be ok with doing that?

Also, on the specific topic of mutexes, we're planning to extend the synchronization abstraction in Mbed TLS. Currently we only have mutexes, but we would like to add some notification mechanism (e.g. condition variables). Our plan is to define a subset of [C11 concurrency support](https://en.cppreference.com/w/c/thread) and make the Mbed TLS abstraction a trivial wrapper around it (e.g. `#define mbedtls_mtx_init mtx_init` and so on if you have C11 `threads.h`, and we'd also provide an abstraction on top of pthreads). Can SRW locks easily be extended to support something like C11 condition variables?

**Comment by SergeySeroshtan** [comment]
> SRW locks easily be extended to support something like C11 condition variables?

A brief overlook says yes - https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-sleepconditionvariablesrw

**Comment by fwh-dc** [comment]
Do you @SergeySeroshtan want to do it? 
Otherwise I'd like to spend some time on it!

Please let me know if I need to sign a contributor agreement or something.

**Comment by gilles-peskine-arm** [comment]
@fwh-dc You don't need to sign an agreement (we used to have one, but we stopped). You need to indicate your acceptance of [`dco.txt`](https://github.com/Mbed-TLS/mbedtls/blob/development/dco.txt) by including a signoff line (`git commit --signoff`, can be automated in various ways) in each commit message.

**Comment by tom-cosgrove-arm** [comment]
Closing this in favour of #7180

**Pull request closed without merging**
