### PR TITLE
Use latest installed OpenSSL 3 as OPENSSL_NEXT

### LINKED ISSUE #7350: Test against OpenSSL 3
Our current "OpenSSL Next" is OpenSSL 1.1.1. This will reach the end of its life in 6 months:

https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/

With this in mind, we should enable compatibility testing with OpenSSL 3.

### PR DESCRIPTION
**Pull request by ronald-cron-arm**
## Description
Fix #7350

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required, only changes related to tests
- [x] **3.6 backport** provided #9028
- [x] **2.28 backport** not required see [this comment](https://github.com/Mbed-TLS/mbedtls/pull/8998#issuecomment-2051611140)
- [x] **tests** not required, changes in testing

### CODE REVIEW

**Review by mpg — APPROVED** [review]
Looking good to me!

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Comment by mpg** [comment]
@ronald-cron-arm I think we want a 3.6 backport for this, however I'm not sure about 2.28: on one hand it doesn't really solve an actual problem there, on the other hand it might be nice to keep things aligned, but is that worth it? Wdyt?

**Comment by ronald-cron-arm** [comment]
> @ronald-cron-arm I think we want a 3.6 backport for this, however I'm not sure about 2.28: on one hand it doesn't really solve an actual problem there, on the other hand it might be nice to keep things aligned, but is that worth it? Wdyt?

Thanks for the reviews. I have created the 3.6 backport now: #9028. For 2.28, I would say we do not need to backport: no TLS 1.3, end of life coming soon ...

**Pull request merged**
