### PR TITLE
TLS 1.3: Enable and add tests

### LINKED ISSUE #5897: Enable TLS 1.2 tests compatible with TLS 1.3 in TLS 1.3 only configuration
### Suggested enhancement
Enable TLS 1.2 tests compatible with TLS 1.3 in TLS 1.3 only configuration, both SSL unit tests and ssl-opt.sh tests.

In SSL unit test suite, potentially the tests whose description starts with:
"Sending app data via TLS", "Record crypt", "Decrypt"
 
In ssl-opt.sh, potentially the tests whose description starts with:
"Authentication", "Non-blocking I/O", "Event-driven", "ALPN", "keyUsage", "Small/Large packet", "SSL async private".

### Justification
Improve testing of client and server TLS 1.3 implementation.

### PR DESCRIPTION
**Pull request by ronald-cron-arm**
## Description
Fix #5897 

## Status
Ready

## Requires Backporting
No, TLS 1.3 only

### CODE REVIEW

**Comment by yuhaoth** [comment]
There are a tls13 only test fail. I am not sure what's happen. beside that, this PR looks good to me

**Review by yuhaoth — DISMISSED** [review]
LGTM, But same item fail in OpenCI and the same item pass in Internal CI

**Comment by xkqian** [comment]
Seems it failed in this test case: 
"[2022-06-24T13:40:34.091Z] Authentication: client cert not trusted, server required ............... FAIL
[2022-06-24T13:40:34.091Z]   ! pattern '! mbedtls_ssl_handshake returned' MUST be present in the Client output
[2022-06-24T13:40:34.091Z]   ! outputs saved to o-XXX-256.log"

**Comment by ronald-cron-arm** [comment]
@yuhaoth @xkqian I believe I have addressed your comment. Please have another look.

**Review by xkqian — APPROVED** [review]
LGTM

**Review by yuhaoth — APPROVED** [review]
LGTM

**Pull request merged**
