### PR TITLE
[Bugfix] Fix null dereference in `mbedtls_pk_verify_ext()`

### PR DESCRIPTION
**Pull request by valeriosetti**
## Description

This fixes a NULL dereference crash in `mbedtls_pk_verify_ext()` that was possible when this function was called with an opaque RSA key. The issue was found while working at #8937.

## PR checklist

- [x] **changelog** provided
- [x] **backport** not required - no opaque RSA keys in 2.28
- [x] **tests** provided

### CODE REVIEW

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]
LGTM for the bug fix and non-regression test, but I think we need a changelog entry under Bugfix.

**Review by gilles-peskine-arm — DISMISSED** [review]
LGTM

**Review by mpg — CHANGES_REQUESTED** [review]
Looks pretty good. I wasn't sure if I should approve as-is or insist on fixing the discrepancy. Then I looked as #8937 and it says "verify_ext: not supported", so I think I'm going to insist we should test that.

Given the time frame, and the fact you've based 8937 on this one, I think we could close this one and keep only 8937 (addressing the comment from this one), in order to reduce the number of review and CI cycles.

**Comment by gilles-peskine-arm** [comment]
There are no opaque RSA keys in 2.28, so there's no bugfix to backport. We could backport the test code but it wouldn't be much use.

**Comment by mpg** [comment]
> There are no opaque RSA keys in 2.28, so there's no bugfix to backport. We could backport the test code but it wouldn't be much use.

Ah right, I only checked that there were opaque keys, but missed those were only ECC back then. Thanks!

**Review by mpg — APPROVED** [review]
LGTM, thanks for addressing my feedback!

**Review by gilles-peskine-arm — APPROVED** [review]
LGTM

**Pull request merged**
