### PR TITLE
Fix RSA ALT test guards

### LINKED ISSUE #3174: build failure if compiled without MBEDTLS_PK_RSA_ALT_SUPPORT
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

**OS**  
linux

**mbed TLS build:**  
Version: 4500e83fe41a0765bc06b47662b3ae00d0b1bd59
OS version: 5.6.0
Configuration: please attach config.h file where possible  
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  
Additional environment information:  

**Peer device TLS stack and version**  
n/a
Version:  

**Expected behavior**   
builds without errors

**Actual behavior**  
[ 74%] Linking C executable test_suite_x509write
/usr/lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/test_suite_x509write.dir/test_suite_x509write.c.o: in function `execute_tests':
test_suite_x509write.c:(.text+0x1756): warning: warning: your code uses stdio (7+k bloat).
/usr/lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /opt/diet/lib-x86_64/libc.a(vsnprintf.o): in function `vsnprintf':
vsnprintf.c:(.text.vsnprintf+0x4c): warning: warning: the printf functions add several kilobytes of bloat.
/usr/lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/test_suite_x509write.dir/test_suite_x509write.c.o: in function `test_x509_crt_check':
test_suite_x509write.c:(.text+0x976): undefined reference to `mbedtls_pk_setup_rsa_alt'
collect2: error: ld returned 1 exit status

The bloat warning message comes from my special libc. You can disregard it here.

**Steps to reproduce**  

----------------------------------------------------------------
## Enhancement\Feature Request

**Justification - why does the library need this feature?**  

**Suggested enhancement**  

-----------------------------------------------------------------

## Question

**Please first check for answers in the [Mbed TLS knowledge Base](https://tls.mbed.org/kb). If you can't find the answer you're looking for then please use the [Mbed TLS mailing list](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls)**

### PR DESCRIPTION
**Pull request by daverodgman**
## Description

Fixes #3174.

## Gatekeeper checklist

- [x] **changelog** provided
- [x] **backport** done #6951 
- [x] **tests** not required

### CODE REVIEW

**Comment by tom-cosgrove-arm** [comment]
Presumably there isn't anything in the CI to catch this combination of defines - should we add something to avoid a regression in future?

**Comment by daverodgman** [comment]
I've added a regression test (compile-only to avoid bloating CI time).

**Comment by tom-cosgrove-arm** [comment]
Compile-only is fine

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Pull request merged**
