### PR TITLE
Fix memcpy of null pointer found by Clang static analyzer

### PR DESCRIPTION
**Pull request by oppm**
## Description
Fixes a few issues found by clang static analyzer.

## Status
**READY**

## Requires Backporting
Yes

## Steps to test or reproduce
Build with `scan-build`.

### CODE REVIEW

**Comment by ronald-cron-arm** [comment]
Thanks for this. To be able to reproduce and have more information about clang static analyzer findings, could you elaborate on "Build with scan-build." ? Do you need a configuration file for this to specify what has to be scanned?

**Comment by oppm** [comment]
> Thanks for this. To be able to reproduce and have more information about clang static analyzer findings, could you elaborate on "Build with scan-build." ? Do you need a configuration file for this to specify what has to be scanned?

No, I didn't use a configuration file. All I did was run `scan-build make` instead of `make` to build. Then the errors are reported in html files. Actually, quite a few more bugs were found by `scan-build` but I reported only the ones with relevance for us.

**Comment by gilles-peskine-arm** [comment]
> Actually, quite a few more bugs were found by scan-build

Please keep in mind that `scan-build` reports _warnings_, not bugs. We've considered adding it to our CI, but we haven't done so because it turns up a lot of false positives.

**Comment by oppm** [comment]
> > Actually, quite a few more bugs were found by scan-build
> 
> Please keep in mind that `scan-build` reports _warnings_, not bugs. We've considered adding it to our CI, but we haven't done so because it turns up a lot of false positives.

Yes, I am aware of that. I reviewed the findings I reported and found them legitimate.

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]
Please edit the commit messages to report what is being fixed accurately. It's not a bug if a static analysis tool can't determine whether the memory is initialized in all cases. It is a bug if there is a case in which the memory is not initialized. The analysis I posted in my review should be in the commit message.

Please add a non-regression test for the case that is a genuine bug.

**Comment by gilles-peskine-arm** [comment]
The `memcpy(NULL, ...)` fix should be backported. The initializations should not be backported since they aren't bugs and they have a tiny but nonzero impact on performance and code size.

**Comment by daverodgman** [comment]
Low impact, moving to Q4 tech debt

**Comment by tom-cosgrove-arm** [comment]
Closing this as the genuine UB (`memcpy(NULL, _, 0)`) is fixed (slightly differently) by #5801, and the other two changes here are false positives for reading uninitialised memory

**Pull request closed without merging**
