### PR TITLE
Replace MBEDTLS_MD_CAN_SHA512 with its PSA_WANT counterpart

### LINKED ISSUE #9114: Replace `MBEDTLS_MD_CAN_SHA512`  with its `PSA_WANT` counterpartarts
Replace the macros other then in the `include` directory:
- `MBEDTLS_MD_CAN_SHA512` to `PSA_WANT_ALG_SHA_512`

Ensure that the test are run in the same way.

### PR DESCRIPTION
**Pull request by gabor-mezei-arm**
## Description

Replace the macros other then in the `include` directory:
- `MBEDTLS_MD_CAN_SHA512` to `PSA_WANT_ALG_SHA_512`

Resolve #9114 

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required, internal changes
- [x] **3.6 backport** not required, needed for 4.0
- [x] **2.28 backport** not required, needed for 4.0
- [x] **tests** not required

### CODE REVIEW

**Comment by ronald-cron-arm** [comment]
@gabor-mezei-arm We are in the final steps of merging #9185. You will be able to rebase to development then and this should resolve the "framework" conflict.

**Review by eleuzi01 — DISMISSED** [review]
LGTM

**Review by eleuzi01 — APPROVED** [review]
LGTM, thanks!

**Review by tom-daubney-arm — APPROVED** [review]
LGTM.

**Comment by gabor-mezei-arm** [comment]
The legacy macro removal PRs most probably cause a merge conflict to each other so wait for the others to be merged.

**Comment by ronald-cron-arm** [comment]
@gabor-mezei-arm it seems that if you rebase this PR we should be close to be able to merge it, right?

**Review by eleuzi01 — APPROVED** [review]

**Review by tom-daubney-arm — APPROVED** [review]
Rebase LGTM - thanks!

**Pull request merged**
