### PR TITLE
Refactor key derivation structure for the driver interface + Implement key derivation input getters v.2

### PR DESCRIPTION
**Pull request by mprse**
## Description
This is continuation of https://github.com/Mbed-TLS/mbedtls/pull/5867 which will be closed now.

Provided changes:
- Refactor the key derivation data structures (struct psa_key_derivation_s and subtructures) to separate the data used by phase 1 (driver-independent - collect inputs) and the data used by phase 2 (specific to the implementation). Call the structure used for phase 1 `psa_crypto_driver_key_derivation_inputs_t`.
- Refactor the existing code accordingly, with no expected behavior change.
- Implement key derivation input getters.
- Create unit tests for these functions.
- Use these functions instead of direct access in `psa_crypto_key_derivation_complete_inputs`.

Resolves:
https://github.com/Mbed-TLS/mbedtls/issues/5477
https://github.com/Mbed-TLS/mbedtls/issues/5478

## Status
**READY**

## Requires Backporting
 NO  

## Migrations
NO

### CODE REVIEW

**Comment by mprse** [comment]
Got the following failure:
`^^^^check_recursion: Check: recursion.pl: tests/scripts/recursion.pl library/*.c -> 2^^^^`

I understand that this function searches for recursion in code which is generally no allowed (with some exceptions), but I'm not aware of any recursion made in these changes. Also there is no information about the issue found just failed result.

**Comment by mprse** [comment]
Closing this one as I won't be able to continue.

**Comment by ruchi393** [comment]
Hi, I am planning to pick up the work on key derivation driver entry points based on the specification and issues created. I see that this PR was closed. @mprse and @gilles-peskine-arm can you advise if rebasing this patch to the new tf psa crypto and starting form there would be a good option.

**Comment by gilles-peskine-arm** [comment]
Thanks @ruchi393 ! I don't think rebasing this pull request would work well, ebcause a lot of things have changed.

As discussed in the PSA crypto driver interface working group, we're going to use Oberon's simpler interface for key derivation drivers rather than my original proposal. I don't think we have that in specification form yet — action on Oberon.

Our test structure has changed quite a bit, as well, although this pull request doesn't cover that part.

I think we need to re-plan the issues based on the new interface design, and taking care of splitting it down into manageable pieces. We also need to discuss scheduling and prioritization with Shebu.

**Comment by ruchi393** [comment]
Thanks @gilles-peskine-arm . I have raised this topic on discord channel to get more details on this new proposed interface. We are planning to work actively on this topic. If a specification is available, it would be great and we can contribute.

**Pull request closed without merging**
