### PR TITLE
Fixed spelling and typographical errors found by CodeSpell

### PR DESCRIPTION
**Pull request by warmsocks**
Signed-off-by: Shaun Case <warmsocks@gmail.com>

## Description
Fixed spelling and typographical errors found by CodeSpell. See https://github.com/codespell-project/codespell
Redo of unsuccessfully edited PR#5345

## Status
READY

## Requires Backporting
NO  

## Migrations
NO

### CODE REVIEW

**Review by minosgalanakis — COMMENTED** [review]
LGTM

My only (non blocking) concern is the modifications on the Changelog given that it modifie's history, even for a good reason.

**Review by trackpadpro — APPROVED** [review]
Good job! I was just about to fix the memebrs problem myself.

**Comment by gilles-peskine-arm** [comment]
This needs a backport to `mbedtls-2.28`.

**Comment by AndrzejKurek** [comment]
Hello @warmsocks and thanks for your contribution!
This PR looks good, but I would also advocate against modifying the changelog.
There's also, unfortunately, a conflict to be fixed.
Please let me know if you have some spare time to fix this PR, and if not, if you are ok with someone else taking over, introducing the necessary fixes and a backport.

**Pull request closed without merging**
