### PR TITLE
[Backport 3.6] Improve generate_test_keys.py

### PR DESCRIPTION
**Pull request by valeriosetti**
## Description

This is the backport of #9017

## PR checklist

- [x] **changelog** not required
- [x] **3.6 backport**  this is it
- [x] **2.28 backport** not required
- [x] **tests**  not required

### CODE REVIEW

**Comment by valeriosetti** [comment]
Note to reviewers: all the commits from #9010 has simply been cherry-picked here.

**Review by gilles-peskine-arm — APPROVED** [review]
LGTM as a backport of #9017.

**Review by gilles-peskine-arm — APPROVED** [review]
LGTM

**Comment by valeriosetti** [comment]
Force pushed to get all the recent changes in #9010. Once again all the commits were just cherry-picked.

**Review by mpg — DISMISSED** [review]
LGTM, thanks!

**Review by gilles-peskine-arm — APPROVED** [review]
LGTM

**Review by mpg — APPROVED** [review]
LGTM

**Pull request merged**
