### PR TITLE
Extend test framework for Record Size Limit Extension

### LINKED ISSUE #7006: Extend test framework for Record Size Limit Extension
### Suggested enhancement

Add a new test precondition option to ssl-opt.sh that only makes a test run if the available GnuTLS version supports Record Size Limit Extension. (Support has been added in version 3.6.8 according to the GnuTLS [website](https://www.gnutls.org/manual/gnutls.html))

OpenSSL is out of scope as they don't seem to support this extension yet (they have an open [issue](https://github.com/openssl/openssl/issues/8187) and a [PR](https://github.com/openssl/openssl/pull/18248) for it).

This should be done in a way consistent how we already do similar conditions. For example here is how TLS 1.3 support is detected in GnuTLS:
https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.3.0/tests/ssl-opt.sh#L604-L621

And this is how it is used to filter tests:
https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.3.0/tests/ssl-opt.sh#L11204

### Justification

Mbed TLS needs this because we are about to add Record Size Limit Extension and we need testing available as early as possible.

### Definition of Done

- [ ] Record Size Limit Extension support detection is added to ssl-opt.sh
- [ ] A new test case is added to ssl-opt.sh that passes but only runs if the available GnuTLS  version has Record Size limit extension (the sole purpose of this test case is to confirm that the new filter works)
- [ ] This new test runs in Travis CI (GnuTLS recent enough) and is skipped in Open CI (GnuTLS version too old)

### PR DESCRIPTION
**Pull request by KloolK**
Fixes #7006

### CODE REVIEW

**Comment by KloolK** [comment]
@yanesca Could you trigger a rebuild on Travis CI please? I don't seem to have the permissions for that and would like to avoid pushing again because that would also re-run all other CIs

**Comment by yanesca** [comment]
(Also, don't worry about the internal CI failure, it is not related to this PR.)

**Comment by KloolK** [comment]
Results from the newly added tests on Travis (where the tests are expected to be skipped):
https://app.travis-ci.com/github/Mbed-TLS/mbedtls/jobs/595326924#L1452-L1453

https://app.travis-ci.com/github/Mbed-TLS/mbedtls/jobs/595326923#L4242-L4243
https://app.travis-ci.com/github/Mbed-TLS/mbedtls/jobs/595326923#L8084-L8085
https://app.travis-ci.com/github/Mbed-TLS/mbedtls/jobs/595326923#L15551-L15552
https://app.travis-ci.com/github/Mbed-TLS/mbedtls/jobs/595326923#L19393-L19394

One result from Open CI (where the tests are expected to pass):
https://ci.staging.trustedfirmware.org/blue/rest/organizations/jenkins/pipelines/mbed-tls-pr-merge/branches/PR-7048-merge/runs/4/nodes/464/steps/5740/log/?start=0 :
```
[2023-02-07T11:13:49.811Z] Record Size Limit: Test gnutls record size limit feature ............... PASS
[2023-02-07T11:13:50.388Z] Record Size Limit: TLS 1.3: Test gnutls record size limit feature ...... PASS
```

**Review by yanesca — APPROVED** [review]
LGTM.

**Review by davidhorstmann-arm — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
