### PR TITLE
Fix typo in comments.

### PR DESCRIPTION
**Pull request by adamwolf**
## Description
Fixes a typo in comments.

## Status
**READY**

## Additional comments
When I click through on https://developer.mbed.org/contributor_agreement/, there isn't an agreement form.

### CODE REVIEW

**Comment by adamwolf** [comment]
Is there anything I can do to move this along, or is this waiting on other folks?

Thanks!

**Comment by k-stachowiak** [comment]
@adamwolf The changes look good. However, this kind of a change also require backports to the 2.7 and 2.16 branches. Would you be willing to raise additional 2 PRs targeting those branches?

**Comment by RonEld** [comment]
@adamwolf The reason you can't find the form is because Mbed OS doesn't need a CLA anymore.
So did Mbed TLS, for the development branch.
However, as mentioned by @k-stachowiak , the LTS branches require a signed CLA form.
You can find the [agreement to sign here](https://www.mbed.com/en/about-mbed/contributor-license-agreements/), which can be signed and returned to us.

Thanks for your understanding and again, thanks for the contribution!

**Comment by adamwolf** [comment]
@k-stachowiak I can sign the CLA and backport to 2.7 and 2.16.  Are there other branches I should backport to?

**Comment by k-stachowiak** [comment]
Last time I was involved, these were the "long term support" branches, so there should be no need to port to others. However, I'm not as close to the development as I used to be, so it would be best if somebody from the core team could confirm that, just in case.

**Comment by gilles-peskine-arm** [comment]
Thanks @adamwolf. I confirm that the long-term support branches are `mbedtls-2.7` and `mbedtls-2.16`. We intend to maintain LTS branches for at least 3 years so 2.7 will be an LTS branch until at least January 2021.

**Comment by mpg** [comment]
Hi @adamwolf ! There's been an update to how we manage licensing for contributions, we no longer require a CLA, but instead ask that contributors add a signed-off-by tag in the commit message, see https://github.com/ARMmbed/mbedtls/issues/3054 and https://github.com/ARMmbed/mbedtls/blob/development/CONTRIBUTING.md#making-a-contribution

Could you update this PR and create backport PRs to the mbedtls-2.16 and mbedtls-2.7 branches (which I confirm are the only branches that need backporting to).

**Comment by adamwolf** [comment]
Yes, I will do this.

**Comment by tom-cosgrove-arm** [comment]
This needs work (minor rebasing and sign-off adding); I'm closing this and opening #5719 with the updates

**Pull request closed without merging**
