### PR TITLE
Backport 2.28: Record the outcome of each test case in compat.sh

### PR DESCRIPTION
**Pull request by tgonzalezorlandoarm**
## Description

Backport of PR #7136 

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required
- [x] **backport** Backport of https://github.com/Mbed-TLS/mbedtls/pull/7136
- [x] **tests** not required

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

### CODE REVIEW

**Comment by tgonzalezorlandoarm** [comment]
@yanrayw This is the requested backport. In 2.28 mbedtls_config.h does not exist. I hope I dealt with this correctly, please let me know otherwise.

**Comment by lpy4105** [comment]
LGTM, thanks!

**Review by tom-daubney-arm — APPROVED** [review]
Faithful backport, LGTM.

**Comment by tom-daubney-arm** [comment]
@lpy4105 It looks like you have just left a comment rather than submitting it as a review officially. I am not sure if @yanrayw is technically allowed to review given he authored the original PR, so could you please officially submit as a review, and then we can mark it approved.

I am taking the CI as green here. It looks like the internal CI is being a bit slow but the equivalent components on OpenCI have passed, so I think we're all good.

**Pull request merged**
