### PR TITLE
Update TF-M config

### PR DESCRIPTION
**Pull request by daverodgman**
## Description

This brings our copy of the TF-M config closer to the upstream version by removing PK, as per https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/tree/lib/ext/mbedcrypto/mbedcrypto_config/tfm_mbedcrypto_config_profile_medium.h?id=8a5469cb2469cbddc2977003aa4b6e480503a374

Also, set `MBEDTLS_MD_C`, because this is required by `MBEDTLS_HKDF_C` (which they do set). (Leaving it unset generally works thanks to `config_adjust_legacy_from_psa.h`, but if `PSA_WANT_ALG_DETERMINISTIC_ECDSA` is unset then it doesn't get set automatically and therefore breaks).

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required
- [x] **backport** not required
- [x] **tests** not required

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

### CODE REVIEW

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Comment by tom-cosgrove-arm** [comment]
Does this interact with #8164?

**Review by davidhorstmann-arm — APPROVED** [review]
Looks straightforward enough

**Comment by daverodgman** [comment]
> Does this interact with #8164?

That seems to undo this - it will need an update.

**Pull request merged**
