### PR TITLE
Backport 2.28: "CSR parsing with critical fields fails" #8377

### PR DESCRIPTION
**Pull request by mschulz-at-hilscher**
## Description

Backporting of the test cases introduced in https://github.com/Mbed-TLS/mbedtls/issues/8377

## PR checklist

- [X] **changelog** not required
- [X] **backport** this is the backport
- [X] **tests** provided

### CODE REVIEW

**Comment by mschulz-at-hilscher** [comment]
The tests in this PR currently fail, but this is expected as mbedtls 2.28 currently does not care about whether extensions in a parsed CSR are critical or not.

```
X509 CSR ASN.1 (Unsupported critical extension, critical=true) .... FAILED
  my_ret == ref_ret
  at line 1094, suites/test_suite_x509parse.function
  lhs = 0x0000000000000000 = 0
  rhs = 0xffffffffffffda9e = -9570
X509 CSR ASN.1 (Unsupported non-critical extension, critical=false  PASS
X509 CSR ASN.1 (Unsupported non-critical extension, critical undef  PASS
```

We need to decide, how to handle this behavior. Either accept, that mbedtls 2.28 generally does not check those extensions and we have to change the test cases or add checking of extensions and thereby breaking the current behavior of the mbedtls_x509_csr_parse_der function.

**Comment by davidhorstmann-arm** [comment]
@mschulz-at-hilscher Since we know that silently ignoring the unsupported extensions is safe, we should change the testcases to pass rather than changing the behaviour.

**Comment by mschulz-at-hilscher** [comment]
Tests pass now:
```
X509 CSR ASN.1 (Unsupported critical extension, critical=true, ign  PASS
X509 CSR ASN.1 (Unsupported non-critical extension, critical=false  PASS
X509 CSR ASN.1 (Unsupported non-critical extension, critical undef  PASS
```

Nevertheless, I added a comment to the first test case as it behaves differently compared to the one we have on the development branch.
`X509 CSR ASN.1 (Unsupported critical extension, critical=true, ignore for backwards compatibility)`

**Review by davidhorstmann-arm — APPROVED** [review]
LGTM, thanks!

**Review by paul-elliott-arm — APPROVED** [review]
LGTM

**Pull request merged**
