### PR TITLE
CMake: Only use Apple-specific ranlib flags with Apple-provided toolchains

### PR DESCRIPTION
**Pull request by merryhime**
## Description

Matching on operating system breaks builds with alternative toolchains on macOS. Instead of matching on Darwin, match on AppleClang.

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

### CODE REVIEW

**Review by paul-elliott-arm — APPROVED** [review]
LGTM

**Review by davidhorstmann-arm — APPROVED** [review]
LGTM by inspection

**Review by davidhorstmann-arm — CHANGES_REQUESTED** [review]
Main change looks fine.

Since this is a fix, I think it needs a backport to `mbedtls-2.28` and a ChangeLog entry unless @paul-elliott-arm disagrees?

**Comment by paul-elliott-arm** [comment]
@merryhime - I presume you no longer wanted to work on this. Do you mind if we take it over?

**Comment by merryhime** [comment]
> @merryhime - I presume you no longer wanted to work on this. Do you mind if we take it over?

Go head.

**Pull request closed without merging**
