### PR TITLE
Backport 2.28: Verify numerical ip SubjectAlternativeName properly

### PR DESCRIPTION
**Pull request by scareything**
Trivial backport of #2906

### CODE REVIEW

**Comment by paul-elliott-arm** [comment]
Hi @scareything - given this is a new feature, I am not sure this would be applicable for this branch. Do I presume you are using a fixed version at your end?

**Comment by scareything** [comment]
Hi @paul-elliott-arm we are currently based on `development`, but would prefer to get this feature from a released version as soon as one is available. Do you have any rough ideas on when 3.x may be released?

**Comment by gilles-peskine-arm** [comment]
Hi @scareything,

We would like to release Mbed TLS 3.0 at the end of June. It's a tight deadline so only have limited bandwidth to review large patches for which we hadn't already agreed on a schedule. Furthermore, to avoid difficult reconciliations between the 2.x branch and the 3.0 branch, we've separated the code into areas where all new features should go into both 2.x and 3.0 (PSA crypto) and areas where all new features should go into 3.0 only (classic crypto, X.509, TLS). So I'm afraid getting a new X.509 feature into 2.x is really difficult now.

**Review by gilles-peskine-arm — COMMENTED** [review]
This is a trivial backport of https://github.com/ARMmbed/mbedtls/pull/2906, touching an area of the code that hasn't diverged yet between 2.2x and 3.x. As long as 2.2x doesn't enter LTS status, it is acceptable if #2906 is acceptable.

**Comment by gstrauss** [comment]
#6475 and #7436 have been merged into development branch for mbedtls-3.x

Can the result be considered for backport to mbedtls-2.28.x?

**Comment by gilles-peskine-arm** [comment]
This is a new feature, adding significant code size and some attack surface. So no, we are not going to add it to an LTS branch.

**Pull request closed without merging**
