### PR TITLE
dynamically sized key store

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Resolve the static limitation on the number of PSA keys at the expense of code size. The new option `MBEDTLS_PSA_KEY_STORE_DYNAMIC` is enabled by the default `mbedtls_config.h`, but will remain disabled by default in projects that have their own configuration file.

Fixes https://github.com/Mbed-TLS/mbedtls/issues/9216.

See https://github.com/Mbed-TLS/mbedtls/pull/9309 for a design document.

This is a direct forward-port of the 3.6 version, which minimizes the changes when the new option is disabled. We could simplify the code, and perhaps even reconsider the compile-time options. But now is not the time, both because we have other higher-priority work and because the 3.6 version may evolve after 3.6.1 and it'll be less work if development remains aligned with 3.6 for a while.

## PR checklist

- [x] **changelog** provided
- [x] **development PR** here
- [x] **framework PR** not required
- [x] **3.6 PR** https://github.com/Mbed-TLS/mbedtls/pull/9240
- [x] **2.28 PR** not required because: new feature
- **tests**  provided

### CODE REVIEW

**Review by gabor-mezei-arm — APPROVED** [review]
A faithful forward port. LGTM

**Review by bensze01 — APPROVED** [review]
Faithful forward port of #9240 as of 41e3f2067a3092293d6c21c6cebc48e1adf6f383

**Review by bensze01 — CHANGES_REQUESTED** [review]
@gilles-peskine-arm Please amend last commit to match 11cac75449e5a81cbafc87519e72c3fcedd4ebdd

**Review by bensze01 — APPROVED** [review]
LGTM

**Review by gabor-mezei-arm — APPROVED** [review]
LGTM

**Pull request merged**
