### PR TITLE
Define all PSA_xxx macros to 1 rather than have them empty, for consistency

### PR DESCRIPTION
**Pull request by tom-cosgrove-arm**
Make the change for consistency. We can think about adding errors if defined to 0 later.

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [ ] **changelog** not required - internal change
- [ ] **backport** #8146
- [ ] **tests** not required

Updating this should cause CI to re-run

### CODE REVIEW

**Review by gilles-peskine-arm — APPROVED** [review]

**Comment by tom-cosgrove-arm** [comment]
> `MBEDTLS_PSA_BUILTIN_MAC` and `MBEDTLS_PSA_BUILTIN_HASH`

I was very specifically limiting myself to the `PSA_xxx` macros, since the `MBEDTLS_xxx` macros already rarely define to `1`, whereas nearly all the `PSA_xxx` ones do, and so that would be a much larger change.

If we want to define `MBEDTLS_PSA_xxx` macros to `1`, there are some in `mbedtls_config.h`, the `MBEDTLS_PSA_ACCEL_KEY_TYPE_ECC_KEY_PAIR_xxx` in `include/psa/crypto_legacy.h`, and others.

Let's get the `PSA_xxx` ones in and then we can see how we feel about changing all the others

**Comment by gilles-peskine-arm** [comment]
> not required - this is PSA only

PSA-only is not relevant: 2.28 has PSA.

We're not going to change the behavior (which in practice is relying on `defined()`) in an LTS branch. But if there's some inconsistency in how `#define PSA_WANT_xxx 0` is handled inside 2.28, we should fix it.

(I haven't yet checked whether there is any inconsistency to fix in 2.28.)

**Comment by gilles-peskine-arm** [comment]
I've checked, some of those do apply to 2.28. So please make a backport.

**Comment by tom-cosgrove-arm** [comment]
Updated description to get CI to re-run

**Pull request merged**
