### PR TITLE
bignum: Removed merge scaffolding

### LINKED ISSUE #7305: Bignum - Clean up merge scaffolding
### Suggested enhancement

The ask for this item is to undo the merge slots introduced in PR [#6530](https://github.com/Mbed-TLS/mbedtls/pull/6530)

The ask is to remove the merge slots from `bignum_xx.c/h` and `test_suite_bignum_xx.function/data`

### Justification
Merge slots were introduced when the code was changing rapidly by multiple contirbutors. This is no longer the case

### PR DESCRIPTION
**Pull request by minosgalanakis**
## Description

This PR resolves #7305. It is cleaning up the code-base by removing the biggnum merge slots.

## Gatekeeper checklist

- [x] **changelog** Not required: not user facing
- [x] **backport** Not required: not present in LTS
- [x] **tests**Not required: changes are in comments only

### CODE REVIEW

**Review by gabor-mezei-arm — APPROVED** [review]
LGTM

**Comment by yanesca** [comment]
Sorry, I merged multiplication yesterday and it introduced a conflict. @minosgalanakis could you please rebase?

**Review by yanesca — COMMENTED** [review]
I have confirmed that all merge slots have been removed and that nothing else has been removed. Looks good to me (aside of course the conflict mentioned above).

**Review by yanesca — APPROVED** [review]
LGTM

**Pull request merged**
