### PR TITLE
Move TLS auxiliary test scripts to the framework 

### PR DESCRIPTION
**Pull request by eleuzi01**
## Description

Resolves https://github.com/Mbed-TLS/mbedtls-framework/issues/54

## PR checklist

Please remove the segment/s on either side of the | symbol as appropriate, and add any relevant link/s to the end of the line.
If the provided content is part of the present PR remove the # symbol.

- [x] **changelog** not required - internal changes
- [x] **development PR** provided 
- [x] **framework PR** provided https://github.com/Mbed-TLS/mbedtls-framework/pull/56
- [x] **3.6 PR** provided #9675 
- [x] **2.28 PR** not required because no framework in 2.28
- [x] **tests**  not required - file movement only

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

### CODE REVIEW

**Review by mpg — DISMISSED** [review]
LGTM, thanks!

**Review by mpg — APPROVED** [review]
LGTM, thanks!

**Review by mpg — APPROVED** [review]
LGTM

**Review by davidhorstmann-arm — APPROVED** [review]
LGTM, thanks!

**Comment by davidhorstmann-arm** [comment]
This and #9675 need updating after the merge of Mbed-TLS/mbedtls-framework#56, ready to re-approve once that's done

**Review by gilles-peskine-arm — APPROVED** [review]
Approving the last commit that updates the framework, based upon the the approval of 7f7036e4708471db1d170cae688d16bcfb09959e [by Manuel](https://github.com/Mbed-TLS/mbedtls/pull/9673#pullrequestreview-2371976850) or [by David](https://github.com/Mbed-TLS/mbedtls/pull/9673#pullrequestreview-2372464837).

**Review by davidhorstmann-arm — APPROVED** [review]
LGTM

**Pull request merged**
