### PR TITLE
Clarify driver handling of ALG_STREAM and ALG_ECB

### LINKED ISSUE #8315: Clarify driver handling of ALG_STREAM and ALG_ECB
Currently, `all.sh` has, in `helper_libtestdriver1_adjust_config()`, some special handling of `ALG_STREAM_CIPHER` and `ALG_ECB_NO_PADDING`, because apparently having them enabled causes partial support for cipher operations to be included in libtestdriver1 even when that's not wanted.

The algorithm `ALG_STREAM_CIPHER` is special is that it doesn't have any specific code: it's just what we use with stream ciphers, that don't require a "mode", but the PSA API still requires an alg, so `ALG_STREAM` fills that formal requirement, but what we get is really just the underlying stream cipher primitive.

The situation is almost the same with `ALG_ECB_NO_PADDING`, except it's for block ciphers, and it differs from "just the underlying primitive" by the fact that it can apply to more than one block.

Looking at `include/mbedtls/config_adjust_legacy_from_psa.h` we have the following:
```c
#if defined(PSA_WANT_ALG_STREAM_CIPHER)
#define MBEDTLS_PSA_BUILTIN_ALG_STREAM_CIPHER 1
#endif /* PSA_WANT_ALG_STREAM_CIPHER */
```
```c
#if defined(PSA_WANT_ALG_ECB_NO_PADDING) &&     \
    !defined(MBEDTLS_PSA_ACCEL_ALG_ECB_NO_PADDING)
#define MBEDTLS_PSA_BUILTIN_ALG_ECB_NO_PADDING 1
#endif
// ...
/* If any of the block modes are requested that don't have an
 * associated HW assist, define PSA_HAVE_SOFT_BLOCK_MODE for checking
 * in the block cipher key types. */
#if (defined(PSA_WANT_ALG_CTR) && !defined(MBEDTLS_PSA_ACCEL_ALG_CTR)) || \
    (defined(PSA_WANT_ALG_CFB) && !defined(MBEDTLS_PSA_ACCEL_ALG_CFB)) || \
    (defined(PSA_WANT_ALG_OFB) && !defined(MBEDTLS_PSA_ACCEL_ALG_OFB)) || \
    defined(PSA_WANT_ALG_ECB_NO_PADDING) || \
    (defined(PSA_WANT_ALG_CBC_NO_PADDING) && \
    !defined(MBEDTLS_PSA_ACCEL_ALG_CBC_NO_PADDING)) || \
    (defined(PSA_WANT_ALG_CBC_PKCS7) && \
    !defined(MBEDTLS_PSA_ACCEL_ALG_CBC_PKCS7)) || \
    (defined(PSA_WANT_ALG_CMAC) && !defined(MBEDTLS_PSA_ACCEL_ALG_CMAC))
#define PSA_HAVE_SOFT_BLOCK_MODE 1
#endif
```

It looks like for some reason those are not handled the usual way regarding `ACCEL` macros.

This task to investigate why. Possible outcomes:

1. Remove special handling of those two if possible.
2. Otherwise, improve documentation about why they have to be handled in a special way.

### PR DESCRIPTION
**Pull request by valeriosetti**
## Description

This PR resolves #8315.

## PR checklist

- [ ] **changelog** should this be postponed to #6337? In that case I can just put one sentence here to track what I did
- [x] **backport** not required
- [x] **tests** not required

### CODE REVIEW

**Review by mpg — APPROVED** [review]
LGTM.

**Comment by mpg** [comment]
> changelog should this be postponed to https://github.com/Mbed-TLS/mbedtls/issues/6337? In that case I can just put one sentence here to track what I did

Let's do that.

Note: I'm not even convinced this belongs in the ChangeLog: we mostly fixed things in our tests and test tools. Only the change in `adjut_legacy_from_psa.h` is potentially user-visible, but since the situation was undocumented before, I'm inclined to not mention this specific change in the ChangeLog, and just clearly document the new state in the upcoming documentation. We'll see when we do #6337.

**Comment by valeriosetti** [comment]
Rebased after #8346 was merged

**Review by d3zd3z — APPROVED** [review]
The only suggestion I'd make is maybe clarify a bit in the commit text, especially for the first commit, what is actually being fixed. I had to dig through to the issue to really understand it, and that can be hard to get to when someone just has a git tree they are looking at.

**Review by mpg — APPROVED** [review]
Still LGTM after rebase.

**Pull request merged**
