### PR TITLE
Remove md_info in ssl_tls12_populate_transform() when USE_PSA_CRYPTO is defined

### PR DESCRIPTION
**Pull request by superna9999**
## Description
Remove md_info in ssl_tls12_populate_transform() when USE_PSA_CRYPTO is defined

Follow-up to #5573
See https://github.com/ARMmbed/mbedtls/issues/5179#issuecomment-1066520054

## Status
**READY**

## Requires Backporting
NO 

## Migrations
NO

## Additional comments
N/A

## Todos
- [X] Tests

## Steps to test or reproduce
ssl-opt.sh & test_suite_pk must run clean

### CODE REVIEW

**Comment by superna9999** [comment]
@minosgalanakis it refers to https://github.com/Mbed-TLS/mbedtls/issues/5179#issuecomment-1066520054 and is a follow up to https://github.com/Mbed-TLS/mbedtls/pull/5573

**Review by mpg — APPROVED** [review]
LGTM

**Comment by mpg** [comment]
@minosgalanakis Regarding context: the long-term motivation is that we'd like to get rid of the MD layer eventually (at least, remove it from the public API) and only use the PSA Crypto API for everything. This is done incrementally, see `docs/architecture/psa-migration` for the current state (well, current at the end of last year) and an outline of the next steps, as well as the various EPICs with "use PSA" in the name - specifically, this PR is a small step towards #5211.

(Not everything is fully fleshed out however, especially regarding more long-term steps, so there might be a few things that I take for granted but are unfortunately unwritten yet - I'm due to update those documents before we release 3.2 anyway, so I'll try to pay attention to that.)

I agree that commit messages should explain the motivation in general, but OTOH for long-running efforts like migrating from "legacy" crypto API to PSA Crypto API, I don't think it's necessary to reference the goal in every single commit. Also, we can always find the PR that introduced a commit and look at it if more context is needed - of course that only works if we have good enough PR descriptions, and are not afraid to ask for clarification if needed, like you did :)

**Comment by mpg** [comment]
The internal CI is passing, except the `win32-msvc12_64` component on pr-merge which didn't start due to a temporary network issue; since that component passed in the pr-head job, I'm calling it good enough for merging.

**Pull request merged**
