### PR TITLE
Backport 2.28: Enable mpi_mod_int test case to take full-range MPI integers

### PR DESCRIPTION
**Pull request by tom-cosgrove-arm**
Backport of #6573 

## Gatekeeper checklist

- [x] **changelog** not required - this is tests
- [x] **backport** - this is the backport
- [x] **tests**  these are tests

### CODE REVIEW

**Review by wernerlewis — DISMISSED** [review]
LGTM, faithful backport

**Review by gilles-peskine-arm — DISMISSED** [review]
LGTM

We should backport the renaming of the test functions to make backports like this one easier.

**Review by wernerlewis — APPROVED** [review]

**Comment by gilles-peskine-arm** [comment]
Please rebase with the renamed test suite — sorry. Git seems to cope with a rebase without assistance, but can't figure out a merge.

**Review by gilles-peskine-arm — APPROVED** [review]
LGTM

**Comment by tom-cosgrove-arm** [comment]
CI has passed, so removing `needs-ci`

**Pull request merged**
