### PR TITLE
Check remaning dependencies on ECP in PK module

### LINKED ISSUE #7460: Improve pk_wrap calling convention and check for remaning ECP dependencies in PK files
Following the [comments](https://github.com/Mbed-TLS/mbedtls/pull/7202#issuecomment-1508063453) in #7073 and discussion on slack, here is the to do list to be addressed before starting #7073 and #7074:

- [ ] Add missing USE_PSA_INIT()/DONE() in tests - actually while at it we could do this in a systematic way: according to [our own documentation](https://github.com/Mbed-TLS/mbedtls/blob/development/include/mbedtls/mbedtls_config.h#L1933) all PK, X.509 and SSL tests should have it (unless they already have MD_OR_USE_PSA_INIT()/DONE() of course, or a plain PSA_INIT()/PSA_DONE() for 1.3 tests). (Note: there's one in mbedtls_test_ssl_perform_handshake(), so test functions that are merely a wrapper around that don't need it.)
    - #7461 
- [ ] Change the calling convention to pass the full pk_context for existing wrappers - might be worth checking that the CI fully passes at this point (actually those two commits could even be a separate PR). See also [this comment](https://github.com/Mbed-TLS/mbedtls/pull/7202#discussion_r1170999430)
    - https://github.com/Mbed-TLS/mbedtls/pull/7463
- [x] grep for remaining mbedtls_ecp functions in PK files and think about what's the plan for replacing/removing each one of them
    - https://github.com/Mbed-TLS/mbedtls/pull/7465

## Note for reviewers/gatekeepers
All the points mentioned above will be addressed by separate PRs, so please wait for all of them to be addressed before closing this issue.

### PR DESCRIPTION
**Pull request by valeriosetti**
This is the 3rd step of #7460
Resolves #7460 (partially)
~Requires #7463~

## Gatekeeper checklist

- [x] **changelog** not required - internal script
- [x] **backport** not required - internal script
- [x] **tests** not required - internal script

### CODE REVIEW

**Comment by valeriosetti** [comment]
Reply to [this comment](https://github.com/Mbed-TLS/mbedtls/issues/7460#issuecomment-1515926682)
Good idea! I forgot about the `syms.sh` script, but here it should work quite good. I just started this PR with a [proposal](https://github.com/Mbed-TLS/mbedtls/pull/7465/commits/d3641d17149736596d81d5dbcb0038df40c90c51) for an improvement of this script which can be helpful for what we are going to analyze here.

Using that script, here's what I found:
```
./docs/architecture/psa-migration/syms.sh full pk pkparse pkwrite
cat full-*-external | grep mbedtls_ecp | sort -u
```

```
mbedtls_ecp_check_privkey
mbedtls_ecp_check_pubkey
mbedtls_ecp_group_free
mbedtls_ecp_group_init
mbedtls_ecp_group_load
mbedtls_ecp_grp_id_list
mbedtls_ecp_keypair_free
mbedtls_ecp_point_free
mbedtls_ecp_point_read_binary
mbedtls_ecp_point_write_binary
mbedtls_ecp_restart_is_enabled
mbedtls_ecp_write_key
```

**Comment by valeriosetti** [comment]
Here's my thoughts about these remaining dependencies:

- mbedtls_ecp_check_privkey
    - once #7074 will be completed we will import the private key also in PSA and this checks key's validity while importing (see `psa_crypto_ecp`), so we will skip this check

- mbedtls_ecp_check_pubkey
    - basically the same as the previous one, but it depends on #7073. The check on the PSA side is still done in `psa_crypto_ecp`

- mbedtls_ecp_group_free, mbedtls_ecp_group_init, mbedtls_ecp_grp_id_list, mbedtls_ecp_point_free
    - these are used only when `MBEDTLS_PK_PARSE_EC_EXTENDED` is enabled. It is [already planned](https://github.com/Mbed-TLS/mbedtls/issues/7442) to have `ECP_LIGHT` enabled when `MBEDTLS_PK_PARSE_EC_EXTENDED` also is, otherwise it would not be possible to parse custom curves

- pk_use_ecparams
    - a part from the  `MBEDTLS_PK_PARSE_EC_EXTENDED` dependency which goes back to the previous point, this is also used in `pk_use_ecparams`. We can get rid of this part once #7073 and #7074 are done

- mbedtls_ecp_keypair_free
    - easily removable after #7073 and #7074

- mbedtls_ecp_point_read_binary
    - 1 reference depends on `MBEDTLS_PK_PARSE_EC_EXTENDED`, while the other 2 should disappear once #7073 and #7074 are addressed

- mbedtls_ecp_point_write_binary
    - references in `eckey_check_pair_psa` and `ecdsa_verify_wrap` will be dropped in #7073 + #7074

- mbedtls_ecp_restart_is_enabled
    - restartable functions are not available in PSA yet, so having `ECP_LIGHT` enabled is mandatory to use this functionality. As a consequence the dependency will disappear by disabling `MBEDTLS_ECP_RESTARTABLE`

- mbedtls_ecp_write_key
    - will probably be replaced by `psa_export` in #7074

**Comment by valeriosetti** [comment]
Following my previous comment, here is the list of dependencies when `MBEDTLS_ECP_RESTARTABLE` and `MBEDTLS_PK_PARSE_EC_EXTENDED` are also disabled on top of the `full` configuration

```
mbedtls_ecp_check_privkey
mbedtls_ecp_check_pubkey
mbedtls_ecp_group_load
mbedtls_ecp_keypair_free
mbedtls_ecp_point_read_binary
mbedtls_ecp_point_write_binary
mbedtls_ecp_write_key
```

**Comment by mpg** [comment]
> ./docs/architecture/psa-migration/syms.sh full pk pkparse pkwrite

I think we should add `pk_wrap` to that list.

**Comment by valeriosetti** [comment]
> > ./docs/architecture/psa-migration/syms.sh full pk pkparse pkwrite
> I think we should add `pk_wrap` to that list.

Right, but fortunately this doesn't add much to the list:

- `mbedtls_ecp_keypair_free` and `mbedtls_ecp_keypair_init` can be removed after #7073 and #7074
- `mbedtls_ecp_point_write_binary`  is used in `ecdsa_verify_wrap` but can be removed after #7073

**Comment by mpg** [comment]
> Requires #7463

I'm not sure I understand why. Can't we have just the changes to `all.sh` and `syms.sh` without the others?

**Comment by valeriosetti** [comment]
> I'm not sure I understand why. Can't we have just the changes to all.sh and syms.sh without the others?

TBH this was mostly for me to ease the rebase process for the reshape of #7202. There is no strict requirement for that.
Do you want me to rebase this PR on `development`?

**Comment by mpg** [comment]
Yes, I'd prefer to have this based on development, that way we can merge it quickly.

(For the rework of 7202, I think you can start with merging the 3 pre-requisite PRs into your feature branch. Then you can remove the merge commits once all 3 are merged to development.)

**Review by mpg — APPROVED** [review]
LGTM, both the changes to the script, and the analysis.

**Pull request merged**
