### PR TITLE
Backport 3.6: Split check_test_cases.py and outcome_analysis.py

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
* Split `check_test_cases.py` into test case collection (`collect_test_cases.py`, used by outcome analysis) and the checks proper. Move both parts to the framework.
* Split `analyze_outcomes.py` into code (`outcome_analysis.py`, moved to the framework) and data (`analyze_outcomes.py`, stays in its branch).
* Upgrade mypy, for the sake of a new feature in `outcome_analysis.py`.
* Prepare to require all test cases to be executed, i.e. to enforcing full coverage. But for now, keep it as a warning in this branch. To be continued in the backport of https://github.com/Mbed-TLS/mbedtls/pull/9593.

## PR checklist

- [x] **changelog** not required because: test stuff only
- [x] **development PR** provided #9668
- [x] **framework PR** provided Mbed-TLS/mbedtls-framework#55
- [x] **3.6 PR** here
- [x] **2.28 PR** not required because: no framework in 2.28, and the improvements to outcome analysis aren't worth backporting at this stage
- **tests**  provided

### CODE REVIEW

**Review by eleuzi01 — APPROVED** [review]
LGTM

**Review by mpg — DISMISSED** [review]
LGTM.

Straightforward backport with an extra initial commit. I checked that this commit indeed aligns with development, and is harmless in 3.6.

**Review by eleuzi01 — APPROVED** [review]
LGTM

**Review by mpg — APPROVED** [review]
LGTM

**Review by mpg — APPROVED** [review]
LGTM after updating the framework pointer.

**Review by eleuzi01 — APPROVED** [review]

**Pull request merged**
