### PR TITLE
ssl-opt: improve PSK mode detection

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Fix some issues in `ssl-opt.sh` around requirement detections, mostly related to PSK vs certificates. Prerequisite of https://github.com/Mbed-TLS/mbedtls/pull/9541.

Straight forward port of https://github.com/Mbed-TLS/mbedtls/pull/9546.

## PR checklist

- [x] **changelog** not required because: test only
- [x] **development PR** here
- [x] **framework PR** https://github.com/Mbed-TLS/mbedtls-framework/pull/44
- [x] **3.6 PR** #9546
- [x] **2.28 PR** not required because: it's mostly about TLS 1.3 changes, and not worth backporting the few changes that aren't.
- **tests**  provided + check that we aren't executing fewer test cases, compared with the baseline [`outcomes.csv.xz`](https://mbedtls.trustedfirmware.org/job/mbed-tls-nightly-tests/928/artifact/outcomes.csv.xz) (excluding `;component_release_` which are not run in the PR job). The following command lists the test cases that have changed, excluding those that used to be skipped; its output is empty.
    ```
    wget -O 8c95999b3828f1b3e7a069e61c2b33b9f509e446.outcomes.csv.xz https://mbedtls.trustedfirmware.org/job/mbed-tls-nightly-tests/942/artifact/outcomes.csv.xz
    wget -O 1.outcomes.csv.xz https://mbedtls.trustedfirmware.org/job/mbed-tls-pr-head/job/PR-9556-head/1/artifact/outcomes.csv.xz
    comm -23 <(xzcat 8c95999b3828f1b3e7a069e61c2b33b9f509e446.outcomes.csv.xz | grep -v ';component_release_' | sort) <(xzcat 1.outcomes.csv.xz | sort) | grep -v ';SKIP;'
    ```

### CODE REVIEW

**Review by ronald-cron-arm — DISMISSED** [review]
LGTM but it seems you need to rebase the framework PR.

**Comment by gilles-peskine-arm** [comment]
I'll need to rewrite the history to amend the submodule update commit, anyway, once the framework PR is merged.

How about I do that now, since the framework PR is approved and has passed the CI on both branches?

**Review by mpg — APPROVED** [review]
LGTM but there's a conflict in framework (also in the 3.6 PR now).

**Comment by gilles-peskine-arm** [comment]
I've rebased both this PR and the 3.6 one to get the latest framework updates.

**Review by mpg — APPROVED** [review]
The rebase looks good to me.

**Review by ronald-cron-arm — APPROVED** [review]
LGTM

**Pull request merged**
