### PR TITLE
Coverity fix: Set `type_id` in `x509_get_other_name()`

### PR DESCRIPTION
**Pull request by davidhorstmann-arm**
When parsing a subject alternative name of type otherName, retain the type-id field of the otherName. Previously this was not copied to the `mbedtls_x509_san_other_name` struct when it should have been.

This fixes an issue found by Coverity

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** provided
- [x] **backport** #8096 
- [x] **tests** not required - Previous testing covers this area (now that they are fixed up)

### CODE REVIEW

**Review by tgonzalezorlandoarm — APPROVED** [review]
LGTM

**Comment by tgonzalezorlandoarm** [comment]
I think it's alright not include any other testing

**Review by paul-elliott-arm — APPROVED** [review]
LGTM

**Comment by paul-elliott-arm** [comment]
> I think it's alright not include any other testing

I agree with this - I think we already have tests to cover this, its just they were not correct.

**Pull request merged**
