### PR TITLE
Mbedtls 2.28.6

### PR DESCRIPTION
**Pull request by daverodgman**
## Description

This results in (almost) no changes to tip, but includes commit 3a91dad9dceb484eea8b41f8941facafc4520021 which is suitable to be released as 2.28.6

Intended changes to tip are:
- Changelog
- Changes produced by bump_version.sh
- BRANCHES.md
- Everest docs in config.h

Note: github shows a lot of changes that were made and then reverted by this PR - it's clearer to review this locally.

Release CI https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-new/820/

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** provided
- [x] **backport** this is it
- [x] **tests** not required

### CODE REVIEW

**Review by minosgalanakis — DISMISSED** [review]
LGTM

**Review by waleed-elmelegy-arm — APPROVED** [review]
LGTM

**Review by minosgalanakis — APPROVED** [review]
LGTM

**Comment by daverodgman** [comment]
I missed a sign-off on the merge commit, but not going to iterate just for this.

**Pull request merged**
