### PR TITLE
TLS 1.3 SRV EarlyData: Ignore application message when rejected

### LINKED ISSUE #6360: TLS 1.3 server: Implement and test behaviour one when receiving an "early_data" extension
SPEC:
A server which receives an "early_data" extension MUST behave in one
of three ways:
- Ignore the extension and return a regular 1-RTT response. The server then skips past early data by attempting to deprotect received records using the handshake traffic key, discarding records which fail deprotection (up to the configured max_early_data_size). Once a record is deprotected successfully, it is treated as the start of the client’s second flight and the server proceeds as with an ordinary 1-RTT handshake.
- ...

The purpose of this issue is to implement and test the behavior described just above.
The "configured max_early_data_size" should be 0 but in the case of early data associated to a valid PSK (valid from the handshake point of view) established through a NewSessionTicket where it is then equal to the max_early_data_size associated to the PSK.

Testing:
An MbedTLS client sends as part of a session resumption less early data than the maximum authorized by the associated ticket to an MbedTLS server but the server does not eventually accept early data (because the PSK ciphersuite is not available on the server for example). The PSK based handshake succeeds but not the early data transfer.

Depends on: #6341

### PR DESCRIPTION
**Pull request by yuhaoth**
## Description

fix #6360.

- Ignore the extension and return a regular 1-RTT response. The server then skips past early data by attempting to deprotect received records using the handshake traffic key, discarding records which fail deprotection (up to the configured max_early_data_size). Once a record is deprotected successfully, it is treated as the start of the client’s second flight and the server proceeds as with an ordinary 1-RTT handshake.

## PR checklist

- [x] **changelog** not required
- [x] **backport**  not required
- [x] **tests** provided

### CODE REVIEW

**Comment by yuhaoth** [comment]
OpenCI pass and internal CI fail

**Review by ronald-cron-arm — CHANGES_REQUESTED** [review]
Early review. The change in the code looks at the right place to me. We miss some testing now though I'd say. We need the GnuTLS to reconnect with a valid ticket while early data are disabled on the server side. I've seen in #6485 that you introduce some "reco_*" option as we already have in ssl_client2. That is a good way to go I'd say. Thus here it would be an "reco_early_data" flag option to enable/disable early data before getting a resumption request.

**Comment by ronald-cron-arm** [comment]
> In #6721 , I introduce list of `max_early_data_size`
Not the case anymore I think. Otherwise if we only need two values for this option, one for the first connection, one for the re-connection I do not think that a list is the best solution, a `reco_*` additional option seems more suitable to me.

> In the server side, I define the option like below, I am thinking about that, what's your suggestion?
#define USAGE_EARLY_DATA \
    "    max_early_data_size=%%d default: -1 (disabled)\n"             \
    "                            options: -1 (disabled), "           \
    "                                     >= 0 (enabled, max amount of early data )\n"

In the spirit of what we ended up in #8596 I think it would rather be two options, one being `early_data` with the enabled and disabled values.

**Comment by yuhaoth** [comment]
@ronald-cron-arm , I just update some commits for early review. Please take a quick look.

**Comment by ronald-cron-arm** [comment]
Thinking about the options we need in ssl_server2 for early data, it seems to me that in the first place we have an issue with the configuration of the TLS 1.3 server. Currently on server side, we use `early_data_enabled` configuration for two different things:
1) Enable the reading of early data through `mbedtls_ssl_read_early_data()`
2) Enable the setting of the "early data allowed" ticket flag when creating and sending tickets to the client.

It seems better to me to use `mbedtls_ssl_conf_early_data()` only for 1).

For 2) we could extend and deprecate `mbedtls_ssl_conf_new_session_tickets()`.  `mbedtls_ssl_conf_new_session_tickets_ext()` would have a new parameter `allow_early_data` that we would use for case 2.

**Comment by ronald-cron-arm** [comment]
> > For 2) we could extend and deprecate `mbedtls_ssl_conf_new_session_tickets()`. `mbedtls_ssl_conf_new_session_tickets_ext()` would have a new parameter `allow_early_data` that we would use for case 2.
> 
> Another option is to deprecate `mbedtls_ssl_ticket_write_t` or extend it to allow modify session , like #8525
> 
> And I'd like postpone this issue. I just put it in #7068 for I am not sure if we should create issue.

Yes that seems reasonable, I will create a ticket to track the issues around tickets.

**Comment by ronald-cron-arm** [comment]
Superseded by #8727.

**Pull request closed without merging**
