### PR TITLE
Backport RSA signature/verification tests

### PR DESCRIPTION
**Pull request by mprse**
## Description
Backport part of PR https://github.com/ARMmbed/mbedtls/pull/5292 (the new signature/verification tests).

Resolves https://github.com/ARMmbed/mbedtls/issues/5618.

## Status
**READY**

### CODE REVIEW

**Review by AndrzejKurek — CHANGES_REQUESTED** [review]
I would recommend having the following tests in the same order, in the same place as the original (to backport further fixes easier):

```
- sign_message transparent driver: fake RSA PKCS#1 v1.5 SHA-256
- sign_message transparent driver: error RSA PKCS#1 v1.5 SHA-256
- sign_message transparent driver: fallback RSA PKCS#1 v1.5 SHA-256
- sign_message transparent driver: calculate in driver RSA PKCS#1 v1.5 SHA-256
- sign_message transparent driver: fake ECDSA SECP256R1 SHA-256
- sign_message transparent driver: error ECDSA SECP256R1 SHA-256
- sign_message transparent driver: fallback ECDSA SECP256R1 SHA-256
- sign_message transparent driver: calculate in driver ECDSA SECP256R1 SHA-256
```

**Review by AndrzejKurek — APPROVED** [review]

**Comment by mprse** [comment]
This one is waiting for quite long. It is approved but CI does not look good.
I restarted Jenkins, but don't know how to restart open-ci.

**Comment by AndrzejKurek** [comment]
> This one is waiting for quite long. It is approved but CI does not look good. I restarted Jenkins, but don't know how to restart open-ci.

You could try a no-edit commit and force-push, but this will probably restart all CI jobs:
`git commit --amend --no-edit`

**Review by mpg — APPROVED** [review]
Approving as a faithful backport of the 4 relevant commits in #5292

**Pull request merged**
