### PR TITLE
Fix usage & error reporting in SSL programs

### PR DESCRIPTION
**Pull request by mpg**
## Description

- Allow calling without arguments again
- Add explicit "help" and "help_ciphersuites" parameters
- Add info about what went wrong in case of usage errors

This is mostly trying to improve on things which have been annoying me regularly. (I've already written the part about reporting what exactly went wrong more that once locally.) The goal is not for everything to be perfect, just better than the status quo.

## PR checklist

- [x] **changelog** not required - minor change to test programs
- [x] **backport** https://github.com/Mbed-TLS/mbedtls/pull/8118
- [x] **tests** not required - manually tested by calling the programs in a variety of ways

### CODE REVIEW

**Comment by gowthamsk-arm** [comment]
The error reporting looks clean now, and identifying the issue is much easier. Thanks :)

**Review by gowthamsk-arm — APPROVED** [review]
The external CI jobs seem to have some issues.

**Review by gilles-peskine-arm — APPROVED** [review]
Looks good to me, thanks for pushing this through!

**Comment by gilles-peskine-arm** [comment]
I've pushed a merge of the target branch to get fresh CI results.

**Review by gilles-peskine-arm — APPROVED** [review]
I hereby assert that the commit I pushed to this branch is a merge of the target branch. [This can easily be checked on GitHub](https://github.com/Mbed-TLS/mbedtls/pull/7844/commits/f745e5b8de884441cae11b0fd60d371ff349ddd7).

**Pull request merged**
