### PR TITLE
3.6: Projects and 3.6 branch detections

### PR DESCRIPTION
**Pull request by ronald-cron-arm**
## Description

Companion PR of #9552 and Mbed-TLS/mbedtls-framework/pull/45
Just update the framework as in #9552 

## PR checklist

- [x] **changelog** not required because: changes to an internal script 
- [x] **development PR** https://github.com/Mbed-TLS/mbedtls/pull/9552
- [x] **framework PR** Mbed-TLS/mbedtls-framework#45
- [x] **3.6 PR** here
- [x] **2.28 not required because: 4.x/3.x only work
- **tests**  not required because: internals

### CODE REVIEW

**Review by davidhorstmann-arm — DISMISSED** [review]
Ah I didn't realise there was already a `project_name.txt` in 3.6, the framework PR wouldn't have broken anything after all.

LGTM, thanks!

**Review by minosgalanakis — DISMISSED** [review]
LGTM

**Review by minosgalanakis — APPROVED** [review]
LGTM ( The open CI failure looks to be unrelated & spurious)

**Review by davidhorstmann-arm — DISMISSED** [review]
LGTM, thanks!

**Comment by davidhorstmann-arm** [comment]
I've restarted the CI - if it was a spurious failure it should pass on rerun

**Review by davidhorstmann-arm — APPROVED** [review]
LGTM, thanks!

**Review by minosgalanakis — APPROVED** [review]
LGTM

**Pull request merged**
