### PR TITLE
Minor fixes to test_data_generation.py

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
This is a collection of minor fixes to issues I found in Python scripts near the end of my review of https://github.com/Mbed-TLS/mbedtls/pull/6093. I didn't want to hold that PR for minor, mostly preexisting issues, hence this follow-up.

* [Less ambiguous name for `test_generation.py`](https://github.com/Mbed-TLS/mbedtls/pull/6093#discussion_r973333528).
* [Fix paths when not invoked from the mbedtls root](https://github.com/Mbed-TLS/mbedtls/pull/6093#discussion_r973329644).
* [Docstring that should have been a comment](https://github.com/Mbed-TLS/mbedtls/pull/6093#discussion_r973325217).
* Use relative imports (fixes e.g. running `python3 -m unittest scripts/mbedtls_dev/psa_storage.py`).
* Unify the 4 copies of `check_repo_path` (reported by `pylint` when not running with `-j`).
* Don't run pylint with `-j` since that makes it not signal code that's duplicated in different modules.
* Generated .data files are now replaced atomically. (How did I live without this when working on the generated storage tests??)

Changelog: no (no user-visible bugs were fixed).

Backport: https://github.com/Mbed-TLS/mbedtls/pull/6424

### CODE REVIEW

**Review by wernerlewis — DISMISSED** [review]
LGTM. Python changes are good improvements, CMake changes seem reasonable for the change in script behavior.

**Review by gabor-mezei-arm — CHANGES_REQUESTED** [review]
Just one misspell otherwise LGTM

**Review by gabor-mezei-arm — APPROVED** [review]
LGTM

**Review by wernerlewis — APPROVED** [review]
LGTM

**Comment by yanesca** [comment]
@gilles-peskine-arm do you think you will have time to raise a backport?(https://github.com/Mbed-TLS/mbedtls/pull/6307 is now merged.)

I am interested in merging because https://github.com/Mbed-TLS/mbedtls/pull/6399 depends on this.

**Pull request merged**
