### PR TITLE
Added the uniformResourceIdentifier subtype for the subjectAltName.

### PR DESCRIPTION
**Pull request by hannestschofenig**
## Description

OPC UA carries a ProductInstanceUri and, optionally, a CompositeInstanceUri as a uniformResourceIdentifier in the subjectAltName field of an X.509 certificate. This PR adds parsing support for the uniformResourceIdentifier subtype to the subjectAltName field.

Signed-off-by: Hannes Tschofenig <hannes.tschofenig@arm.com>

## Gatekeeper checklist

- [ ] **changelog** provided, or not required
- [ ] **backport** done, or not required
- [x] **tests** provided, or not required

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

### CODE REVIEW

**Comment by mpg** [comment]
Hi Hannes! Thanks for your PR. Apparently the CI has found some issues with test dependencies, can you look into them?

**Comment by AndrzejKurek** [comment]
I think that [this](https://github.com/AndrzejKurek/mbedtls/commit/91156d1f93f7a529d5cfdd60b099c35fff164e12) should do the trick :)

**Comment by AndrzejKurek** [comment]
Are you willing to continue working on this PR, @hannestschofenig, or would you like me to take it over? :)

**Comment by AndrzejKurek** [comment]
Work continued [here](https://github.com/Mbed-TLS/mbedtls/pull/7025).

**Pull request closed without merging**
