### PR TITLE
Fix wrong dependencies in test cases

### PR DESCRIPTION
**Pull request by mpg**
## Description

Continuing & replacing #8594 (to which I can't push). Only the last two commits are new, everything else is from #8594.

## PR checklist

- [x] **changelog** not required - style fix in tests
- [x] **3.6 backport** done - #9009
- [x] **2.28 backport** not required - already done in #8996
- [x] **tests** not required - style fix in tests

### CODE REVIEW

**Review by Ryan-Everett-arm — APPROVED** [review]
LGTM, thanks!

**Review by gilles-peskine-arm — COMMENTED** [review]
LGTM at f4e1fc5aff03b91ab8f138fdab47b91c6125c3b7

However, the CI failed on merge for https://github.com/Mbed-TLS/mbedtls/pull/8594. Something must have bitrotted. Please rebase or add a merge commit so that pr-head tests something closer to what will be merged.

**Review by Ryan-Everett-arm — APPROVED** [review]
LGTM

**Review by gilles-peskine-arm — APPROVED** [review]
LGTM

**Pull request merged**
