### PR TITLE
Error codes: enforce add macro

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Enforce the use of `MBEDTLS_ERROR_ADD` to add a low-level error code with a high-level error code.

This is a step of DI towards.https://github.com/Mbed-TLS/mbedtls/issues/8501.

## PR checklist

- [x] **changelog** not required because: no behavior change
- [x] **development PR** here
- [x] **framework PR** not required
- [x] **3.6 PR** not required because: 4.0 prep
- [x] **2.28 PR** not required because: 4.0 prep
- **tests**  provided

### CODE REVIEW

**Review by yanesca — APPROVED** [review]
I have reviewed the script in the commit message and executed it locally arriving at the same result. I have reviewed the last two commits manually.

Looks good to me.

**Review by paul-elliott-arm — CHANGES_REQUESTED** [review]
LGTM, however will need rebase due to conflicts.

**Comment by gilles-peskine-arm** [comment]
I have rebased on top of the latest `development` to take care of the merge conflict. For "Use MBEDTLS_ERROR_ADD instead of explicit addition: simple cases", I replayed the script. For the other commits, there was no conflict.

**Review by yanesca — APPROVED** [review]
LGTM

**Comment by gilles-peskine-arm** [comment]
The [failure on the merge queue](https://mbedtls.trustedfirmware.org/blue/rest/organizations/jenkins/pipelines/mbed-tls-pr-head/branches/gh-readonly-queue%252Fdevelopment%252Fpr-9566-4e4647a4e7ab4e88feb7dca9600e2800f1284d8c/runs/1/nodes/506/steps/3158/log/?start=0) was a timeout in one test case of `ssl-opt.sh`. I'm requeuing it.

**Pull request merged**
