### PR TITLE
pkwrite: fix buffer overrun

### PR DESCRIPTION
**Pull request by valeriosetti**
## Description

This PR fixes a potential buffer overrun in:
- `pk_write_rsa_der`
- `pk_write_ec_pubkey`

In both functions, when dealing with opaque keys, there was no check that the provided buffer was large enough to contain the key being exported. This commit fixes this problem and it also adds some testing in `test_suite_pkwrite` to trigger these checks.

Resolve https://github.com/Mbed-TLS/mbedtls/issues/9699 discovered with the tests added here.

## PR checklist

- [x] **changelog** provided
- [x] **development PR** it's this one
- [x] **framework PR** not required
- [x] **3.6 PR** provided https://github.com/Mbed-TLS/mbedtls/pull/9698
- [x] **2.28 PR** not required because: offending code added in 3.5
- **tests**  provided

### CODE REVIEW

**Comment by valeriosetti** [comment]
@mpg I know you are busy with other stuff, but can I ask you to take a look at this fix when you have some spare time? Mostly because you reviewed the PR that I did when I reshaped `pkwrite` so you already have some background about it. Plus it's also quite short as PR :)

**Review by gilles-peskine-arm — COMMENTED** [review]
Looks good to me so far. Can you please cherry-pick some commits from https://github.com/Mbed-TLS/mbedtls/pull/9698, to align `development` with 3.6 and get a passing CI?

* 453fd05333 Changelog entry for security fix
* 93d421e751 Defer static keystore to 3.6.3
* 107ea89daa Fix completion mistake in changelog entry
* 765da156bd Work around GCC 5 performance problem with Asan+UBSan and -O3
* bac001f62e Temporarily comment out tests that are clogging the CI

(I think we actually don't want bac001f62e, I made a mistake by leaving it into the final version for 3.6, but it'll be easier to deal with it in a follow-up, let's keep the branches aligned.)

**Comment by valeriosetti** [comment]
Cherry-picked and adapter when necessary all the [relevant commits](https://github.com/Mbed-TLS/mbedtls/pull/9690#pullrequestreview-2369504968) from #9698

**Review by gilles-peskine-arm — APPROVED** [review]
Thanks for the update, LGTM

**Review by davidhorstmann-arm — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
