### PR TITLE
[Backport 3.6] psa_util.c included in builds without PSA, which can break the build

### PR DESCRIPTION
**Pull request by sezrab**
Backport of #9313 

## PR checklist

- [x] **changelog** provided
- [x] **3.6 backport** provided - this is the backport.
- [x] **2.28 backport** not required, feature doesn't exist
- [x] **tests** not required because we removed buggy functions in configurations that made them buggy. See also #9317

### CODE REVIEW

**Comment by gilles-peskine-arm** [comment]
This is missing the changes to the test suite.

**Comment by sezrab** [comment]
> This is missing the changes to the test suite.

@gilles-peskine-arm I think [`test_suite_psa_crypto_util.function`](https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.6/tests/suites/test_suite_psa_crypto_util.function) already uses `MBEDTLS_PSA_UTIL_HAVE_ECDSA` in 3.6

**Comment by gilles-peskine-arm** [comment]
> I think test_suite_psa_crypto_util.function already uses MBEDTLS_PSA_UTIL_HAVE_ECDSA in 3.6

Ah. So it does. The difference between 3.6 and development still doesn't quite make sense to me, but I now think that something's wrong with the development PR because things changed on the development branch after you started working. Let me look closer.

**Review by gilles-peskine-arm — APPROVED** [review]
Looking at this independently on the `mbedtls-3.6` branch:

We want to resolve a [bug](https://github.com/Mbed-TLS/mbedtls/issues/9311) in 3.6.0 whereby the ECDSA conversion functions don't work when PSA is disabled (due to a buffer size that only works in builds with PSA). Since the functions are not very useful without PSA and didn't work without PSA, we want to disable them in builds without PSA. This pull request does the requisite change.

Incidentally, it has come up that the tests of these functions were only running in builds with PSA. The preprocessor guard on the test functions is the same as the guard on the library functions: `MBEDTLS_PSA_UTIL_HAVE_ECDSA`, so there's nothing to fix there. The lack of test coverage came from guards on the test cases, which depend on PSA support for curve sizes. Since the library functions are now enabled only in builds with PSA, the test cases do run in all the builds that have the library functions. So we don't need to change anything else in the tests.

Therefore this pull request correctly fixes the bug.

There is no non-regression test, but that would come through stricter compiler flags and we'll handle that in a separate pull request (backport of https://github.com/Mbed-TLS/mbedtls/pull/9456, addressing https://github.com/Mbed-TLS/mbedtls/issues/9317).

**Review by mpg — APPROVED** [review]
LGTM. As pointing out previously, the patch differs from the development patch, but in ways that have been explained in the meantime, so it's all good.

**Pull request merged**
