### PR TITLE
Always enable MBEDTLS_USE_PSA_CRYPTO in all.sh

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
A step towards https://github.com/Mbed-TLS/mbedtls/issues/9630: we no longer test with `MBEDTLS_USE_PSA_CRYPTO` disabled. It's still possible to disable it explicitly; that will be handled in a follow-up.

Note: this may conflict with the work to migrate `depends.py` to the PSA configuration (https://github.com/Mbed-TLS/mbedtls/pull/9292, https://github.com/Mbed-TLS/mbedtls/pull/9612, https://github.com/Mbed-TLS/mbedtls/pull/9633, https://github.com/Mbed-TLS/mbedtls/pull/9634, https://github.com/Mbed-TLS/mbedtls/pull/9654).

## PR checklist

- [x] **changelog** provided
- [x] **development PR** here
- [x] **framework PR** not required
- [x] **3.6 PR** not required because: new stuff
- [x] **2.28 PR** not required because: new stuff
- **tests**  provided

### CODE REVIEW

**Review by mpg — COMMENTED** [review]
Looks good to me except it doesn't do exactly what it says on the tin: now `USE_PSA` is enabled by default, but could still be disabled - either explicitly, or just by failing to define it when using a custom config.

Reading the PR's title, I would have expected something like removing `USE_PSA` from `mbedtls_config.h` and then defining it unconditionally in `config_adjust_legacy_crypto.h` for example. Reading the issue's description only re-inforced that impression.

**Comment by gilles-peskine-arm** [comment]
> Looks good to me except it doesn't do exactly what it says on the tin: now USE_PSA is enabled by default, but could still be disabled - either explicitly, or just by failing to define it when using a custom config.

That's a good point. This accomplishes the _title_ of #9630: we're no longer building code that's guarded by `!defined(MBEDTLS_USE_PSA_CRYPTO)`. But it doesn't reach the definition of done of #9630, which says “`MBEDTLS_USE_PSA_CRYPTO` is no longer a selectable option in mbedtls_config.h`”.

I think this is a useful milestone, which has passed the CI and which you've reviewed. After this, we no longer have to worry about the non-use-PSA code paths in test code and test scripts. So I propose to declare this as a step towards #9630, and make a follow-up that fully resolves #9630. After that follow-up, we'll no longer have to worry about accidentally not enabling `MBEDTLS_USE_PSA_CRYPTO`.

The follow-up will need to take care of test scripts that query `MBEDTLS_USE_PSA_CRYPTO`, since that will no longer be a public option covered by `query_compile_time_config`. So there'll at least be some code to remove in `ssl-opt.sh`.

**Review by mpg — APPROVED** [review]
Approving now, considering https://github.com/Mbed-TLS/mbedtls/pull/9614#issuecomment-2434904761

**Comment by gilles-peskine-arm** [comment]
Uh, I clearly made some mistake in a rebase. [Originally](https://github.com/gilles-peskine-arm/mbedtls/tree/use_psa_crypto-always_on-1) this branch had no `unset MBEDTLS_USE_PSA_CRYPTO` in `components-*.sh`, but now there are some. I don't think that the current state is a useful milestone: my intent here was that we would never do a CI run with `MBEDTLS_USE_PSA_CRYPTO` disabled (except possibly in configurations with only low-level crypto). I'm going to fix that.

**Comment by gilles-peskine-arm** [comment]
So I just accidentally dropped one commit in a rebase. It still applies cleanly so here goes.

**Review by mpg — APPROVED** [review]
LGTM

**Comment by mpg** [comment]
Looking at the outcomes file:
```
% grep 'Config: !MBEDTLS_USE_PSA_CRYPTO;PASS' outcomes.csv 
Linux-x86_64;component_test_ccm_aes_sha256;test_suite_config.mbedtls_boolean;Config: !MBEDTLS_USE_PSA_CRYPTO;PASS;
Linux-x86_64;component_test_tfm_config_as_is;test_suite_config.mbedtls_boolean;Config: !MBEDTLS_USE_PSA_CRYPTO;PASS;
```
The first one has nothing that's affected by `USE_PSA` so it's OK. The 2nd one is out of our control, but FWIW it doesn't seem to have anything that would be affected by `USE_PSA` either.

**Review by yanesca — APPROVED** [review]
LGTM.

(API break check expected to fail as the PR turns USE_PSA_CRYPTO on in the default configuration.)

**Pull request merged**
