### PR TITLE
Replace MBEDTLS_ECP_HAVE_SECP521R1 with PSA_WANT_ECC_SECP_R1_521

### LINKED ISSUE #9330: Replace `MBEDTLS_ECP_HAVE_SECP*R1`  with its `PSA_WANT` counterparts
Replace these macros:
- `MBEDTLS_ECP_HAVE_SECP192R1` to `PSA_WANT_ECC_SECP_R1_192`
- `MBEDTLS_ECP_HAVE_SECP224R1` to `PSA_WANT_ECC_SECP_R1_224`
- `MBEDTLS_ECP_HAVE_SECP256R1` to `PSA_WANT_ECC_SECP_R1_256`
- `MBEDTLS_ECP_HAVE_SECP384R1` to `PSA_WANT_ECC_SECP_R1_384`
- `MBEDTLS_ECP_HAVE_SECP512R1` to `PSA_WANT_ECC_SECP_R1_512`

The macros should be replaced in all files except `mbedtls_config.h`, `cneck_config.h` and `config_adjust_*.h`.

Ensure that the test are run in the same way.

### PR DESCRIPTION
**Pull request by eleuzi01**
## Description

Partially resolves #9330 

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required, internal changes
- [x] **3.6 backport** not required, needed for 4.0
- [x] **2.28 backport** not required, needed for 4.0
- [x] **tests** not required

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

### CODE REVIEW

**Review by sezrab — APPROVED** [review]
LGTM

**Review by gabor-mezei-arm — APPROVED** [review]
LGTM

**Comment by gilles-peskine-arm** [comment]
There's a conflict now.

**Review by gabor-mezei-arm — APPROVED** [review]
LGTM

**Review by sezrab — APPROVED** [review]
LGTM

**Pull request merged**
