### PR TITLE
Backport 3.6: Add MD5 support for requires_hash_alg

### PR DESCRIPTION
**Pull request by sezrab**
Trivial backport of #9290 

## PR checklist

- [x] **changelog** not required
- [x] **3.6 backport** of #9290 
- [x] **2.28 backport** not required
- [x] **tests** not required

### CODE REVIEW

**Comment by gilles-peskine-arm** [comment]
This is missing the changes in `ssl-opt.sh`.

**Comment by gilles-peskine-arm** [comment]
The actual bug fix is still missing.

**Review by gilles-peskine-arm — APPROVED** [review]
LGTM

**Review by eleuzi01 — APPROVED** [review]
LGTM

**Pull request merged**
