### PR TITLE
Hide unnecessarily public functions in SHA-256 and SHA-512 A64 acceleration

### LINKED ISSUE #5752: SHA512/256 build fail   on arm64 PC
### Summary
This issue is found in Arm64 PC. To run ` all.sh` in aarch64 ubuntu 20.04, it reports sha512/256 error.

- By default, `./tests/scripts/all.sh build_psa_accel_alg_sha*` will report compiler options error.
   - And I check `all.sh` , I did not found any  `aarch64-linux-gnu` cross compile test . I think the test coverage is not enough. we should add `aarch64-linux-gnu` cross compiler, and add tests for it.

- Test command: `./tests/scripts/all.sh build_no_std_function`, it reports below error. With `-march=armv8.2-a+sha3+crypto`
```
/home/haoyu01/work/mbedtls/mbedtls/library/sha512.c:530:5: error: no previous prototype for 'mbedtls_internal_sha512_process_a64_crypto' [-Werror=missing-prototypes]
  530 | int mbedtls_internal_sha512_process_a64_crypto( mbedtls_sha512_context *ctx,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/haoyu01/work/mbedtls/mbedtls/library/sha512.c:548:5: error: no previous prototype for 'mbedtls_internal_sha512_process_c' [-Werror=missing-prototypes]
  548 | int mbedtls_internal_sha512_process_c( mbedtls_sha512_context *ctx,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/haoyu01/work/mbedtls/mbedtls/library/sha512.c:679:5: error: no previous prototype for 'mbedtls_a64_crypto_sha512_has_support' [-Werror=missing-prototypes]
  679 | int mbedtls_a64_crypto_sha512_has_support( void )
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

- Test command : `./tests/scripts/all.sh check_names --force` report below errors. With `-march=armv8.2-a+sha3+crypto`
```
All symbols in header: FAIL

    > 'mbedtls_a64_crypto_sha512_has_support' was found as an available symbol
      in the output of nm, however it was not declared in any header files.
    > 'mbedtls_internal_sha512_process_a64_crypto' was found as an available
      symbol in the output of nm, however it was not declared in any header
      files.
    > 'mbedtls_internal_sha512_process_c' was found as an available symbol in
      the output of nm, however it was not declared in any header files.
```

### System information

Mbed TLS version (number or commit id): 09dc05b880b1b32972bf1052b558dbc0aaca92db
Operating system and version: ubuntu 20.04 
Machine ARCH: Arm64

### Expected behavior
Test PASS

### Actual behavior
Test Fail

### Additional information
To add `-march=armv8.2-a+sha3+crypto` with below patch.
```diff
diff --git a/include/mbedtls/build_info.h b/include/mbedtls/build_info.h
index 3dd944c76..8d4830d91 100644
--- a/include/mbedtls/build_info.h
+++ b/include/mbedtls/build_info.h
@@ -80,6 +80,9 @@
 #if defined(MBEDTLS_PSA_CRYPTO_CONFIG)
 #include "mbedtls/config_psa.h"
 #endif
+#if defined(__aarch64__)
+#pragma GCC target ("arch=armv8.2-a+sha3+crypto")
+#endif
 
 #include "mbedtls/check_config.h"
```

### PR DESCRIPTION
**Pull request by tom-cosgrove-arm**
Fixes #5752

### CODE REVIEW

**Comment by tom-cosgrove-arm** [comment]
This is purely to shut the compiler up when compiling with `-Wmissing-prototypes`. `mbedtls_a64_crypto_sha512_has_support()` doesn't need to be public, so I've made it static to match `mbedtls_a64_crypto_sha256_has_support()`.

The other functions can end up `#define`d to be the public "process" functions, so I've put the prototypes just in front of them, rather that in a header. Where they are defined to the public "process" functions, there will be two prototypes - one in the header, the other will be this new one. However, multiple prototypes is safe, and this is actually much simpler than only doing it when absolutely necessary.

**Review by yuhaoth — CHANGES_REQUESTED** [review]
looks good to fix `check_names` and `build_no_std_function` fail on Arm64 HOST.

And could we add target pragma into right place. So we can run  tests without change anything.
```
#if defined(__aarch64__)
#pragma GCC target ("arch=armv8.2-a+sha3+crypto")
#endif
 ```

**Comment by tom-cosgrove-arm** [comment]
> looks good to fix `check_names` and `build_no_std_function` fail on Arm64 HOST.
> 
> And could we add target pragma into right place. So we can run tests without change anything.
> 
> ```
> #if defined(__aarch64__)
> #pragma GCC target ("arch=armv8.2-a+sha3+crypto")
> #endif
> ```

This is only necessary if you want the A64 acceleration, and may be actually wrong e.g. if someone is building for something like RPi which doesn't have crypto extensions. So no, I don't think we should do this.

**Comment by yuhaoth** [comment]
> 
> This is only necessary if you want the A64 acceleration, and may be actually wrong e.g. if someone is building for something like RPi which doesn't have crypto extensions. So no, I don't think we should do this.

I mean replace `#      error "Must use minimum -march=armv8.2-a+sha3 for MBEDTLS_SHA512_USE_A64_CRYPTO_*"` with pragma, not always set it.

Otherwise, I think we should fix `build_psa_acce*` fail  in `tests/scripts/all.sh` . we should check the compiler target and modify CFLAGS

**Comment by tom-cosgrove-arm** [comment]
> I mean replace `# error "Must use minimum -march=armv8.2-a+sha3 for MBEDTLS_SHA512_USE_A64_CRYPTO_*"` with pragma, not always set it.

Ah sorry, I misunderstood.

But the original design (reviewed and approved) was that the user would need to specify the exact arch flags, and I still think that is the correct thing to do - the user might want a greater architecture. Or the user might need a lower architecture, have set these flags, and so quietly building for something that might not work on the target systems is wrong. So failing if not set is the right thing to do.

And yes, it means when changing builds, flags need to be set - I needed to do that in `all.sh` during the original PR.

**Comment by yuhaoth** [comment]
> But the original design (reviewed and approved) was that the user would need to specify the exact arch flags, and I still think that is the correct thing to do - the user might want a greater architecture. Or the user might need a lower architecture, have set these flags, and so quietly building for something that might not work on the target systems is wrong. So failing if not set is the right thing to do.
> 

That's point I want to confirm. My suggestion will hide the details for compiler setting. User might not notify the difference of target. But easy to use :). 

> And yes, it means when changing builds, flags need to be set - I needed to do that in `all.sh` during the original PR.

Should I create a new issue? If yes, I will approve this PR.

**Review by tom-daubney-arm — APPROVED** [review]
Agree with the use of static here. Looks like a sensible addition to the existing code.

LGTM

**Review by yuhaoth — APPROVED** [review]
LGTM

**Pull request merged**
