### PR TITLE
Improve write supported group ext

### PR DESCRIPTION
**Pull request by ronald-cron-arm**
Follow-up of #7627.

### CODE REVIEW

**Comment by mpg** [comment]
@ronald-cron-arm https://confluence.arm.com/display/BSGSoftware/Git+Recipes-Mbed+Crypto#GitRecipesMbedCrypto-Iwantcodestyletobecheckedautomatically ;)

**Review by mpg — DISMISSED** [review]
Looks good to me, thanks for improving this!

**Comment by ronald-cron-arm** [comment]
Following the merge of #7627, I've rebased and fixed the coding style issues.

**Review by mpg — DISMISSED** [review]
LGTM!

**Comment by mprse** [comment]
Unfortunately CI is unhappy. 

`depends.py` fails for `!MBEDTLS_ECP_C` build and two other configurations have strange error: `undefined reference to PSA_TO_MBEDTLS_ERR`.

**Comment by mprse** [comment]
It looks like the same problem was in my PR, so maybe this is general problem on development branch?

Fix in my PR: https://github.com/Mbed-TLS/mbedtls/pull/7858/commits/9de101d1df98f621eb2bc5d8d3f86ef129941d51

**Comment by mpg** [comment]
See https://github.com/Mbed-TLS/mbedtls/pull/7870 - this broke the nightly CI. Let's get 7870 merged quickly, then we can rebase both PRs on top of the fix.

**Comment by ronald-cron-arm** [comment]
I've just rebased following the merge of #7870.

**Comment by mprse** [comment]
The review wasn't invalidated, by force push?

**Comment by gilles-peskine-arm** [comment]
> The review wasn't invalidated, by force push?

Huh, that's strange. It's [supposed to](https://github.com/Mbed-TLS/mbedtls/settings/branch_protection_rules/5026).

**Comment by ronald-cron-arm** [comment]
Yes that's strange. Hopefully it was just an one-off.

**Review by mprse — APPROVED** [review]

**Review by mpg — APPROVED** [review]

**Pull request merged**
