### PR TITLE
Switch to new code style: development

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Switch the code to the new code style. `all.sh check_code_style` will enforce the coding style during CI.

This branch was obtained by running [`update-code-style-preview-branches.sh development`](https://github.com/Mbed-TLS/mbedtls/pull/6758).

## Gatekeeper checklist

- [x] **changelog** no (should we?)
- [x] **backport** https://github.com/Mbed-TLS/mbedtls/pull/6908
- [x] **tests** [release job](https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-new/805/) → PASS

### CODE REVIEW

**Review by davidhorstmann-arm — APPROVED** [review]
Checked as follows:
- Reproduced manually from `development` and checked that there is no difference.
- Checked that the `all.sh` change is correct.
- Some spot checks on corrected files.

LGTM

**Comment by tom-cosgrove-arm** [comment]
As a user, I go to read some of the headers and WTF? it all looks different... but nothing in the ChangeLog?

**Comment by gilles-peskine-arm** [comment]
pr-head failed on OpenCI, that's an infrastructure problem. We have a full CI pass on the internal CI so CI is ok.

**Comment by gilles-peskine-arm** [comment]
I'm thinking maybe we should have a changelog entry under “Changes”. And possibly update `CONTRIBUTING.md`. But let's do this in a follow-up PR, so we don't have to do another round of CI on this one.

**Comment by daverodgman** [comment]
Confirmed the set of files in the tree is a match. Confirmed that compiling the library result in identical output (via objdump -D). Spot-checks look good.

LGTM.

**Review by daverodgman — APPROVED** [review]

**Pull request merged**
