### PR TITLE
Replace MBEDTLS_SSL_HAVE_CAMELLIA with PSA_WANT_KEY_TYPE_CAMELLIA

### LINKED ISSUE #9334: Replace legacy key type macros with its `PSA_WANT` counterparts
Replace these macros:
- `MBEDTLS_SSL_HAVE_AES` to `PSA_WANT_KEY_TYPE_AES`
- `MBEDTLS_SSL_HAVE_ARIA` to `PSA_WANT_KEY_TYPE_ARIA`
- `MBEDTLS_SSL_HAVE_CAMELLIA` to `PSA_WANT_KEY_TYPE_CAMELLIA`

The macros should be replaced in all files except `mbedtls_config.h`, `cneck_config.h` and `config_adjust_*.h`.

Ensure that the test are run in the same way.

### PR DESCRIPTION
**Pull request by eleuzi01**
## Description

Partially resolves #9334 

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required, internal changes
- [x] **3.6 backport** not required, needed for 4.0
- [x] **2.28 backport** not required, needed for 4.0
- [x] **tests** not required

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

### CODE REVIEW

**Comment by gabor-mezei-arm** [comment]
The `MBEDTLS_SSL_HAVE_CAMELLIA` macro should not to be removed.

**Comment by mpg** [comment]
The design discussion has been resolved, see https://github.com/Mbed-TLS/mbedtls/issues/9335#issuecomment-2251107614

**Review by gabor-mezei-arm — APPROVED** [review]
LGTM

**Review by gabor-mezei-arm — DISMISSED** [review]
LGTM

**Review by gabor-mezei-arm — APPROVED** [review]
LGTM

**Review by sezrab — APPROVED** [review]
LGTM

**Pull request merged**
