### PR TITLE
Backport 3.6: Test cases not executed: switch to enforcement mode

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Switch the test coverage analysis in `analyze_outcomes.py` to enforcement mode. In other words, the CI will now complain if there is a test case that is not executed in any configuration. Legitimate exceptions can be recorded in the script.

This is a backport of https://github.com/Mbed-TLS/mbedtls/pull/9593. Most commits are cherry-picked, but there are a few differences due to how development has already diverged from 3.6.

## PR checklist

- [x] **changelog** not required because: test only
- [x] **development PR** provided #9593
- [x] **framework PR** provided Mbed-TLS/mbedtls-framework#58
- [x] **3.6 PR** here
- [x] **2.28 PR** not required because: too late in the lifetime of 2.28 to bother
- **tests**  provided

### CODE REVIEW

**Review by yanesca — APPROVED** [review]
The new commits look good to me and the rest is faithful backport of the original.

**Review by paul-elliott-arm — APPROVED** [review]
LGTM

**Review by yanesca — APPROVED** [review]
LGTM.

**Review by paul-elliott-arm — DISMISSED** [review]
LGTM

**Review by yanesca — APPROVED** [review]
Did the merge locally and arrived at the same result.

**Review by paul-elliott-arm — APPROVED** [review]
LGTM

**Pull request merged**
