### PR TITLE
Fix NULL argument handling in mbedtls_xxx_free() functions

### LINKED ISSUE #8915: mbedtls_entropy_free not checking for NULL context
Hi,

I am using mbedtls-3.5.2. Every mbedtls_XXX_free() API function I came across checks for NULL parameter (just like `free()` does), however, `mbedtls_entropy_free` does not. Is there a reason for this?

In my code both the client and server share the same dynamically allocated ctr_drbg and entropy structs (not sure if this is the correct approach though). At the end of a session both of them try to free these structs and whoever does first sets them to NULL, which works well with `mbedtls_ctr_drbg_free()`, but not as much with `mbedtls_entropy_free()`. That is where I ran into this issue.

### PR DESCRIPTION
**Pull request by Troy-Butler**
## Description

Added conditional statements to mbedtls_xxx_free() functions to handle NULL arguments.
Resolves #8915.

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required
- [x] **backport** not required, but could be done for 3.6
- [x] **tests** not required

### CODE REVIEW

**Comment by gilles-peskine-arm** [comment]
Please amend the commit message to contain a signoff line (`git commit -a -s` will help you), to [indicate that you legally agree to contribute under the Mbed TLS license](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md#license-and-copyright).

**Comment by Troy-Butler** [comment]
I apologize for my delayed response. I've made the requested changes.

**Comment by gilles-peskine-arm** [comment]
Please don't include unrelated commits in a pull request, this makes it hard to review. You seem to have started on top of a pull request rather than the `development` branch. You can fix that with
```
git rebase development~1 --onto origin/development development
```
assuming that your local branch is called `development`. (Tip: don't do anything on the `development` branch, always pick a branch name related to your work, e.g. `git checkout -b handle-null-arguments`. Unfortunately, for this time, you can't rename the branch of a pull request on GitHub.)

**Comment by gilles-peskine-arm** [comment]
> I've rebased as requested.

Maybe, but not pushed...

**Comment by Troy-Butler** [comment]
When I attempt to push, I am told "Everything up-to-date"

**Comment by gilles-peskine-arm** [comment]
Please make sure that you've successfully rebased: `git show -s HEAD~1` should be a merge commit.

**Comment by Troy-Butler** [comment]
I received a success response when I rebased, but git show does not indicate a merge commit. This is becoming more and more of a mess, so at this point, I think the best course of action is for me to close this pull request and start again.

**Pull request closed without merging**
