### PR TITLE
Clean up curves handling in libtestdriver1 config

### LINKED ISSUE #8274: Clean up curves handling in libtestdriver1 config
Currently curves are handled in a special way in `tests/include/test/drivers/config_test_driver.h`. As a consequence, they also seem to require special handling in each `all.sh` that accelerates, like [here](https://github.com/Mbed-TLS/mbedtls/blob/b51f3da3549034818ea5e7b66695a44c65454cbc/tests/scripts/all.sh#L2317) for example. Furthermore, it doesn't look like anyone clearly understands why things are this way.

This task is to either:
1. Fix handling of curves in libtestdriver1 config so that it's more uniform with other ACCEL macros, and no longer require special treatment in `all.sh` components that accelerate ECC.
2. Or if it can't seem to be done, document clearly why this special handling is needed.

### PR DESCRIPTION
**Pull request by valeriosetti**
## Description

This PR solves disparity in management of accelerate curves in `libtestdriver1` builds.

Resolves #8274

## PR checklist

- [x] **changelog** not required as it's only for internal testing purposes only
- [x] **backport** not required
- [x] **tests** provided: components in `all.sh` were modified in order to rely on the new implementation

### CODE REVIEW

**Comment by valeriosetti** [comment]
I don't think that the error reported by the CI (ABI-API break) really belongs to this PR:
```
[2023-10-30T11:27:37.770Z] <removed_symbols>
[2023-10-30T11:27:37.770Z]   <header name="psa_crypto_cipher.c">
[2023-10-30T11:27:37.770Z]     <library name="libmbedcrypto.so.15">
[2023-10-30T11:27:37.770Z]       <name>mbedtls_cipher_values_from_psa</name>
[2023-10-30T11:27:37.770Z]     </library>
[2023-10-30T11:27:37.770Z]   </header>
[2023-10-30T11:27:37.770Z] </removed_symbols>
```
Isn't it?

**Comment by gilles-peskine-arm** [comment]
The ABI break is indeed unrelated. I think (but haven't checked thoroughly) that it's an instance of https://github.com/Mbed-TLS/mbedtls-test/issues/37.

**Review by mpg — CHANGES_REQUESTED** [review]
I'm happy with the changes that are there, but I think one thing's missing: in `common_test_psa_crypto_config_accel_ecc_some_curves()` on line 2612 we still have
```
    helper_libtestdriver1_make_main "$loc_accel_list $loc_curve_list"
```
I think we should no longer have `loc_curve_list` here. (It's not harmful technically, but it might give a wrong impression to readers.)

**Comment by valeriosetti** [comment]
> I'm happy with the changes that are there, but I think one thing's missing: in `common_test_psa_crypto_config_accel_ecc_some_curves()` on line 2612 we still have
> 
> ```
>     helper_libtestdriver1_make_main "$loc_accel_list $loc_curve_list"
> ```
> 
> I think we should no longer have `loc_curve_list` here. (It's not harmful technically, but it might give a wrong impression to readers.)

I'm sorry, this is definitely a leftover. I will remove it ;)

**Review by mpg — APPROVED** [review]
LGTM

**Review by d3zd3z — APPROVED** [review]

**Pull request merged**
