### PR TITLE
Enable explicit_bzero() on OpenBSD

### PR DESCRIPTION
**Pull request by tom-cosgrove-arm**
## Gatekeeper checklist

- [x] **changelog** not required
- [x] **backport** not required
- [x] **tests** not required

### CODE REVIEW

**Comment by daverodgman** [comment]
On balance I'm OK with dropping the version check discussed in #7173 https://github.com/Mbed-TLS/mbedtls/pull/7173#discussion_r1124749036 - but also don't see any particular reason not to use it? Any good justifications either way?

**Comment by tom-cosgrove-arm** [comment]
Yes, tested on latest OpenBSD

**Comment by tom-cosgrove-arm** [comment]
... and to explicitly confirm that OpenBSD still gets `gmtime_r()`

**Comment by tom-cosgrove-arm** [comment]
> On balance I'm OK with dropping the version check discussed in #7173 (comment) - but also don't see any particular reason not to use it?

OpenBSD added `explicit_bzero()` nearly a decade ago (OpenBSD 5.5, released May 1, 2014). OpenBSD generally only supports releases for a year, so anyone using a version of OpenBSD without `explicit_bzero()` is using "very unsupported" software, and could just use the 2.28 LTS.

I don't see the point in adding a check for approximately 0 users, that involves having to include another header (sys/param.h)

**Comment by gilles-peskine-arm** [comment]
In https://github.com/Mbed-TLS/mbedtls/pull/7173#discussion_r1124656359, I wasn't worried about ancient OpenBSD. I was worried about builds with some standard-compliance symbol defined (like `_POSIX_C_SOURCE`).

**Pull request merged**
