### PR TITLE
Introduce mbedtls_test_read_mpi_core

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Introduce `mbedtls_test_read_mpi_core`. Broken out of https://github.com/Mbed-TLS/mbedtls/pull/6303 by demand.

Changelog: no (test only)

Backport: for the commits that aren't about `mbedtls_test_read_mpi_core` — https://github.com/Mbed-TLS/mbedtls/pull/6387

Possible alternative: https://github.com/Mbed-TLS/mbedtls/pull/6398 (continues this pull request and adds extra commits)

### CODE REVIEW

**Review by yanesca — APPROVED** [review]
Have a minor suggestion, but other than that it looks good to me.

**Review by yanesca — APPROVED** [review]
LGTM

**Review by gabor-mezei-arm — APPROVED** [review]
LGTM

**Comment by yanesca** [comment]
@gilles-peskine-arm shall we merge this, or would you like to put up a backport first?

**Comment by gilles-peskine-arm** [comment]
The (partial) backport is up for review and linked in the PR description.

**Pull request merged**
