### PR TITLE
Backport 3.6: Report configuration settings in the outcome file

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Trivial backport of https://github.com/Mbed-TLS/mbedtls/pull/9172

## PR checklist

- [x] **changelog** no (test only)
- [x] Backport of https://github.com/Mbed-TLS/mbedtls/pull/9172
- [x] Framework: https://github.com/Mbed-TLS/mbedtls-framework/pull/28
- [x] **tests** provided

### CODE REVIEW

**Review by ronald-cron-arm — APPROVED** [review]
I've checked the rebase of #9172 on top of the merge of #9289. LGTM.

**Review by paul-elliott-arm — APPROVED** [review]
LGTM

**Review by ronald-cron-arm — APPROVED** [review]
LGTM

**Review by paul-elliott-arm — APPROVED** [review]
LGTM

**Pull request merged**
