### PR TITLE
Fix invalid commands for ec_x{25519,448}_{prv,pub}.{der,pem}

### PR DESCRIPTION
**Pull request by lpy4105**
## Description

The commands in `tests/data_files/Makefile` to generate ec key files is invalid, which is introduced in #6838 

## PR checklist

- [x] **changelog** not required, internal use.
- [x] **backport** not required, new feature bug fix.
- [x] **tests** not required

### CODE REVIEW

**Review by gilles-peskine-arm — DISMISSED** [review]
LGTM

I haven't checked for completeness. Any incremental progress is good.

**Review by yuhaoth — CHANGES_REQUESTED** [review]
I perfer genkey with PEM format and output public key with PEM private key
like below
```
ec_x25519_prv.pem:
	$(OPENSSL) genpkey -algorithm X25519 -out $@ -outform PEM

ec_x25519_pub.pem: ec_x25519_prv.pem
	$(OPENSSL) pkey -in $< -out $@ \
		-pubout -inform PEM -outform PEM

ec_x25519_pub.der: ec_x25519_prv.pem
	$(OPENSSL) pkey -in $< -out $@ \
		-pubout -inform PEM -outform DER

ec_x25519_prv.der: ec_x25519_prv.pem
	$(OPENSSL) pkey -in $< -inform PEM -out $@ -outform DER
all_final += ec_x25519_prv.pem ec_x25519_pub.pem ec_x25519_prv.der ec_x25519_pub.der

ec_x448_prv.pem:
	$(OPENSSL) genpkey -algorithm X448 -out $@ -outform PEM

ec_x448_pub.pem: ec_x448_prv.pem
	$(OPENSSL) pkey -in $< -out $@ \
		-pubout -inform PEM -outform PEM

ec_x448_pub.der: ec_x448_prv.pem
	$(OPENSSL) pkey -in $< -out $@ \
		-pubout -inform PEM -outform DER

ec_x448_prv.der: ec_x448_prv.pem
	$(OPENSSL) pkey -in $< -inform PEM -out $@ -outform DER
all_final += ec_x448_prv.pem ec_x448_pub.pem ec_x448_prv.der ec_x448_pub.der
```

**Comment by gilles-peskine-arm** [comment]
> I perfer genkey with PEM format and output public key with PEM private key

Why?

We want all test keys in DER format, because some builds don't support PEM and we still want to test them. In addition, we have some keys in PEM format to test support, and we have some keys in PEM format just because historically we created them in PEM.

So it would be better to generate all keys in DER format, and then do a DER→PEM conversion if we also want the PEM.

So I prefer d1200ee2e88c18cfd464ccb6feee202b5060e988 to cfd0b20fd3da8cc93420e49937eef815b24d8f19. cfd0b20fd3da8cc93420e49937eef815b24d8f19 seems to be moving backwards.

**Review by yuhaoth — DISMISSED** [review]
LGTM

**Comment by yuhaoth** [comment]
> Why?

`PEM` is text format and friendly for `git diff` . 
It include file type header, we can know the type directly.

> 
> We want all test keys in DER format, because some builds don't support PEM and we still want to test them. In addition, we have some keys in PEM format to test support, and we have some keys in PEM format just because historically we created them in PEM.

I do not know that. And I do not like commit a binary file into git repo if possible.

**Comment by gilles-peskine-arm** [comment]
> friendly for git diff

It's base64, so not really.

> It include file type header, we can know the type directly.

I don't see how that's useful. We already know what's a key/cert/CRL/... from the file name.

> I do not like commit a binary file into git repo if possible.

We need the DER files anyway.

**Comment by yuhaoth** [comment]
>We already know what's a key/cert/CRL/... from the file name.

Then we should cleanup the filenames. I found we can not get the type from filename. 

>>  I do not like commit a binary file into git repo if possible.

> We need the DER files anyway.

That's my personal habit. let‘s change the files to DER if PEM is not used.

**Comment by lpy4105** [comment]
Delete https://github.com/Mbed-TLS/mbedtls/commit/cfd0b20fd3da8cc93420e49937eef815b24d8f19 and add one more commit (https://github.com/Mbed-TLS/mbedtls/pull/7670/commits/21e5939479648453d787badb560f014730e090e6) to generate PEM pub key files directly from DER prv key files.

**Review by yuhaoth — APPROVED** [review]
LGTM

**Pull request merged**
