### PR TITLE
Bignum: Must call mbedtls_mpi_mod_modulus_init() before anything else in tests

### PR DESCRIPTION
**Pull request by tom-cosgrove-arm**
Fixes (new) Coverity issues 381893 and 381894

## Gatekeeper checklist

- [ ] **changelog** not required - part of tests
- [ ] **backport** not required - this is in new test code
- [ ] **tests** - fixing tests

### CODE REVIEW

**Review by yanesca — APPROVED** [review]
LGTM.

**Review by wernerlewis — APPROVED** [review]
LGTM

**Review by minosgalanakis — APPROVED** [review]
LGTM (Open CI is not working)

**Comment by tom-cosgrove-arm** [comment]
CI has passed except for OpenCI with "Scripts not permitted to use method hudson.model.Run getParent"

**Pull request merged**
