### PR TITLE
Fix zeroization at NULL pointer

### LINKED ISSUE #6516: When mbedtls_calloc returns NULL in tls_prf_generic then segmentation fault occurs
### Summary

When mbedtls_calloc at https://github.com/Mbed-TLS/mbedtls/blob/development/library/ssl_tls.c#L5579 returns NULL the code goes to the exit label. In the exit section the code calls mbedtls_zeroize https://github.com/Mbed-TLS/mbedtls/blob/development/library/ssl_tls.c#L5638 which then writes zeroes near address NULL.

I was doing some systematic injection of malloc errors that's why I came across this issue. I produced the error using mbedtls 2.28.1 but the issue is also in the development branch.

### System information

Mbed TLS version (number or commit id): 
Operating system and version: 
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information:

### PR DESCRIPTION
**Pull request by daverodgman**
Fixes #6516

Backport: #6523 
Changelog: yes, present

### CODE REVIEW

**Comment by tom-cosgrove-arm** [comment]
Should this have a non-regression test?

**Comment by daverodgman** [comment]
> Should this have a non-regression test?

I was thinking not - it would be very difficult to test, and it is not very likely to regress. It does need a Changelog though.

**Comment by daverodgman** [comment]
Actually, isn't this dead code? It's only used by TLS 1.0 and 1.1, which we don't support?

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Review by paul-elliott-arm — APPROVED** [review]
LGTM

**Comment by daverodgman** [comment]
Internal CI is happy except for an unrelated CI issue on Windows 2013

**Pull request merged**
