### PR TITLE
[Backport 3.6] Fix issue in handling legacy_compression_methods in ssl_tls13_parse_client_hello()

### PR DESCRIPTION
**Pull request by waleed-elmelegy-arm**
## Description

Please write a few sentences describing the overall goals of the pull request's commits.
backports #9244 

## PR checklist

Please remove the segment/s on either side of the | symbol as appropriate, and add any relevant link/s to the end of the line.
If the provided content is part of the present PR remove the # symbol.

- [X] **changelog** provided | not required because: 
- [X] **development PR** provided #9244 
- [X] **framework PR** not required
- [X] **3.6 PR** not required because: This is it
- [X] **2.28 PR** not required because: (feature not in 2.28)
- [X] **tests**  provided

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

### CODE REVIEW

**Review by gilles-peskine-arm — APPROVED** [review]
Approved as a trivial backport

**Review by minosgalanakis — APPROVED** [review]
LGTM, faithfull backport.

**Review by tom-cosgrove-arm — DISMISSED** [review]
Faithful backport

**Review by minosgalanakis — DISMISSED** [review]
LGTM

**Review by gilles-peskine-arm — APPROVED** [review]
LGTM

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM, faithful backport + capitalisation fix :)

**Pull request merged**
