### PR TITLE
Force MBEDTLS_USE_PSA_CRYPTO enabled

### LINKED ISSUE #9630: Always build with MBEDTLS_USE_PSA_CRYPTO enabled
The goal of this issue is to always have `MBEDTLS_USE_PSA_CRYPTO` enabled no matter how the library is built.

Definition of done: `MBEDTLS_USE_PSA_CRYPTO_ENABLED` is no longer a selectable option in `mbedtls_config.h`, but an internal symbol that is auto-enabled during a transition period.

Any reduction in test coverage should be justified.

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Resolve #9630.

There are still builds with `MBEDTLS_PSA_CRYPTO_CLIENT` disabled, when we're only building some low-level crypto.

Continues https://github.com/Mbed-TLS/mbedtls/pull/9614.

## PR checklist

- [x] **changelog** not required because: already announced in https://github.com/Mbed-TLS/mbedtls/pull/9614
- [x] **development PR** here
- [x] **framework PR** not required
- [x] **3.6 PR** not required because: new stuff
- [x] **2.28 PR** not required because: new stuff
- **tests**  provided

### CODE REVIEW

**Comment by minosgalanakis** [comment]
Thanks for this pr.  

I was wondering what happens with builds that override the default config such as `config-symmetric-only.h` -> [link ](https://github.com/Mbed-TLS/mbedtls/blob/development/tests/scripts/components-configuration-crypto.sh#419) or some of the other [hardcoded configs](https://github.com/Mbed-TLS/mbedtls/tree/development/configs)

Does the change in [config_adjust_legacy_crypto.h](https://github.com/Mbed-TLS/mbedtls/pull/9727/files#diff-c3f397e69bbaf729daf8c1867565bc10984fbdc5dd2ee9219bd777a49057bdc0) propage as a default when the files are being overriden? Are those hardcoded uses cases out of scope for now?

**Comment by gilles-peskine-arm** [comment]
@minosgalanakis I'm sorry, I don't understand your question. `MBEDTLS_USE_PSA_CRYPTO` is now always defined after including `mbedtls/build_info.h`, regardless of what happens in `MBEDTLS_CONFIG_FILE` or `PSA_CRYPTO_CONFIG_FILE`. This may require a further change to the `*adjust*` files ensure that it's defined after including `tf-psa-crypto/build_info.h`. This has nothing to do with how the config is constructed though, so I'm not sure if that's what you're asking about?

**Comment by minosgalanakis** [comment]
@gilles-peskine-arm thanks for clarifying that, you answered my question. 

Yes basically I was wondering how global this change is, and which other configuratoins may need to manually adjusted.

**Review by yanesca — APPROVED** [review]
LGTM

**Comment by gilles-peskine-arm** [comment]
@yanesca We don't need the validation from OpenCI, but GitHub won't let us merge until it passes. So I've started a new job.

**Pull request merged**
