### PR TITLE
Allow auto-generation of library/certs.c from tests/data_files

### PR DESCRIPTION
**Pull request by hanno-arm**
__Summary:__ This PR annotates the hardcoded test certificates and keys in `library/certs.c` with a formal comment syntax describing their type and origin in `tests/data_files`, and adds a script `scripts/generate_certs.sh` which parses these comments and updates the hardcoded data. This aims to simplify the synchronization of `tests/data_files` with `library/certs.c` as well as the addition of new test data. This was suggested by @AndrzejKurek in #2260.

This is based on #2260.

### CODE REVIEW

**Comment by hanno-arm** [comment]
@mpg @gilles-peskine-arm What's your view on this PR? As it stands, every modification of CRT or key files is prone to introduce a mismatch between `library/certs.c` and `tests/data_files`, and this PR is a way to detect this, and to automatically keep both in sync. I'm aware that the script I've written isn't optimal, and I'm sure @gilles-peskine-arm would be able to come up with something much better, but considering that we're short on time and debating our engagement even in much more important problems such as #3564, I wonder if it's worth taking this PR as-is and leaving improvements of the script for another time. WDYT?

**Comment by mpg** [comment]
@hanno-arm I'd be inclined to go with this script for starters. We can always rewrite in Python or otherwise later, but IMO this script is an improvement over the existing situation.

**Comment by hanno-arm** [comment]
@mpg Ok, I'll clean up and rebase this PR, then :+1:

**Comment by gilles-peskine-arm** [comment]
I like the general approach to generate `certs.c` automatically instead of manually updating it.

Please add the script to `check-generated-files.sh`.

I'd prefer for the new script to be in Python. More team members know Python than sh and the language has fewer gotchas. I'm not sure if `xxd` is even present in our CI environment. Python code would be more readable than sh. The sh script has many points of failure that would go undetected even with the addition of `set -e`, whereas python code can be relied on to exit with an uncaught exception if something unexpected happens.

**Comment by gilles-peskine-arm** [comment]
FYI this script doesn't work on 2.7 because it doesn't have “BEGIN FILE”…“END FILE” markers. That's not a big deal, just something extra to do in the backports. More concerning, running this script on mbedtls-2.7 has no effect if I use bash, but with dash, it mangles the file: `\r\n` gets turned into CRLF. I haven't investigated why, probably a non-portable use of `echo`. Yet another argument to write this in python instead of sh.

**Comment by ronald-cron-arm** [comment]
I also think it would be much better for the script to be written in Python. @hanno-arm do you think you would have time, would fancy rewriting the script in Python?

**Comment by tom-cosgrove-arm** [comment]
Closing this in favour of #5986, which does the same thing in Python

**Pull request closed without merging**
