### PR TITLE
Replace MBEDTLS_MD_CAN_SHA3_256 with PSA_WANT_ALG_SHA3_256

### PR DESCRIPTION
**Pull request by eleuzi01**
## Description

Issue #9115

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required, internal changes
- [x] **3.6 backport** not required, needed for 4.0
- [x] **2.28 backport** not required, needed for 4.0
- [x] **tests** not required

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

### CODE REVIEW

**Review by gabor-mezei-arm — APPROVED** [review]
LGTM

**Review by gabor-mezei-arm — APPROVED** [review]
LGTM

**Review by tom-daubney-arm — APPROVED** [review]
It is not clear to me why the internal CI failed here, possible timeout?

OpenCI has fully passed though so all is well.

LGTM - thanks!

**Comment by tom-daubney-arm** [comment]
Ah I found the internal CI failure: bad client exit code:
```[2024-07-02T18:59:30.524Z] Connection ID, 3D+MTU: Cli+Srv enabled, CID on renegotiation ........... FAIL
[2024-07-02T18:59:30.524Z]   ! bad client exit code (expected 0, got 1)
[2024-07-02T18:59:30.524Z]   ! outputs saved to o-XXX-124.log```

I guess this is spurious and can be ignored if the same thing passed on Open CI. @gabor-mezei-arm WDYT?

**Comment by gilles-peskine-arm** [comment]
With a bad client exit code, you need to look at the client logs for the root cause. The exit code is a secondary indication.

Maybe an instance of https://github.com/Mbed-TLS/mbedtls/issues/8471 ? Please check.

**Comment by tom-daubney-arm** [comment]
> With a bad client exit code, you need to look at the client logs for the root cause. The exit code is a secondary indication.
> 
> Maybe an instance of #8471 ? Please check.

Thanks @gilles-peskine-arm . I have downloaded the logs and will go through them in the morning.

**Comment by tom-daubney-arm** [comment]
@gilles-peskine-arm I have looked through the client logs and compared them to some log you provided in the issue #8471 . I feel fairly confident that this is an instance of #8471 : The last 20 or so lines of the client logs I am comparing are a complete match with the same error codes etc, however the logs diverge after that. 

There is a difference between the two failed components client logs in that the one from this PR uses TLS1.3 and the one you have provided does not, but I am struggling to definitively prove that the differences in the logs are due to that.

Is what I have looked at enough to say "yes this is an instance of #8471" or do I need to try and go deeper?

**Comment by gilles-peskine-arm** [comment]
> the one from this PR uses TLS1.3

That can't be right: 3D tests are about DTLS. “3D” stands for Drop/Duplicate/Delay, which are the three bad things that can happen to UDP packets and which DTLS needs to recover from. We don't implement DTLS 1.3, so these test cases can only use DTLS 1.2. (Or DTLS 1.1 in Mbed TLS 2.28.)

>  The last 20 or so lines of the client logs I am comparing are a complete match with the same error codes etc, however the logs diverge after that.

Do you mean the last 20 lines of the whole log? That's a handshake error and not terribly indicative. Or do you mean the 20 lines leading to the first sign of error? That would be more indicative that the problem is the same. Though to be fair, I don't know what the problem is. If we fully understood the failure, we would have fixed it by now. As long as the problem rises to the level of “it's intermittent, very rare, and has no obvious cause”, I'm ok with bundling it up.

**Comment by tom-daubney-arm** [comment]
> That can't be right: 3D tests are about DTLS. “3D” stands for Drop/Duplicate/Delay, which are the three bad things that can happen to UDP packets and which DTLS needs to recover from. We don't implement DTLS 1.3, so these test cases can only use DTLS 1.2. (Or DTLS 1.1 in Mbed TLS 2.28.)
> 
Sorry - that is my mistake, I misinterpreted the wording the test component that failed: `full_without_ecdhe_ecdsa_and_tls13` to mean that we are using TLS1.3 but on re-reading, we clearly aren't. 
>
> Do you mean the last 20 lines of the whole log? That's a handshake error and not terribly indicative. Or do you mean the 20 lines leading to the first sign of error? That would be more indicative that the problem is the same. Though to be fair, I don't know what the problem is. If we fully understood the failure, we would have fixed it by now. As long as the problem rises to the level of “it's intermittent, very rare, and has no obvious cause”, I'm ok with bundling it up.

And yes, I mean the handshake error part, which I agree doesn't really tell us a whole bunch. I will try and dig a bit more.

**Pull request merged**
