### PR TITLE
Mbed TLS 3.5.1

### PR DESCRIPTION
**Pull request by daverodgman**
## Description

This results in (almost) no changes to tip, but includes commit [edb8fec](https://github.com/Mbed-TLS/mbedtls/pull/8468/commits/edb8fec9882084344a314368ac7fd957a187519c) which is suitable to be released as 3.5.1

Intended changes to tip are:
- Changelog
- Changes produced by `bump_version.sh`
- BRANCHES.md
- Everest docs in `mbedtls_config.h`

Note: github shows a lot of changes that were made and then reverted by this PR - it's clearer to review this locally.

Release CI https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-new/821/

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** provided
- [x] **backport** #8469 
- [x] **tests** not required

Updated to fix missing Changelog entry.

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

### CODE REVIEW

**Review by minosgalanakis — APPROVED** [review]
LGTM. Tested it locally and verified the auto-generated files licenses too.

**Review by waleed-elmelegy-arm — DISMISSED** [review]
LGTM

**Review by minosgalanakis — APPROVED** [review]
LGTM

**Review by waleed-elmelegy-arm — APPROVED** [review]
LGTM

**Review by minosgalanakis — APPROVED** [review]
LGTM

**Pull request merged**
