### PR TITLE
[Backport 3.6] Adapt config.py to configuration file split

### PR DESCRIPTION
**Pull request by gabor-mezei-arm**
## Description

Only update framework to the version used in #9229 

## PR checklist

Please remove the segment/s on either side of the | symbol as appropriate, and add any relevant link/s to the end of the line.
If the provided content is part of the present PR remove the # symbol.

- [x] **changelog** not required because: only platform script change
- [x] **development PR** provided #9229 
- [x] **framework PR** provided Mbed-TLS/mbedtls-framework#35
- [x] **3.6 PR** not required because: this is
- [x] **2.28 PR** not required because: changes not compatible with it
- **tests**  provided

### CODE REVIEW

**Comment by ronald-cron-arm** [comment]
@gabor-mezei-arm There is a conflict with the framework. Rebasing on top of the head of 3.6 should resolve the conflict.

**Review by tom-daubney-arm — APPROVED** [review]
LGTM.

**Review by ronald-cron-arm — APPROVED** [review]
LGTM

**Review by tom-daubney-arm — APPROVED** [review]
LGTM.

**Review by ronald-cron-arm — DISMISSED** [review]

**Review by ronald-cron-arm — APPROVED** [review]
The update of the framework to the merge of https://github.com/Mbed-TLS/mbedtls/issues/35 looks good to me.

**Comment by ronald-cron-arm** [comment]
@tom-daubney-arm please have another look

**Review by tom-daubney-arm — APPROVED** [review]
LGTM.

**Pull request merged**
