### PR TITLE
Replace MBEDTLS_MD_CAN_MD5 with PSA_WANT_ALG_MD5

### PR DESCRIPTION
**Pull request by eleuzi01**
## Description

Issue #9110.

Status: blocked by https://github.com/Mbed-TLS/mbedtls/pull/9290 which fixes dependencies around a use of MD5 in test code.

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required, internal changes
- [x] **3.6 backport** not required, needed for 4.0
- [x] **2.28 backport** not required, needed for 4.0
- [x] **tests** not required

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

### CODE REVIEW

**Review by gabor-mezei-arm — APPROVED** [review]
LGTM
The CI is failing after all test have been passed.

**Comment by tom-daubney-arm** [comment]
Note that this issue is only half of the fix for #9110. We will need #9125 to be merged as well before we can close this issue.

**Review by tom-daubney-arm — APPROVED** [review]
LGTM - thanks!

Only remaining hits for `MBEDTLS_MD_CAN_MD5` are in the `include` directory and the description in #9110 says that it is not required to remove from there.

Question though: Why not just remove these hits from `check_config.h` and `config_adjust_legacy_crypto.h`? Are they being removed later? @eleuzi01 @gabor-mezei-arm

**Comment by tom-daubney-arm** [comment]
> LGTM The CI is failing after all test have been passed.

Given this comment, I am ignoring the CI failures.

**Comment by gabor-mezei-arm** [comment]
> Question though: Why not just remove these hits from `check_config.h` and `config_adjust_legacy_crypto.h`? Are they being removed later?

It will be removed later.

**Comment by gilles-peskine-arm** [comment]
There is now a genuine CI failure in outcome analysis, see the [logs](https://mbedtls.trustedfirmware.org/job/mbed-tls-pr-head/job/PR-9123-head/4/execution/node/8321/log/).

It will be fixed by https://github.com/Mbed-TLS/mbedtls/pull/9290. I suggest waiting until that is merged.

**Review by gabor-mezei-arm — APPROVED** [review]
LGTM

**Pull request merged**
