### PR TITLE
Remove symmetric crypto alt interface

### PR DESCRIPTION
**Pull request by tom-daubney-arm**
## Description

Remove symmetric crypto ALT interfaces.

This PR is made up of commits split out from #9226 in order to ease review.

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** Will be provided at end of PR series
- [x] **3.6 backport** not required
- [x] **2.28 backport** not required
- [x] **tests** existing tests suffice

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

### CODE REVIEW

**Review by ronald-cron-arm — APPROVED** [review]
LGTM, thanks.

**Review by bensze01 — DISMISSED** [review]
LGTM. Please rebase to resolve the conflicts.

**Review by ronald-cron-arm — DISMISSED** [review]
I've checked the rebase, LGTM.

**Comment by tom-daubney-arm** [comment]
@ronald-cron-arm Rebased again, this time without needing manual conflict resolution.

**Review by bensze01 — APPROVED** [review]
LGTM

**Pull request merged**
