### PR TITLE
Fix mbedtls_pk_get_bitlen for a key size that is not a multiple of 8

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Fix https://github.com/Mbed-TLS/mbedtls/issues/868.

Note that the scope is restricted to fixing `mbedtls_pk_get_bitlen()` for keys that are already supported. This pull request does not expand support for non-byte-aligned RSA keys (in particular, PSA still rejects those).

This pull request does not touch `psa_crypto_rsa.c` to avoid conflicts with https://github.com/Mbed-TLS/mbedtls/pull/8740. Follow-up once both are merged: https://github.com/Mbed-TLS/mbedtls/issues/8780.

## PR checklist

- [x] **changelog** provided
- [x] **backport** https://github.com/Mbed-TLS/mbedtls/pull/8814
- [x] **tests** provided

### CODE REVIEW

**Review by tom-cosgrove-arm — DISMISSED** [review]
LGTM

**Comment by tom-cosgrove-arm** [comment]
Bah @gilles-peskine-arm conflicts

**Comment by gilles-peskine-arm** [comment]
There were two consecutive additions. I've rebased.

**Review by tom-cosgrove-arm — DISMISSED** [review]
LGTM

**Comment by tom-cosgrove-arm** [comment]
Grr, conflicts again

**Comment by gilles-peskine-arm** [comment]
Now there were consecutive changes in `test_suite_pkparse.data`. Rebased again.

**Review by tom-cosgrove-arm — DISMISSED** [review]
LGTM

**Review by minosgalanakis — DISMISSED** [review]
LGTM. Are backports required or is that a 3X issue?

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Comment by gilles-peskine-arm** [comment]
I pushed two very small improvements that I noticed while working on the backport.

**Review by minosgalanakis — APPROVED** [review]
LGTM

**Pull request merged**
