### PR TITLE
Test accel all ciphers and aead

### LINKED ISSUE #6316: [G3] Add test component with all ciphers and AEADs accelerated only
- Add a test component that accelerates all ciphers, modes and AEADs, with as many things enabled as currently possible
- Add a reference component with a similar config and everything built-in, and coverage comparison in `analyze_outcome.py` as usual.

For this task, it is acceptable to disable as many modules as needed initially to make things build without built-in implementations of ciphers / modes / AEADs.  Adding support for new things is out of scope here, but small bugs can be fixed immediately if easy enough. It is also acceptable to ignore as much as necessary in the coverage comparison for now.

All gaps identified here will be either decided out-of-scope for this EPIC's goals, or closed by subsequent tasks to be created.

If bugs are fixed, the fixes should be backported if the bugs were also present in 2.28.

Depends on #8064

### PR DESCRIPTION
**Pull request by mpg**
This is a work-in-progress attempt to resolve #6316 - not even passing tests locally, but just pushing before I leave so that others can use it if needed. cc @ronald-cron-arm and @gilles-peskine-arm as you're working on rationalizing accelerator testing. I believe this is the first build without software AES with tests, and probably the first for a few other things since I ran into some failing test cases.

### CODE REVIEW

**Comment by gilles-peskine-arm** [comment]
> this is the first build without software AES with tests

Surely there's one since a few days ago, thanks to #6385 with `depends.py cipher_id`?

**Comment by mpg** [comment]
Sorry, meant with accelerated AES but not software AES.

**Comment by tom-cosgrove-arm** [comment]
Note that commit `1a54d2181` is unsigned, and there are conflicts

**Comment by tom-daubney-arm** [comment]
We are now converting older PRs to draft PRs where the following conditions are met: They have not been updated in the last 3 months, and they need more than non-trivial work to complete.

**Comment by mpg** [comment]
This one can be closed, I'll create a new one when the time comes.

**Pull request closed without merging**
