### PR TITLE
TLS 1.3: Adjustments for the coming release

### PR DESCRIPTION
**Pull request by ronald-cron-arm**
## Description

Some adjustments in the TLS 1.3 implementation for the coming release.

## Gatekeeper checklist

- [x] **changelog** not required
- [x] **backport** not required
- [x] **tests** not required

### CODE REVIEW

**Review by xkqian — APPROVED** [review]
LGTM

**Review by yuhaoth — DISMISSED** [review]
LGTM

**Comment by ronald-cron-arm** [comment]
@xkqian @yuhaoth I've integrated @xkqian proposal. Please have another look.

**Review by xkqian — APPROVED** [review]
LGTM

**Pull request merged**
