### PR TITLE
[Backport 3.6] Fix v3.6 issues 9186 and 9188 bp

### PR DESCRIPTION
**Pull request by minosgalanakis**
## Description

This is a backport of #9189

## PR checklist

Please remove the segment/s on either side of the | symbol as appropriate, and add any relevant link/s to the end of the line.
If the provided content is part of the present PR remove the # symbol.

- [x] **changelog** provided
- [x] **development PR** provided #9189
- [x] **framework PR** provided [#23](https://github.com/Mbed-TLS/mbedtls-framework/pull/23)
- [x] **3.6 PR** provided
- [x] **2.28 PR**  not required because: neither issue is present in 2.28 (#9186: no build failure in the given configuration and compilers; #9188: moot since PSA did not support DHM yet)
- **tests**  not required because: TBD

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

### CODE REVIEW

**Review by gilles-peskine-arm — DISMISSED** [review]
LGTM as a backport of #9189

**Review by eleuzi01 — DISMISSED** [review]
LGTM

**Review by gilles-peskine-arm — APPROVED** [review]
LGTM after submodule update

**Review by eleuzi01 — APPROVED** [review]
LGTM

**Pull request closed without merging**
