### PR TITLE
[Backport 3.6] Move test data files to framework

### PR DESCRIPTION
**Pull request by davidhorstmann-arm**
Not quite trivial backport of #9249.

One merge conflict in the following test `.data` files:
```
tests/suites/test_suite_hmac_drbg.misc.data
tests/suites/test_suite_md.data
tests/suites/test_suite_pkparse.data
tests/suites/test_suite_x509parse.data
tests/suites/test_suite_x509write.data
```
Due to legacy macros being replaced by PSA ones in test case dependencies (which conflicts with the change of path from `data_files` to `../framework/data_files` in test arguments).

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required - internal file motion only, no user facing changes
- [x] **3.6 backport** of #9249 
- [x] **2.28 backport** not required - no framework in 2.28
- [x] **tests** not required - file motion only

### CODE REVIEW

**Review by ronald-cron-arm — APPROVED** [review]
LGTM, thanks.

**Review by davidhorstmann-arm — COMMENTED** [review]
Submodule update LGTM

**Review by ronald-cron-arm — APPROVED** [review]
LGTM with the approval of the last commit by @davidhorstmann-arm

**Review by tom-daubney-arm — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
