### PR TITLE
Backport 2.28: move entropy init prior arguments number recognition 

### PR DESCRIPTION
**Pull request by PiotrBzdrega**
## Description

Fix to issue #8809 like in development branch

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** provided
- [x] **backport** of #8810
- [ ] **tests** not required

### CODE REVIEW

**Review by gilles-peskine-arm — DISMISSED** [review]
LGTM

**Comment by tom-cosgrove-arm** [comment]
@PiotrBzdrega is this meant to still be draft?

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Comment by tom-cosgrove-arm** [comment]
CI failure is

```
[2024-02-13T16:25:16.919Z] ******************************************************************
[2024-02-13T16:25:16.919Z] * check_files: Check: file sanity checks (permissions, encodings) 
[2024-02-13T16:25:16.919Z] * Tue Feb 13 16:25:16 UTC 2024
[2024-02-13T16:25:16.919Z] ******************************************************************
[2024-02-13T16:25:23.482Z] Missing newline at end of file:
[2024-02-13T16:25:23.482Z] ChangeLog.d/gen-key-segfault.txt
[2024-02-13T16:25:23.482Z] 
[2024-02-13T16:25:23.482Z] ^^^^check_files: Check: file sanity checks (permissions, encodings): tests/scripts/check_files.py -> 1^^^^
```

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Comment by tom-cosgrove-arm** [comment]
I do wonder how hard it would be for the assemble-changelog script to add `\n` if there wasn't one at the end of the `.txt` file...

**Comment by PiotrBzdrega** [comment]
> I do wonder how hard it would be for the assemble-changelog script to add `\n` if there wasn't one at the end of the `.txt` file...

That would be nice 🤔, I will try to find a way

**Review by gilles-peskine-arm — APPROVED** [review]

**Comment by gilles-peskine-arm** [comment]
> I do wonder how hard it would be for the assemble-changelog script to add \n if there wasn't one at the end of the .txt file...

Easy. But `check_files` would complain anyway, so why bother?

> I noticed also that ../scripts/assemble_changelog.py somehow does not take into account:
> Each entry starts with three spaces, an asterisk and a space. Continuation lines start with 5 spaces.

Doable but not a priority, we usually do minor reformatting when we prepare a release anyway.

It would also be nice to enforce line lengths in the changelog, but we also don't want to reformat lines that were deliberately broken in a certain way.

The three-spaces-asterisk thing is weird and we could get rid of it, but that would require changing already-existing entries and we'd have to address pull requests in flight, so it's a lot of hassle for a minor gain.

**Pull request merged**
