### PR TITLE
Finalize split preparation-3

### PR DESCRIPTION
**Pull request by ronald-cron-arm**
## Description
Fixes https://github.com/Mbed-TLS/mbedtls/issues/9624

## PR checklist
- [x] **changelog** not required because: no change from the user perspective
- [x] **development PR** here
- [x] **framework PR** not required
- [x] **3.6 PR** not required because: 4.0 only work 
- [x] **2.28 PR** not required because: 4.0 only work 
- **tests**  not required because: just changing the way things are done

### CODE REVIEW

**Review by minosgalanakis — DISMISSED** [review]
Looks good, but I wil lneed to test locally.

**Review by gabor-mezei-arm — DISMISSED** [review]
Looks good to me

**Comment by ronald-cron-arm** [comment]
Following the merged of #9828, I've rebased on top of development. I've added also two commits addressing issues I spotted when testing TF-PSA-Crypto standalone.

**Comment by ronald-cron-arm** [comment]
The CI failed just because of a tab introduced in the last commit. I've fixed that now. It is ready for re-review.

**Review by gabor-mezei-arm — APPROVED** [review]
LGTM

**Review by minosgalanakis — APPROVED** [review]
LGTM

**Pull request merged**
