### PR TITLE
Test memory management in pkcs7

### PR DESCRIPTION
**Pull request by xkqian**
## Description

Add negative test cases for pkcs7 signer info to cover the memory malloc/free issues.

Change the size or tag of the fields such as version, alg, name, issuer, signature, etc.
Trigger corruption and see whether memory issues happen.

## Gatekeeper checklist

- [ N] **changelog** provided, or not required
- [ N] **backport** done, or not required
- [ Y] **tests** provided, or not required

### CODE REVIEW

**Comment by xkqian** [comment]
Rebase to top of development to solve the conflicts.

**Comment by tom-cosgrove-arm** [comment]
This is still marked `needs-work` - is it ready for review?

**Comment by tom-cosgrove-arm** [comment]
Hmm, on Travis [22594.4 full configuration on arm64](https://app.travis-ci.com/github/Mbed-TLS/mbedtls/jobs/597454352) failed with `test_suite_pkcs7 .................................................. FAIL` so yes, this still `needs-work`

**Comment by daverodgman** [comment]
I think the CI is failing because this is missing the test data files - I've pushed a commit to add these.

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Comment by daverodgman** [comment]
I've run coverage against 4f01121 (the version of the code when #6778 was raised) - this shows significant coverage gaps in `pkcs7_get_signer_info()`. These gaps were covered by the testing work that took place after #6778, but before this PR. So this PR doesn't actually increase coverage, because it's already been done.

I propose merging this PR anyway, because:
- the new tests are simple and target specific areas of PKCS 7 corruption, so it helps assure coverage even if the other test cases were to change
- it's a good example of how to generate PKCS 7 files with specific targeted bits of corruption

Regarding the current level of coverage in these functions:

Looking at `pkcs7_get_signer_info()`, the only un-covered line is the `goto out` for the case where there is a digest algorithm mismatch. This immediately follows a case with a `goto out` which *is* covered, and there's no memory management or function calls between the two, so no risk of this uncovered case causing a memory management issue. Therefore `pkcs7_get_signer_info()` is safe and well covered.

`pkcs7_get_signers_info_set()` is also well covered with two exceptions:
- no coverage for the case with zero signers. OpenSSL won't generate such a file, although it is technically permitted. There is no memory management prior to this case, so exiting here can't leak memory.
- no coverage for when memory allocation fails. This is very hard to test.
I'm happy that this function is well covered re. memory management.

**Review by daverodgman — APPROVED** [review]

**Pull request merged**
