### PR TITLE
Remove all internal functions from public headers

### LINKED ISSUE #7705: More functions should be internal
In Mbed TLS 3.0, we made a few headers internal (that is, moved them the `library/`) that were previously technically public but documented as internal. However, we might have missed a few, and also quite a few public headers also contain internal functions that shouldn't be technically public. We didn't take the time to review and split them, so I think we should in 4.0.

Everytime we notice a function in a public header that shouldn't be public, let's mention it in a comment here.

### LINKED ISSUE #7964: Remove all internal functions from public headers
For historical reasons, we have public headers (`include/mbedtls/*.h`) that declare private functions. We should move their declarations to private headers. We started doing that during the lifetime of 2.x, but mostly only for new functions, so 2.28 LTS still has many private-use functions declared in public headers. Now, [we doubt whether it's ok to change those functions in a LTS release](https://github.com/Mbed-TLS/mbedtls/pull/7788#issuecomment-1643507413).

Ideally, public headers should not describe any private behavior. In practice, they have to describe the implementation of some types, since the compiler needs to know things like the size of variables of a “private” type. But we don't need to declare private functions that don't need cross-library linkage. (Functions used across libraries — crypto functions used in X.509 or TLS, or X.509 functions used in TLS — should be part of the public API.)

The goal of this task is to remove all functions that are not intended to be public from public headers, before we make a 3.x LTS branch.

### PR DESCRIPTION
**Pull request by valeriosetti**
## Description

This PR moves some internal functions prototypes from public to internal header files.

For the list of functions to be moved I used #7705, as mentioned in the original issue (https://github.com/Mbed-TLS/mbedtls/issues/7964#issuecomment-1880866276). If there are more functions that need to be made private, please let me know (or update #7705 with a comment).

Resolves #7964.
Resolves #7705.

## PR checklist

- [x] **changelog** not required as moved functions were already marked as "for internal use only" in most of the cases.
- [x] **backport** not required
- [x] **tests** not required as we're not changing the code, but only the location where functions' prototypes are declared.

### CODE REVIEW

**Review by d3zd3z — APPROVED** [review]
As long as the list of functions made private is adequate, this change seems good to me.

**Comment by mpg** [comment]
> If there are more functions that need to be made private, please let me know

`grep -i '\*.*\<internal\>' include/mbedtls/*.h` finds 75 matches. I haven't looked at everything, a lot of them are clearly OK (struct or fields), some would require looking at the context. If someone has time to take a quick look, that would be great - we're mostly looking for public functions (and to a lesser extent, macros) that could easily be moved to an internal header.

**Comment by gilles-peskine-arm** [comment]
Maybe Doxygen can help us? With `WARN_IF_UNDOCUMENTED` enabled and `EXTRACT_ALL` disabled, we get a list of undocumented names. But there are a lot of false positives to sift through, especially macros that are needed to implement documented macros.

**Comment by minosgalanakis** [comment]
> grep -i '\*.*\<internal\>' include/mbedtls/*.h

I took a look of those files

The following are ok ( onyl expose internal sturctures or macros )
~~~~~
include/mbedtls/aes.h
include/mbedtls/aria.h
include/mbedtls/asn1.h
include/mbedtls/block_cipher.h
include/mbedtls/camellia.h
include/mbedtls/cmac.h
include/mbedtls/config_adjust_legacy_crypto.h
include/mbedtls/config_adjust_ssl.h
include/mbedtls/config_adjust_x509.h
include/mbedtls/des.h
include/mbedtls/ecp.h
include/mbedtls/ecdsa.h
include/mbedtls/md
include/mbedtls/oid.h
include/mbedtls/pkcs7.h
include/mbedtls/pk.h
include/mbedtls/rsa.h
include/mbedtls/ssl_ciphersuites.h
include/mbedtls/ssl.h
include/mbedtls/x509_csr.h
~~~~~

The following have methods which could be moved?

~~~~~
include/mbedtls/md5.h
int mbedtls_md5_finish(mbedtls_md5_context *ctx,
                       unsigned char output[16]);


include/mbedtls/ripemd160.h
int mbedtls_internal_ripemd160_process(mbedtls_ripemd160_context *ctx,
                                       const unsigned char data[64]);

 include/mbedtls/sha1.h
 include/mbedtls/sha256.h
 include/mbedtls/sha512.h

int mbedtls_internal_shaXYZ_process(mbedtls_sha1_context *ctx,
                                  const unsigned char data[64]);  

include/mbedtls/timing.h
unsigned long mbedtls_timing_get_timer(struct mbedtls_timing_hr_time *val, int reset); 
~~~~~

Last but not least  ` include/mbedtls/platform_util.h` has some internal macros but I think we should not be touching them. 

~~~~~
/* Internal macros meant to be called only from within the library. */
#define MBEDTLS_INTERNAL_VALIDATE_RET(cond, ret)  do { } while (0)
#define MBEDTLS_INTERNAL_VALIDATE(cond)           do { } while (0)

/* Internal helper macros for deprecating API constants. */
#if !defined(MBEDTLS_DEPRECATED_REMOVED)
#if defined(MBEDTLS_DEPRECATED_WARNING)

~~~~~

**Review by minosgalanakis — COMMENTED** [review]
Overall looks good. Need to determine if we need we move the internal functions for the hash algorithms

**Comment by gilles-peskine-arm** [comment]
> ```
> /* Internal macros meant to be called only from within the library. */
> #define MBEDTLS_INTERNAL_VALIDATE_RET(cond, ret)  do { } while (0)
> #define MBEDTLS_INTERNAL_VALIDATE(cond)           do { } while (0)
> ```
> 

These have been no-ops since 3.0. We should remove the few remaining uses and the definition. Not necessarily in this PR.


> ```
> /* Internal helper macros for deprecating API constants. */
> #if !defined(MBEDTLS_DEPRECATED_REMOVED)
> #if defined(MBEDTLS_DEPRECATED_WARNING)
> ```

These could be relevant, but we aren't currently using those macros. We might end up using them in 3.6, although I'm not aware of any plan to deprecate a constant in 3.6.

**Comment by gilles-peskine-arm** [comment]
Regarding the `mbedtls_<HASH>_internal_process` functions, these were semi-officially  part of the API in 2.x. I don't remember why we didn't remove them in 3.0: maybe we were planning to but ran out of time? Or maybe there was a reason, perhaps related to ALT implementations? The information is probably in a closed issue on GitHub somewhere...

**Comment by mpg** [comment]
Thank you @minosgalanakis for going over the list!

> These could be relevant, but we aren't currently using those macros. We might end up using them in 3.6, although I'm not aware of any plan to deprecate a constant in 3.6

I think macros for deprecating stuff have to be defined in a public header, since they are going to be used in public headers. 

> Regarding the `mbedtls_<HASH>_internal_process` functions, these were semi-officially part of the API in 2.x. I don't remember why we didn't remove them in 3.0: maybe we were planning to but ran out of time? Or maybe there was a reason, perhaps related to ALT implementations?

I think it's because of the `_PROCESS_ALT` macros that allow replacing just that function. OTOH, we also decided in 3.0 that ALT implementors could be expected to include internal header, for example `library/ecp_internal_alt.h` was created specially for that purpose, so I guess we could move those function's declarations to `library/xxx_internal_alt.h` as well. Would we want a single one for all of them or one file per module?

**Comment by gilles-peskine-arm** [comment]
> I think it's because of the _PROCESS_ALT macros that allow replacing just that function.

Ah, right.

> OTOH, we also decided in 3.0 that ALT implementors could be expected to include internal header

Yes. But we can't change that anymore: that would break existing ALT implementations that wouldn't include the new header, if built with `-Wmissing-prototypes`.

**Comment by mpg** [comment]
> Yes. But we can't change that anymore: that would break existing ALT implementations that wouldn't include the new header, if built with `-Wmissing-prototypes`.

Right, so we need to keep those.

I think that doesn't leave anything more to remove in this PR, considering the `VALIDATE` macros already have [their own issue](https://github.com/Mbed-TLS/mbedtls/issues/4681) so probably should be addressed in a separate PR.

**Comment by tom-cosgrove-arm** [comment]
Ah, I see @minosgalanakis is the other reviewer, but he's on leave this week

**Review by minosgalanakis — APPROVED** [review]
LGTM

**Comment by hmalpani** [comment]
I am building coap example [here](https://github.com/espressif/idf-extra-components/tree/master/coap/examples/coap_client) with mbedtls v3.6.0, and I am getting build errors as some of the API has been made private:

```
/home/harshitmalpani/github/idf-extra-components/coap/libcoap/src/coap_mbedtls.c:1054:18: error: implicit declaration of function 'mbedtls_ssl_ciphersuite_uses_psk'; did you mean 'mbedtls_ssl_ciphersuite_get_id'? [-Werror=implicit-function-declaration]
 1054 |         else if (mbedtls_ssl_ciphersuite_uses_psk(cur)) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  mbedtls_ssl_ciphersuite_get_id

```

I am not sure if some other API can be used in place of `mbedtls_ssl_ciphersuite_uses_psk()`. Can someone help here. Is there any documentation on how to update the code as these APIs have been made private?

**Comment by gilles-peskine-arm** [comment]
@hmalpani `mbedtls_ssl_ciphersuite_uses_psk` and the many other functions whose declarations are no longer in a public header were never public functions — they didn't have any documented effect. If you want them as a public API, that's a request for a new feature, please file an issue.

**Comment by shawnqz** [comment]
how can I call those internal functions again if they became private ? I need "mbedtls_x509_sig_alg_gets", and "mbedtls_mpi_core_bitlen", and they were all moved to library. Is ther any public alternative ?

**Comment by gilles-peskine-arm** [comment]
@shawnqz These functions have never been part of the stable API since they were not documented. If you're willing to live dangerously, you can still call them since C doesn't hide functions at link time, but you'll have to supply your own prototype.

The `mpi_core` functions have never had public declarations. Use functions from `include/mbedtls/bignum.h`, e.g. `mbedtls_mpi_bitlen`.

If there's something missing in the API, please make a feature request and explain what you need. We normally don't add new features in an LTS branch, but just exposing an internal function would probably be ok.

**Pull request merged**
