### PR TITLE
Merge 3.6.2 into 3.6 (slow pkwrite tests)

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Merge 3.6.2 from https://github.com/Mbed-TLS/mbedtls/pull/9694 back into 3.6.2.

This version has extremely slow pkwrite tests with GCC+Asan.

## PR checklist

- [x] **changelog** not required because: just technical git stuff
- [x] **development PR** not required because: N/A
- [x] **framework PR** not required
- [x] **3.6 PR** provided
- [x] **2.28 PR** not required because: no 2.28 release
- **tests**  provided | not required because:

### CODE REVIEW

**Review by yanesca — APPROVED** [review]
LGTM

**Review by davidhorstmann-arm — DISMISSED** [review]
LGTM, thanks!

**Comment by yanesca** [comment]
Restarted the CI as it had a timeout.

**Review by yanesca — APPROVED** [review]
LGTM

**Comment by gilles-peskine-arm** [comment]
Superseded by https://github.com/Mbed-TLS/mbedtls/pull/9698

**Pull request closed without merging**
