### PR TITLE
[dev] Rsapub performance fix

### LINKED ISSUE #9232: Performance regression in mbedtls_mpi_exp_mod() (v3.6.0)
We observed that the `mbedtls_mpi_exp_mod()` function takes much more time to complete in v3.6.0 than in v3.5.2 (about 16 times more). The platform is OP-TEE OS running in QEMU (arm32). See https://github.com/OP-TEE/optee_os/pull/6797 and in particular this commit which brings the function back to the v3.5.2 and solves the issue: https://github.com/jforissier/optee_os/commit/f147fc17b69efc9f22d122466d7b6b9678a6ad61

Any idea what's wrong?

---
Edit (mpg): [status summary](https://github.com/Mbed-TLS/mbedtls/issues/9232#issuecomment-2324078780).

### PR DESCRIPTION
**Pull request by mpg**
## Description

This is the development forward-port of #9281 and #9493. Fixes #9232.

Steps:
1. Cherry-pick all commits from 9281 - some conflicts in core tests because development has constant-time testing of the core expmod function, that 3.6 doesn't have. (Resolved inaccurately, but that will be undone later, see 3a.)
2. Cherry-pick all commits from 9493 - no further conflicts.
3. Adapt to development:
   a. Remove codepath testing when it's redundant.
   b. Move new files to their correct tf-psa-crypto location + define variables in the right places.

## PR checklist

- [x] **changelog** provided
- [x] **development PR** here
- [x] **framework PR** not required
- [x] **3.6 PR** provided #9493 + #9281
- [x] **2.28 PR** not required because: 2.28 not affected by the perf regression
- **tests**  provided

### CODE REVIEW

**Comment by yanesca** [comment]
I have performed steps 1 and 2 and reviewed the difference between the result and this PR. It mostly looks good to me, I just have a question: in step 3a when did you consider a check redundant? I mean, I can see that you kept a number of codepath checks and removed some. I am just curious how the keep/remove decision was made.

**Comment by mpg** [comment]
> in step 3a when did you consider a check redundant? I mean, I can see that you kept a number of codepath checks and removed some. I am just curious how the keep/remove decision was made.

I considered a codepath check redundant when we have proper constant-flow testing (of the safe variant of course), because it already ensures we're not accidentally taking the unsafe codepath - that would result in a constant-flow error.

That's the case for the core expmod function, where CF testing was added recently, so I removed codepath testing there. That's not the case of the bignum expmod function (it has branches for reallocations, sign handling, etc.) and the RSA functions that use it: here since we don't have CF testing, codepath testing is the best way we have to ensure we don't accidentally take the unsafe path.

**Review by yanesca — APPROVED** [review]
Oh, indeed, that makes perfect sense. LGTM

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Pull request merged**
