### PR TITLE
[Backport 3.6] Improve support for submodules in code_style.py

### PR DESCRIPTION
**Pull request by Harry-Ramsey**
This commit improves support for submodules within code_style.py. A new function get_submodule_hash retrieves the submodule hash at the time of a commit allowing an appropriate diff to be seen.

Backport of: #9597.

## PR checklist

Please remove the segment/s on either side of the | symbol as appropriate, and add any relevant link/s to the end of the line.
If the provided content is part of the present PR remove the # symbol.

- [x] **changelog** not required because: a script change that fixes incorrect behaviour.
- [x] **development PR** provided: #9597 
- [x] **framework PR** not required.
- [x] **3.6 PR** provided.
- [x] **2.28 PR** not required because: No framework submodule.
- **tests**  not required.

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

### CODE REVIEW

**Review by gilles-peskine-arm — APPROVED** [review]
LGTM

**Review by eleuzi01 — APPROVED** [review]
LGTM, thanks!

**Comment by eleuzi01** [comment]
Minor comment: usually backports have the same title as the main PRs -> [more info](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/#creating-backports)

**Comment by Harry-Ramsey** [comment]
Thanks, sorry didn't notice it just copied the branch name.

**Pull request merged**
