### PR TITLE
[Backport 3.6] Move TLS auxiliary test scripts to the framework

### PR DESCRIPTION
**Pull request by eleuzi01**
## Description

Backport of #9673 

## PR checklist

Please remove the segment/s on either side of the | symbol as appropriate, and add any relevant link/s to the end of the line.
If the provided content is part of the present PR remove the # symbol.

- [x] **changelog** not required - internal changes
- [x] **development PR** provided #9673
- [x] **framework PR** provided https://github.com/Mbed-TLS/mbedtls-framework/pull/56
- [x] **3.6 PR** provided
- [x] **2.28 PR** not required because no framework in 2.28
- [x] **tests**  not required - file movement only

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

### CODE REVIEW

**Review by mpg — APPROVED** [review]
LGTM

**Review by mpg — APPROVED** [review]

**Review by davidhorstmann-arm — APPROVED** [review]
LGTM, thanks!

**Review by gilles-peskine-arm — APPROVED** [review]
Approving the last commit that updates the framework, based upon the the approval of 5adc9c304b09f612e9414f2a6cca8e3bb1551cd9 [by Manuel](https://github.com/Mbed-TLS/mbedtls/pull/9675#pullrequestreview-2371988583) or [by David](https://github.com/Mbed-TLS/mbedtls/pull/9675#pullrequestreview-2372537740).

**Review by davidhorstmann-arm — APPROVED** [review]
LGTM

**Pull request merged**
