### PR TITLE
Updating test-ca.key to use AES instead of DES

### PR DESCRIPTION
**Pull request by bharsaklemukesh975**
Please refer to #7039 

The PR updated only test-ca.key.

## Gatekeeper checklist

- [x] **changelog** not required - internal test changes
- [x] **backport** see https://github.com/Mbed-TLS/mbedtls/pull/7571
- [x] **tests** provided

### CODE REVIEW

**Review by yuhaoth — CHANGES_REQUESTED** [review]
Would you like update `tests/data_files/Makefile` ? Add `test-ca.key` generate command.

**Comment by yuhaoth** [comment]
And the commit should be sign with `git commit -s --amend`. This PR got a DCO fail.

**Comment by yuhaoth** [comment]
> > ? Add `test-ca.key` generate command.
> 
> Can you please share more context, as the key is already generated with AES and saved in the repository?

In `tests/data_files/Makefile` , add a target `$(test_ca_key_file_rsa):` and the command.
```
test_ca_crt = test-ca.crt
test_ca_key_file_rsa = test-ca.key
test_ca_pwd_rsa = PolarSSLTest
test_ca_config_file = test-ca.opensslconf

$(test_ca_key_file_rsa):
         < your generated command, like $(OPENSSL) genkey ... >
test-ca.req.sha256: $(test_ca_key_file_rsa)
	$(MBEDTLS_CERT_REQ) output_file=$@ filename=$(test_ca_key_file_rsa) password=$(test_ca_pwd_rsa) subject_name="C=NL,O=PolarSSL,CN=PolarSSL Test CA" md=SHA256
all_intermediate += test-ca.req.sha256
```

That will record the step of generating the key.

**Review by yuhaoth — APPROVED** [review]
LGTM

**Review by mpg — APPROVED** [review]
Looks good to me!

I have verified that the content of the key has not actually changed, just been re-encrypted, by running the following command both before and after this PR and confirming the output is identical: `openssl rsa -in test-ca.key -passin "pass:PolarSSLTest"`.

Just a minor suggestion for next time: please say in the commit message what command you used to make the conversion.

**Comment by mpg** [comment]
@gilles-peskine-arm Do you think this needs a backport? On one hand, we tend to keep tests aligned between branches when we can in order to simplify future backports. On the other hand, the issue is labelled "enhancement" and I guess it's prep work for removing DES later, which is not going to happen in the LTS branch. Wdyt?

**Comment by mpg** [comment]
@bharsaklemukesh975 Congrats on getting your first PR approved!

Since this was only the first step of #7039 (and you're right of course to proceed in small steps especially for your first contribution), feel free to move on to the next steps in that issue: re-encrypt `*.key.enc` and `ec_prv.*.pw.*` files, then add AES variants of `rsa_pkcs8*des.*` files.

**Comment by gilles-peskine-arm** [comment]
Our primary motivation is to prepare for removing AES. But this is also useful for integrators who'd like to run tests of their configuration on their platform, and their configuration often includes AES but not DES. So I'd prefer to backport, but I wouldn't insist on it.

**Comment by bharsaklemukesh975** [comment]
@mpg Thanks, my forked repo does not have this LTS branch, how can I create a new branch base on the LTS branch?

**Comment by mpg** [comment]
> Thanks, my forked repo does not have this LTS branch, how can I create a new branch base on the LTS branch?

I think I'd do something like:
```
git remote add upstream git@github.com:Mbed-TLS/mbedtls.git
git fetch upstream
git branch --track mbedtls-2.28 upstream/mbedtls-2.28
```
This adds the upstream repository as a new remote called "upstream" (in addition to your fork which is likely called "origin"), and creates a local branch called "mbedtls-2.28" based on our branch with the same name. You can then create and checkout your backport branch with
```
git checkout -b update-pkparse-tests-to-use-AES-2.28 mbedtls-2.28
```
then reproduce the changes from the original "update-pkparse-tests-to-use-AES" branch. For example, this can often be done with:
```
git cherry-pick development..update-pkparse-tests-to-use-AES
```
but this might not work due to conflicts, in which case you'll have to either resolve the conflicts or recreate the changes manually.

In the future, when you want to create another backport, you'll want to update your local "mbedtls-2.28" branch first:
```
git checkout mbedtls-2.28
git pull
# then "git checkout -b some-work-2.28" and the rest as before
```

**Comment by bharsaklemukesh975** [comment]
Thanks @mpg , created #7571 for back-port.

**Comment by AndrzejKurek** [comment]
Unfortunately, this PR introduced a faulty makefile recipe, see https://github.com/Mbed-TLS/mbedtls/pull/7634 for details.

**Pull request merged**
