### PR TITLE
Update old dependency to MBEDTLS_MD_CAN

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
This is a follow-up to 0b8095d96ac57fa3b385cdb57cc94479795550df from #7284. Some test cases had a typo in the old dependency
name (MBEDTLS_HAS_MD5_VIA_LOWLEVEL_OR_PSA instead of MBEDTLS_HAS_ALG_MD5_VIA_LOWLEVEL_OR_PSA) which caused us to miss them.

No completeness objective, I'm just fixing one thing that [@lpy4105 noticed](https://github.com/Mbed-TLS/mbedtls/pull/8022#discussion_r1282684369).

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** no (fixing a test)
- [x] **backport** no (affects work done in 3.x)
- [x] **tests** N/A

### CODE REVIEW

**Review by tom-cosgrove-arm — DISMISSED** [review]
LGTM

**Review by lpy4105 — COMMENTED** [review]
LGTM on 4ebccc03969f81c37d1c509c46350d05b2cd4b11, except the macros changes on PSA init. I've pushed my fix, pls tell me if it looks good to you @gilles-peskine-arm

**Review by gilles-peskine-arm — COMMENTED** [review]
Thanks for the update @lpy4105, I had indeed used the wrong macros.

**Review by lpy4105 — DISMISSED** [review]
LGTM

**Review by tom-cosgrove-arm — DISMISSED** [review]
LGTM

**Comment by lpy4105** [comment]
Merge queue failures are related to the changes in https://github.com/Mbed-TLS/mbedtls/pull/8495. I will firstly merge `development` and see if we need a fix.

**Comment by lpy4105** [comment]
The CI passes after the fix, please re-review @tom-cosgrove-arm and @gilles-peskine-arm

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Review by lpy4105 — APPROVED** [review]
@gilles-peskine-arm I approve this PR, if you don't disagree with the fix.

**Pull request merged**
