### PR TITLE
Split out configuration adjustments from build_info.h and config_psa.h

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Split out the configuration adjustments in `config_psa.h` and (most of the ones in) `build_info.h`. Each new file has a well-defined goal. This is a rework of part of https://github.com/Mbed-TLS/mbedtls/pull/7615.

The goal of this pull request is to create and populate the new files and nothing more. So it consists of:

* Creating new files and writing a description.
* Moving content into those new files.
* The minimum needed to pass the CI.

The following are out of scope and will be done in follow-ups:

* Removing `config_psa.h` which is not really meaningful anymore.
* Any bug fix or presentation improvement that involves reordering the order of definitions and checks.
* Validation of the files' contents.
* More detailed guidance on what goes into each file.

The reason to minimize the scope is that this part has a high potential for merge conflicts. To avoid repeated conflicts, we want to get it in as quickly as possible and in one go.

Review advice: the overall diff is huge, but `git diff --color-moved` on each commit is very effective.

## PR checklist

- [x] **changelog** no (refactoring only)
- [x] **backport** no
- [x] **tests** no (refactoring only)

### CODE REVIEW

**Comment by gilles-peskine-arm** [comment]
I'll amend some commits to tweak some comments to pacify check-names. I'll force-push once the CI results are complete.

**Comment by gilles-peskine-arm** [comment]
There was already a merge conflict so I rebased to re-do the moves.

**Review by ronald-cron-arm — APPROVED** [review]
LGTM

**Review by valeriosetti — APPROVED** [review]
I'm not super happy about the naming of the `config_adjust_legacy_crypto.h` because it both contains "backward compatibility auto-enables" (ex: `MBEDTLS_MD_LIGHT`) and also "internal helpers" (ex: `MBEDTLS_CAN_ECDH`). Since IMO both of them belong to the "internal helper" area, I would have named the file `config_adjust_internal_helpers.h`.
But that's just my opinion and it only concerns file naming, so as long as the underling change is OK and the CI is happy, I'm OK with this PR ;)

**Comment by gilles-peskine-arm** [comment]
> I'm not super happy about the naming of the config_adjust_legacy_crypto.h because it both contains "backward compatibility auto-enables" (ex: MBEDTLS_MD_LIGHT) and also "internal helpers" (ex: MBEDTLS_CAN_ECDH). Since IMO both of them belong to the "internal helper" area, I would have named the file config_adjust_internal_helpers.h.

I broadly agree (although I don't think those are good examples: both are internal helpers). We're likely to handle this in a follow-up. We may actually end up splitting this file further, with some reordering with respect to other files. Because it involves reordering, it's out of scope here.

**Pull request merged**
