### PR TITLE
Backport 2.28: ssl-opt.sh: Fix getting the list of supported ciphersuites.

### PR DESCRIPTION
**Pull request by yuhaoth**
## PR checklist
Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required
- [ ] **backport** of https://github.com/Mbed-TLS/mbedtls/pull/8561
- [x] **tests** not required

### CODE REVIEW

**Review by gilles-peskine-arm — APPROVED** [review]

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]
Please backport https://github.com/Mbed-TLS/mbedtls/pull/8561/commits/60f76663c0ffffad28973e2ba2d7fe09ee8c0dfa

**Comment by yuhaoth** [comment]
I directly rebased #8561

**Review by lpy4105 — APPROVED** [review]
The backport LGTM.

**Review by gilles-peskine-arm — APPROVED** [review]
LGTM

**Pull request merged**
