### PR TITLE
[DRAFT] Introduce internal types for EC points, groups, and coordinates

### PR DESCRIPTION
**Pull request by hanno-becker**
This PR is part of a series of PRs aiming (a) to provide a framework for replacing the modular arithmetic underlying our ECP module and (b) along the way, reduce the number of heap allocations. The first two PR are #5377 and #5383.

The state of affairs in #5383 is that all MPIs involved in ECP coordinate calculations are of standard size (that is, have the same number of limbs as the underlying prime modulus). This would in principle allow for the drop-in of alternative low-level arithmetic routines which operate directly on the MPI buffers, thereby bypassing the bignum module.

However, while #5383 upholds this static allocation property of MPIs to the best of my knowledge, it's difficult to reason that it does. 

The primary motivation for this PR was to use the type system to help track for which MPIs we can be certain that they are of standard size: One introduces a wrapper type `typedef struct { mbedtls_mpi v; } mbedtls_ecp_mpi_internal;` which can be constructed only through helpers which ensure that the underlying MPI is of standard size. As long as this constructor is adhered to, every occurrence of `mbedtls_ecp_mpi_internal` then ensures that the underlying MPI is of standard size, and the "unwrapping" of the underlying MPI comes at no runtime cost.

__Note:__ Needs updating, but holding back until there's clarity on if / in what form the ECP prototype shall be integrated.

### CODE REVIEW

**Comment by hanno-arm** [comment]
Measurements with stack allocated local MPIs:
```
ECDHE-secp521r1       : 180 hs/s (dev: 182)  5992 b heap (dev: 6720),   1904 allocs (dev:   14119)
ECDHE-brainpoolP512r1 :  27 hs/s (dev: 27)   5616 b heap (dev: 6936), 120722 allocs (dev:  131104)
ECDHE-secp384r1       : 268 hs/s (dev: 251)  4568 b heap (dev: 5584),   1485 allocs (dev:   15180)
ECDHE-brainpoolP384r1 :  52 hs/s (dev: 52)   4592 b heap (dev: 5896),  90999 allocs (dev:   98888)
ECDHE-secp256r1       : 437 hs/s (dev: 399)  3592 b heap (dev: 4496),   1112 allocs (dev:   10937)
ECDHE-secp256k1       : 364 hs/s (dev: 378)  3592 b heap (dev: 4184),  15549 allocs (dev:   21235)
ECDHE-brainpoolP256r1 :  99 hs/s (dev: 99)   3592 b heap (dev: 4472),  64255 allocs (dev:   69964)
ECDHE-secp224r1       : 597 hs/s (dev: 597)  3488 b heap (dev: 4104),   986 allocs  (dev:    6749)
ECDHE-secp224k1       : 388 hs/s (dev: 419)  3488 b heap (dev: 4152),  13828 allocs (dev:   18896)
ECDHE-secp192r1       : 824 hs/s (dev: 800)  3104 b heap (dev: 3512),   901 allocs  (dev:    6116)
ECDHE-secp192k1       : 503 hs/s (dev: 539)  3104 b heap (dev: 3592),  11897 allocs (dev:   16272)
ECDHE-x25519          : 324 hs/s (dev: 310)  2136 b heap (dev: 2456),   1158 allocs (dev:   15478)
ECDHE-x448            : 149 hs/s (dev: 144)  3040 b heap (dev: 3752),   1937 allocs (dev:   28878)
```

**Comment by hanno-arm** [comment]
Current code size impact compared to development (GCC 8.3.1, M0+, `-Os`)
```
library/ecp.o, 10226, 9406, 820, 8.72%
library/ecp_curves.o, 37684, 38192, -508, -1.33%
```
Speed, heap usage and heap allocations:
```
  ECDHE-secp256r1          :     457 full handshake/s (dev:399)  3856 heap bytes (dev:4496),    307 allocs (dev: 10937)
```

**Comment by hanno-arm** [comment]
Current performance measurements:
```
  ECDHE-secp521r1          :     182 full handshake/s   6456 heap bytes,    288 allocs
  ECDHE-brainpoolP512r1    :      27 full handshake/s   6040 heap bytes, 119139 allocs
  ECDHE-secp384r1          :     284 full handshake/s   4912 heap bytes,    310 allocs
  ECDHE-brainpoolP384r1    :      53 full handshake/s   4936 heap bytes,  89824 allocs
  ECDHE-secp256r1          :     463 full handshake/s   3856 heap bytes,    313 allocs
  ECDHE-secp256k1          :     390 full handshake/s   3856 heap bytes,  14738 allocs
  ECDHE-brainpoolP256r1    :     101 full handshake/s   3856 heap bytes,  63452 allocs
  ECDHE-secp224r1          :     639 full handshake/s   3752 heap bytes,    288 allocs
  ECDHE-secp224k1          :     412 full handshake/s   3752 heap bytes,  13120 allocs
  ECDHE-secp192r1          :     881 full handshake/s   3328 heap bytes,    305 allocs
  ECDHE-secp192k1          :     551 full handshake/s   3328 heap bytes,  11305 allocs
  ECDHE-x25519             :     333 full handshake/s   2384 heap bytes,    172 allocs
  ECDHE-x448               :     159 full handshake/s   3640 heap bytes,    177 allocs
```
For comparison, here are the numbers from #5383 and development
```
ECDHE-secp521r1       : 186 hs/s (dev: 182)  6672 b heap (dev: 6720),   2436 allocs (dev:   14119)
ECDHE-brainpoolP512r1 :  27 hs/s (dev: 27)   6272 b heap (dev: 6936), 121244 allocs (dev:  131104)
ECDHE-secp384r1       : 269 hs/s (dev: 251)  5176 b heap (dev: 5584),   1899 allocs (dev:   15180)
ECDHE-brainpoolP384r1 :  52 hs/s (dev: 52)   5200 b heap (dev: 5896),  91412 allocs (dev:   98888)
ECDHE-secp256r1       : 430 hs/s (dev: 399)  4152 b heap (dev: 4496),   1448 allocs (dev:   10937)
ECDHE-secp256k1       : 379 hs/s (dev: 378)  4152 b heap (dev: 4184),  15870 allocs (dev:   21235)
ECDHE-brainpoolP256r1 : 100 hs/s (dev: 99)   4152 b heap (dev: 4472),  64580 allocs (dev:   69964)
ECDHE-secp224r1       : 607 hs/s (dev: 597)  4048 b heap (dev: 4104),   1284 allocs (dev:    6749)
ECDHE-secp224k1       : 417 hs/s (dev: 419)  4048 b heap (dev: 4152),  14128 allocs (dev:   18896)
ECDHE-secp192r1       : 841 hs/s (dev: 800)  3640 b heap (dev: 3512),   1170 allocs (dev:    6116)
ECDHE-secp192k1       : 541 hs/s (dev: 539)  3640 b heap (dev: 3592),  12169 allocs (dev:   16272)
ECDHE-x25519          : 347 hs/s (dev: 310)  2376 b heap (dev: 2456),   1197 allocs (dev:   15478)
ECDHE-x448            : 162 hs/s (dev: 144)  3304 b heap (dev: 3752),   1978 allocs (dev:   28878)
```

**Comment by tom-cosgrove-arm** [comment]
After discussing with @yanesca closing this, as we will do things differently now

**Pull request closed without merging**
