### PR TITLE
TLS 1.3 - miscellaneous

### PR DESCRIPTION
**Pull request by ronald-cron-arm**
## Description
Two first commits: follow-up of #5640. Otherwise, some improvements of TLS 1.3 compat tests and some dead-code clean-up.

## Status
READY

## Requires Backporting
No, TLS 1.3 only.

### CODE REVIEW

**Review by yuhaoth — APPROVED** [review]
LGTM

**Review by minosgalanakis — COMMENTED** [review]
It is not clear what the commit message is.

> ECDH operations in TLS 1.3 are no done through PSA.

Should it be?
> ECDH operations in TLS 1.3 are now done through PSA.

**Comment by minosgalanakis** [comment]
Other than  the typo on the comit message it looks good

**Comment by ronald-cron-arm** [comment]
> Other than the typo on the commit message it looks good

@minosgalanakis Sorry for the late reply but I was waiting for #5631 to be merged. I've fixed the last commit message.

**Comment by ronald-cron-arm** [comment]
@yuhaoth @minosgalanakis I've rebased to fix the conflicts due to the merge of #5631. Please have another look.

**Review by yuhaoth — APPROVED** [review]
LGTM. 

And I think open CI error can be ignore

**Comment by minosgalanakis** [comment]
LGTM

**Review by minosgalanakis — APPROVED** [review]

**Pull request merged**
