### PR TITLE
Fix file missing fail on development

### PR DESCRIPTION
**Pull request by yuhaoth**
## Description

#7617 moves `rsa_single_san_uri.crt.der` to `tests/data_files/parse_input` because the file is used by some parse tests only.
And #7575 add `x509_verify` tests , those tests need the file

## Gatekeeper checklist

- [x] **changelog** provided, or not required
- [x] **backport** done, or not required
- [x] **tests** provided, or not required

## Notes for the submitter

Please refer to the [contributing guidelines](../CONTRIBUTING.md), especially the
checklist for PR contributors.

### CODE REVIEW

**Comment by AndrzejKurek** [comment]
Shouldn't there be just a single copy of rsa_single_san_uri.crt.der in the `tests/data_files` directory, and the second one in `parse_input` directory be removed?

**Comment by yuhaoth** [comment]
> Shouldn't there be just a single copy of rsa_single_san_uri.crt.der in the `tests/data_files` directory, and the second one in `parse_input` directory be removed?

Files in `parse_input` won't be updated when expired. And the file is used by `x509_verify`, it should be update when expired

**Comment by AndrzejKurek** [comment]
> > Shouldn't there be just a single copy of rsa_single_san_uri.crt.der in the `tests/data_files` directory, and the second one in `parse_input` directory be removed?
> 
> Files in `parse_input` won't be updated when expired. And the file is used by `x509_verify`, it should be update when expired

Yes, exactly. Why do we need a second copy in `parse_input`?

**Comment by mpg** [comment]
Note: this blocks all other PRs (except those based on old enough development), so I'm strongly inclined to (1) do whatever stops the failure right now (2) only once that's done, discuss what's the right thing to do - and do it in a follow-up PR if necessary.

**Review by AndrzejKurek — APPROVED** [review]

**Pull request merged**
