### PR TITLE
RSA support CRT and NO_CRT mode at same time

### PR DESCRIPTION
**Pull request by lubing521**
Keymaster VTS need libmbedtls with CRT in optee-os.
But some case of the Xtest 4006 no provide CRT
This will cause OP-tee OS check it fail. in order
to support this scenario work well,libmedtls need
frendly deal with RSA with CRT or not.

Tested-by: lubing <lubing@eswin.com>
Signed-off-by: lubing <lubing@eswin.com>

### CODE REVIEW

**Comment by yanesca** [comment]
@lubing521 I would like to continue our discussion we started on https://github.com/ARMmbed/mbedtls/pull/4721. Sorry, the other day I thought I understand it, but reading it back I am lost again.

>Keymaster TA in function TA_generate_key which on flie https://github.com/linaro-swg/kmgk/blob/master/keymaster/ta/generator.c
This function will create rsa key pair with CRT,so in optee-os with libmbedtls need enable CRT together.
if not ,this function will be called fail in rsa_check_context.
call stack as below in optee-os
syscall_asymm_operate--》crypto_acipher_rsanopad_decrypt–》mbedtls_rsa_private–》rsa_check_context

You write that you need to enable CRT because otherwise this part of the code fails:

```
#if !defined(MBEDTLS_RSA_NO_CRT)
    /* Modular exponentiation for P and Q is only
     * used for private key operations and if CRT
     * is used. */
    if( is_priv &&
        ( mbedtls_mpi_cmp_int( &ctx->P, 0 ) <= 0 ||
          mbedtls_mpi_get_bit( &ctx->P, 0 ) == 0 ||
          mbedtls_mpi_cmp_int( &ctx->Q, 0 ) <= 0 ||
          mbedtls_mpi_get_bit( &ctx->Q, 0 ) == 0  ) )
    {
        return( MBEDTLS_ERR_RSA_BAD_INPUT_DATA );
    }
#endif /* !MBEDTLS_RSA_NO_CRT */
```

If CRT is not enabled, then the option `MBEDTLS_RSA_NO_CRT` is defined and consequently the condition `!defined(MBEDTLS_RSA_NO_CRT)` will be false and the above code will not be present in the build and the program can't fail there.

What am I missing?

**Comment by lubing521** [comment]
@yanesca 
I think it needs to be reorganized

In our usage scenario,we need enable mbedtls in optee-os,but mbedtls no support CRT by default.
so we found that keymaster vts one case run fail  as show below 
```
130|console:/data/nativetest/VtsHalKeymasterV3_0TargetTest #
./VtsHalKeymasterV3_0TargetTest --gtest_filter=PerInstance/AttestationTest.RsaAttestation/0_default
Note: Google Test filter = PerInstance/AttestationTest.RsaAttestation/0_default
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from PerInstance/AttestationTest
[ RUN      ] PerInstance/AttestationTest.RsaAttestation/0_default
E/TC:? 0
E/TC:? 0 TA panicked with code 0xffff0001
E/LD:  Status of TA b13a05fa-cfd9-4c8e-9409-db2118d19a2f
E/LD:   arch: aarch64
E/LD:  region  0: va 0x40004000 pa 0x81180000 size 0x002000 flags rw-s (ldelf)
E/LD:  region  1: va 0x40006000 pa 0x81182000 size 0x009000 flags r-xs (ldelf)
E/LD:  region  2: va 0x4000f000 pa 0x8118b000 size 0x001000 flags rw-s (ldelf)
E/LD:  region  3: va 0x40010000 pa 0x8118c000 size 0x004000 flags rw-s (ldelf)
E/LD:  region  4: va 0x40014000 pa 0x81190000 size 0x001000 flags r--s
E/LD:  region  5: va 0x40015000 pa 0x81234000 size 0x009000 flags rw-s (stack)
E/LD:  region  6: va 0x4001e000 pa 0xf07fd4a8 size 0x003000 flags rw-- (param)
E/LD:  region  7: va 0x40021000 pa 0xf15e04a8 size 0x002000 flags rw-- (param)
E/LD:  region  8: va 0x40084000 pa 0x00001000 size 0x050000 flags r-xs [0]
E/LD:  region  9: va 0x400d4000 pa 0x00051000 size 0x053000 flags rw-s [0]
E/LD:   [0] b13a05fa-cfd9-4c8e-9409-db2118d19a2f @ 0x40084000
E/LD:  Call stack:
E/LD:   0x0000000040097800
E/LD:   0x000000004008cd8c
E/LD:   0x000000004008f714
E/LD:   0x0000000040085308
E/LD:   0x0000000040086b20
E/LD:   0x000000004009c0a0
E/LD:   0x0000000040094e08
hardware/interfaces/keymaster/3.0/vts/functional/keymaster_hidl_hal_test.cpp:3929: Failure
Expected: (cert_chain.size()) >= (2U), actual: 0 vs 2
Segmentation fault
[  261.709425] init: Untracked pid 5343 exited with status 0
[  261.717185] init: Untracked pid 5345 exited with status 0
139|console:/data/nativetest/VtsHalKeymasterV3_0TargetTest #
```
as a result  that Keymaster TA in function TA_generate_key which on flie https://github.com/linaro-swg/kmgk/blob/master/keymaster/ta/generator.c  This function will create rsa key pair with CRT,
but mbedtls not support CRT by default , this will casues TA panic.
 
After analysis we need the following code support
```
#if !defined(MBEDTLS_RSA_NO_CRT)
    /*
     * DP = D mod (P - 1)
     * DQ = D mod (Q - 1)
     * QP = Q^-1 mod P
     */
    MBEDTLS_MPI_CHK( mbedtls_rsa_deduce_crt( &ctx->P, &ctx->Q, &ctx->D,
                                             &ctx->DP, &ctx->DQ, &ctx->QP ) );
#endif /* MBEDTLS_RSA_NO_CRT */
```
so we enable CRT in the file lib/libmbedtls/include/mbedtls_config_kernel.h by  Comment line
#define MBEDTLS_RSA_NO_CRT 

keymaster vts work well with optee-os after enable mbedtls with CRT.

But something else happened, But the xtest program, a companion to optee-os, doesn't work.

xtest 4006 for rsa test fail .

```
# xtest 4006
Test ID: 4006
Run test suite with level=0

TEE test application started over default TEE instance
######################################################
#
# regression
#
######################################################
 
* regression_4006 Test TEE Internal API Asymmetric Cipher operations
o regression_4006.1 Asym Crypto case 0 algo 0x60000030 line 2728
regression_4000.c:3900: ta_crypt_cmd_asymmetric_decrypt(c, &session, op, ((void *)0), 0, out_enc, out_enc_size, out, &out_size) has an unexpected value: 0xffff0006 = TEEC_ERROR_BAD_PARAMETERS, expected 0x0 = TEEC_SUCCESS
  regression_4006.1 FAILED
  regression_4006 FAILED
+-----------------------------------------------------
Result of testsuite regression filtered by "4006":
regression_4006.1 FAILED first error at regression_4000.c:3900
regression_4006 FAILED
+-----------------------------------------------------
36 subtests of which 1 failed
1 test case of which 1 failed
91 test cases were skipped
TEE test application done!


D/TC:? 0 tee_ta_init_pseudo_ta_session:299 Lookup pseudo TA cb3e5ba0-adf1-11e0-998b-0002a5d5c51b
D/TC:? 0 ldelf_load_ldelf:91 ldelf load address 0x40006000
D/LD:  ldelf:134 Loading TS cb3e5ba0-adf1-11e0-998b-0002a5d5c51b
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF cb3e5ba0-adf1-11e0-998b-0002a5d5c51b (Secure Storage TA)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF cb3e5ba0-adf1-11e0-998b-0002a5d5c51b (REE)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0
D/LD:  ldelf:168 ELF (cb3e5ba0-adf1-11e0-998b-0002a5d5c51b) at 0x40079000
D/TC:? 0 tee_ta_invoke_command:823 Error: ffff0006 of 4
D/TC:? 0 tee_ta_close_session:512 csess 0x9a115530 id 1
D/TC:? 0 tee_ta_close_session:531 Destroy session
D/TC:? 0 destroy_context:308 Destroy TA ctx (0x9a1154a0)
 ```

I found that xtest 4006 will test without crt parameters and with crt parameters.

```
static const struct xtest_ac_case xtest_ac_cases[] = {

/* RSA test without crt parameters */

XTEST_AC_RSA_CASE(0, TEE_ALG_RSA_NOPAD, TEE_MODE_ENCRYPT, XTEST_AC_RSA_CASE(0, TEE_ALG_RSA_NOPAD, TEE_MODE_ENCRYPT,   ac_rsassa_vect1, NULL_ARRAY, WITHOUT_SALT),

....

...

/* RSA test with crt parameters */

XTEST_AC_RSA_CASE(0, TEE_ALG_RSA_NOPAD, TEE_MODE_ENCRYPT,XTEST_AC_RSA_CASE(0, TEE_ALG_RSA_NOPAD, TEE_MODE_ENCRYPT,   ac_rsassa_vect1, ARRAY, WITHOUT_SALT),

....

...

}
```
By comparing the tomcrypt library ,we get some useful information as below

tomcrypt and mbedtls in optee-os deal with diffrence ways.

1.tomcrypt will do mp_exptmod when xtest 4006 without crt parameters,so no affect after test process.

2.mbedtls withh CRT will check CRT parameters in function rsa_check_context, it will return MBEDTLS_ERR_RSA_BAD_INPUT_DATA when xtest 4006 without crt parameters, so xtest 4006 run fail.

call stack as below :
syscall_asymm_operate--》crypto_acipher_rsanopad_decrypt–》mbedtls_rsa_private–》rsa_check_context

 ```
#if !defined(MBEDTLS_RSA_NO_CRT)
    /* Modular exponentiation for P and Q is only
     * used for private key operations and if CRT
     * is used. */
    if( is_priv &&
        ( mbedtls_mpi_cmp_int( &ctx->P, 0 ) <= 0 ||
          mbedtls_mpi_get_bit( &ctx->P, 0 ) == 0 ||
          mbedtls_mpi_cmp_int( &ctx->Q, 0 ) <= 0 ||
          mbedtls_mpi_get_bit( &ctx->Q, 0 ) == 0  ) )
    {
        return( MBEDTLS_ERR_RSA_BAD_INPUT_DATA );
    }
#endif /* !MBEDTLS_RSA_NO_CRT */
```

To solve this scenario we borrowed from the tomcrypt implementation,

RSA support CRT and NO_CRT mode at same time when mbedtls enable CRT.

**Comment by lubing521** [comment]
> @lubing521 I would like to continue our discussion we started on #4721. Sorry, the other day I thought I understand it, but reading it back I am lost again.
> 
> > Keymaster TA in function TA_generate_key which on flie https://github.com/linaro-swg/kmgk/blob/master/keymaster/ta/generator.c
> > This function will create rsa key pair with CRT,so in optee-os with libmbedtls need enable CRT together.
> > if not ,this function will be called fail in rsa_check_context.
> > call stack as below in optee-os
> > syscall_asymm_operate--》crypto_acipher_rsanopad_decrypt–》mbedtls_rsa_private–》rsa_check_context
> 
> You write that you need to enable CRT because otherwise this part of the code fails:
> 
> ```
> #if !defined(MBEDTLS_RSA_NO_CRT)
>     /* Modular exponentiation for P and Q is only
>      * used for private key operations and if CRT
>      * is used. */
>     if( is_priv &&
>         ( mbedtls_mpi_cmp_int( &ctx->P, 0 ) <= 0 ||
>           mbedtls_mpi_get_bit( &ctx->P, 0 ) == 0 ||
>           mbedtls_mpi_cmp_int( &ctx->Q, 0 ) <= 0 ||
>           mbedtls_mpi_get_bit( &ctx->Q, 0 ) == 0  ) )
>     {
>         return( MBEDTLS_ERR_RSA_BAD_INPUT_DATA );
>     }
> #endif /* !MBEDTLS_RSA_NO_CRT */
> ```
> 
> If CRT is not enabled, then the option `MBEDTLS_RSA_NO_CRT` is defined and consequently the condition `!defined(MBEDTLS_RSA_NO_CRT)` will be false and the above code will not be present in the build and the program can't fail there.
> 
> What am I missing?

sorry, I reexamined and found a problem with the description.
so reorganized the information again.

**Comment by yanesca** [comment]
> as a result that Keymaster TA in function TA_generate_key which on flie https://github.com/linaro-swg/kmgk/blob/master/keymaster/ta/generator.c This function will create rsa key pair with CRT, but mbedtls not support CRT by default , this will casues TA panic.

This is the part that I don't understand. Generating CRT keys means that the key has more information than a non-CRT key. If CRT is disabled in Mbed TLS, it should be able to handle CRT keys as well. It should simply ignore the additional information and commence the operation as usual.

Also, the test output you quoted ends with a segmentation fault. Whether the operation is supported by the Mbed TLS build at hand or not, it shouldn't result in a segmentation fault. Have you identified the reason for that segmentation fault?

**Comment by lubing521** [comment]
> > as a result that Keymaster TA in function TA_generate_key which on flie https://github.com/linaro-swg/kmgk/blob/master/keymaster/ta/generator.c This function will create rsa key pair with CRT, but mbedtls not support CRT by default , this will casues TA panic.
> 
> This is the part that I don't understand. Generating CRT keys means that the key has more information than a non-CRT key. If CRT is disabled in Mbed TLS, it should be able to handle CRT keys as well. It should simply ignore the additional information and commence the operation as usual.
> 
> Also, the test output you quoted ends with a segmentation fault. Whether the operation is supported by the Mbed TLS build at hand or not, it shouldn't result in a segmentation fault. Have you identified the reason for that segmentation fault?

My analysis is as follows:

Dump the segmention fault stack.
it panic in function TEE_WriteObjectData,The function is declared as follows.

TEE_Result TEE_WriteObjectData(TEE_ObjectHandle object, const void *buffer,
			       uint32_t ### size)

user app create the rsa key pari with CRT, It was meant to need CRT ,but libmedtls create they without CRT and return success.
so ,The app considers the creation  rsa key with CRT successful.
There was an error in the size provided during the subsequent save process.

```
E/TC:? 0
E/TC:? 0 TA panicked with code 0xffff0001
E/LD:  Status of TA b13a05fa-cfd9-4c8e-9409-db2118d19a2f
E/LD:   arch: aarch64
E/LD:  region  0: va 0x40004000 pa 0x81180000 size 0x002000 flags rw-s (ldelf)
E/LD:  region  1: va 0x40006000 pa 0x81182000 size 0x009000 flags r-xs (ldelf)
E/LD:  region  2: va 0x4000f000 pa 0x8118b000 size 0x001000 flags rw-s (ldelf)
E/LD:  region  3: va 0x40010000 pa 0x8118c000 size 0x004000 flags rw-s (ldelf)
E/LD:  region  4: va 0x40014000 pa 0x81190000 size 0x001000 flags r--s
E/LD:  region  5: va 0x40015000 pa 0x81234000 size 0x009000 flags rw-s (stack)
E/LD:  region  6: va 0x4001e000 pa 0xf07fd4a8 size 0x003000 flags rw-- (param)
E/LD:  region  7: va 0x40021000 pa 0xf15e04a8 size 0x002000 flags rw-- (param)
E/LD:  region  8: va 0x40084000 pa 0x00001000 size 0x050000 flags r-xs [0] .ta_head .text .rodata .dynsym .dynstr .hash .rela.dyn
E/LD:  region  9: va 0x400d4000 pa 0x00051000 size 0x053000 flags rw-s [0] .dynamic .got .rela.data .rela.got .data .bss
E/LD:   [0] b13a05fa-cfd9-4c8e-9409-db2118d19a2f @ 0x40084000 (out/target/product/ld60_evb/optee/ta/security_TAs_keymaster_ta/b13a05fa-cfd9-4c8e-9409-db2118d19a2f.elf)
E/LD:  Call stack:
E/LD:   0x0000000040097800 TEE_WriteObjectData at optee_os/lib/libutee/tee_api_objects.c:682
E/LD:   0x000000004008cd8c TA_write_obj_attr at keymaster/ta/generator.c:484
E/LD:   0x000000004008f714 TA_create_rsa_attest_key at keymaster/ta/attestation.c:450
E/LD:   0x0000000040085308 TA_attestKey at keymaster/ta/keystore_ta.c:914
E/LD:   0x0000000040086b20 TA_InvokeCommandEntryPoint at keymaster/ta/keystore_ta.c:1848
E/LD:   0x000000004009c0a0 entry_invoke_command at optee_os/lib/libutee/arch/arm/user_ta_entry.c:357
E/LD:   0x0000000040094e08 __ta_entry at out/optee/arm-plat-uniphier/export-ta_arm64/src/user_ta_header.c:47
```

TEE_Result TEE_WriteObjectData(TEE_ObjectHandle object, const void *buffer,
			       uint32_t size)
{
	TEE_Result res;

	if (object == TEE_HANDLE_NULL) {
		res = TEE_ERROR_BAD_PARAMETERS;
		goto out;
	}

	if (size > TEE_DATA_MAX_POSITION) {
		res = TEE_ERROR_OVERFLOW;
		goto out;
	}

	res = _utee_storage_obj_write((unsigned long)object, buffer, size);

out:
	if (res != TEE_SUCCESS &&
	    res != TEE_ERROR_STORAGE_NO_SPACE &&
	    res != TEE_ERROR_OVERFLOW &&
	    res != TEE_ERROR_CORRUPT_OBJECT &&
	    res != TEE_ERROR_STORAGE_NOT_AVAILABLE)
		### TEE_Panic(res);

	return res;
}

**Comment by yanesca** [comment]
@lubing521 Thank you for explaining, then if I understand correctly:
1. If `MBEDTLS_RSA_NO_CRT` is defined, Keymaster crashes because of a bug in the test.
2. If `MBEDTLS_RSA_NO_CRT` is not defined, xtest fails with keys without CRT components.

Can you confirm that my understanding is correct?

**Comment by lubing521** [comment]
> @lubing521 Thank you for explaining, then if I understand correctly:
> 
> 1. If `MBEDTLS_RSA_NO_CRT` is defined, Keymaster crashes because of a bug in the test.

> 2. If `MBEDTLS_RSA_NO_CRT` is not defined, xtest fails with keys without CRT components.
> 
> Can you confirm that my understanding is correct?

yes.

**Comment by yanesca** [comment]
@lubing521 Thank you for confirming!

This PR aims to address case 2. There are several ways to fix this and it takes some effort on our side to make a decision. Also, even after that it is very likely that some refactoring will be needed as well.

Because of this, this PR more complex than it looks at first and we will need to schedule it. I am adding it to the backlog now, but it will take some time until we will be able to schedule it.

**Comment by yanesca** [comment]
As I mentioned above, we need to schedule some resources to move this PR forward. This usually takes several months. If this is too long, in the mean time you could try to fix the bug in the Keymaster test suite, that could make things work with `MBEDTLS_RSA_NO_CRT` on.

**Comment by lubing521** [comment]
> As I mentioned above, we need to schedule some resources to move this PR forward. This usually takes several months. If this is too long, in the mean time you could try to fix the bug in the Keymaster test suite, that could make things work with `MBEDTLS_RSA_NO_CRT` on.

thanks.

**Comment by gilles-peskine-arm** [comment]
Note that this change is not needed for the objective. Mbed TLS can use keys without CRT parameters even when compiled without `MBEDTLS_RSA_NO_CRT`. You need to use the low-level RSA interface, import the parameters that you do have (n, e, d), and call `mbedtls_rsa_complete()`. This will calculate the CRT parameters. After this you can call the RSA signature/decryption functions normally.

**Pull request closed without merging**
