### PR TITLE
General support for subject alternative name subtypes

### PR DESCRIPTION
**Pull request by kevinmkane**
Introduce a data type to support more than the dNSName subtype
of a subject alternative name.

Add support using this mechanism to support the directoryName
subtype.

Add the MBEDTLS_X509_EXPANDED_SUBJECT_ALT_NAME_SUPPORT config.h
directive and enable it by default to include this support;
commenting this out will retain the previous interface.

### CODE REVIEW

**Comment by kevinmkane** [comment]
I haven't seen any activity on this PR in some time. Is there any interest in these additions?

**Comment by NWilson** [comment]
I would be interested. In our application, we have hundreds of lines of custom ASN.1 parsing to fill in the missing bits from mbedTLS. I've tried to open PRs before, but currently they have a backlog.

In our application, we need iPAddress and otherName support, and don't need the directoryName support you've implemented (not that I'm against adding it - just saying what our use-cases at RealVNC are).

**Comment by jpfr** [comment]
The OPC UA protocol (very common in industrial control applications) requires that the URI field in the Alternative Subject Names matches the application description.

We currently have an open bug for non-compliance that we cannot fix without adding a secondary ASN.1 parser just for the Alternative Subject Names.

https://github.com/open62541/open62541/issues/1902

It would be great if this PR could be merged, so we can iterate over all the fields in the Alternative Subject Names. Not just the DNS.

Note that the URI field is not supported by this PR at the moment.

**Comment by daverodgman** [comment]
Re-opening due to renewed interest in this functionality

**Comment by AndrzejKurek** [comment]
Somewhat of a general support for SubjectAltName was added to the library in https://github.com/Mbed-TLS/mbedtls/pull/2530.
A PR with an addition of directoryName parsing, based on the current state of code, can be seen here: https://github.com/Mbed-TLS/mbedtls/pull/6900
URI parsing (mentioned in the comments, needed for OPC UA) is added here: https://github.com/Mbed-TLS/mbedtls/pull/6847
Additional bugfix for SAN parsing, distantly related to this PR: https://github.com/Mbed-TLS/mbedtls/pull/6882.
If there's anything missing from the scope of this PR that isn't handled in others, let us know.
Thanks for bearing for so long!

**Comment by AndrzejKurek** [comment]
Closing this PR, as it is now superseeded.
Somewhat of a general support for SubjectAltName was added to the library in https://github.com/Mbed-TLS/mbedtls/pull/2530.
A PR with an addition of directoryName parsing, based on the current state of code, can be seen here: https://github.com/Mbed-TLS/mbedtls/pull/6900
URI parsing (mentioned in the comments, needed for OPC UA) is added here: https://github.com/Mbed-TLS/mbedtls/pull/6847
Additional bugfix for SAN parsing, distantly related to this PR: https://github.com/Mbed-TLS/mbedtls/pull/6882.
If there's anything missing from the scope of this PR that isn't handled in others, let us know.
Thanks for bearing for so long!

**Pull request closed without merging**
